// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/apikey"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/application"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
)

// ApiKeyUpdate is the builder for updating ApiKey entities.
type ApiKeyUpdate struct {
	config
	hooks    []Hook
	mutation *ApiKeyMutation
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (aku *ApiKeyUpdate) Where(ps ...predicate.ApiKey) *ApiKeyUpdate {
	aku.mutation.Where(ps...)
	return aku
}

// SetApplicationID sets the "application_id" field.
func (aku *ApiKeyUpdate) SetApplicationID(s string) *ApiKeyUpdate {
	aku.mutation.SetApplicationID(s)
	return aku
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableApplicationID(s *string) *ApiKeyUpdate {
	if s != nil {
		aku.SetApplicationID(*s)
	}
	return aku
}

// SetType sets the "type" field.
func (aku *ApiKeyUpdate) SetType(a apikey.Type) *ApiKeyUpdate {
	aku.mutation.SetType(a)
	return aku
}

// SetNillableType sets the "type" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableType(a *apikey.Type) *ApiKeyUpdate {
	if a != nil {
		aku.SetType(*a)
	}
	return aku
}

// SetKeyPrefix sets the "key_prefix" field.
func (aku *ApiKeyUpdate) SetKeyPrefix(s string) *ApiKeyUpdate {
	aku.mutation.SetKeyPrefix(s)
	return aku
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableKeyPrefix(s *string) *ApiKeyUpdate {
	if s != nil {
		aku.SetKeyPrefix(*s)
	}
	return aku
}

// SetKeyHash sets the "key_hash" field.
func (aku *ApiKeyUpdate) SetKeyHash(s string) *ApiKeyUpdate {
	aku.mutation.SetKeyHash(s)
	return aku
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableKeyHash(s *string) *ApiKeyUpdate {
	if s != nil {
		aku.SetKeyHash(*s)
	}
	return aku
}

// SetEnvironment sets the "environment" field.
func (aku *ApiKeyUpdate) SetEnvironment(a apikey.Environment) *ApiKeyUpdate {
	aku.mutation.SetEnvironment(a)
	return aku
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableEnvironment(a *apikey.Environment) *ApiKeyUpdate {
	if a != nil {
		aku.SetEnvironment(*a)
	}
	return aku
}

// SetName sets the "name" field.
func (aku *ApiKeyUpdate) SetName(s string) *ApiKeyUpdate {
	aku.mutation.SetName(s)
	return aku
}

// SetNillableName sets the "name" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableName(s *string) *ApiKeyUpdate {
	if s != nil {
		aku.SetName(*s)
	}
	return aku
}

// ClearName clears the value of the "name" field.
func (aku *ApiKeyUpdate) ClearName() *ApiKeyUpdate {
	aku.mutation.ClearName()
	return aku
}

// SetExpiresAt sets the "expires_at" field.
func (aku *ApiKeyUpdate) SetExpiresAt(t time.Time) *ApiKeyUpdate {
	aku.mutation.SetExpiresAt(t)
	return aku
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableExpiresAt(t *time.Time) *ApiKeyUpdate {
	if t != nil {
		aku.SetExpiresAt(*t)
	}
	return aku
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (aku *ApiKeyUpdate) ClearExpiresAt() *ApiKeyUpdate {
	aku.mutation.ClearExpiresAt()
	return aku
}

// SetLastUsedAt sets the "last_used_at" field.
func (aku *ApiKeyUpdate) SetLastUsedAt(t time.Time) *ApiKeyUpdate {
	aku.mutation.SetLastUsedAt(t)
	return aku
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableLastUsedAt(t *time.Time) *ApiKeyUpdate {
	if t != nil {
		aku.SetLastUsedAt(*t)
	}
	return aku
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (aku *ApiKeyUpdate) ClearLastUsedAt() *ApiKeyUpdate {
	aku.mutation.ClearLastUsedAt()
	return aku
}

// SetRevokedAt sets the "revoked_at" field.
func (aku *ApiKeyUpdate) SetRevokedAt(t time.Time) *ApiKeyUpdate {
	aku.mutation.SetRevokedAt(t)
	return aku
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableRevokedAt(t *time.Time) *ApiKeyUpdate {
	if t != nil {
		aku.SetRevokedAt(*t)
	}
	return aku
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (aku *ApiKeyUpdate) ClearRevokedAt() *ApiKeyUpdate {
	aku.mutation.ClearRevokedAt()
	return aku
}

// SetApplication sets the "application" edge to the Application entity.
func (aku *ApiKeyUpdate) SetApplication(a *Application) *ApiKeyUpdate {
	return aku.SetApplicationID(a.ID)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (aku *ApiKeyUpdate) Mutation() *ApiKeyMutation {
	return aku.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (aku *ApiKeyUpdate) ClearApplication() *ApiKeyUpdate {
	aku.mutation.ClearApplication()
	return aku
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aku *ApiKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aku.sqlSave, aku.mutation, aku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aku *ApiKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := aku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aku *ApiKeyUpdate) Exec(ctx context.Context) error {
	_, err := aku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aku *ApiKeyUpdate) ExecX(ctx context.Context) {
	if err := aku.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aku *ApiKeyUpdate) check() error {
	if v, ok := aku.mutation.ApplicationID(); ok {
		if err := apikey.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApiKey.application_id": %w`, err)}
		}
	}
	if v, ok := aku.mutation.GetType(); ok {
		if err := apikey.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ApiKey.type": %w`, err)}
		}
	}
	if v, ok := aku.mutation.KeyPrefix(); ok {
		if err := apikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_prefix": %w`, err)}
		}
	}
	if v, ok := aku.mutation.KeyHash(); ok {
		if err := apikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_hash": %w`, err)}
		}
	}
	if v, ok := aku.mutation.Environment(); ok {
		if err := apikey.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "ApiKey.environment": %w`, err)}
		}
	}
	if aku.mutation.ApplicationCleared() && len(aku.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKey.application"`)
	}
	return nil
}

func (aku *ApiKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aku.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	if ps := aku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aku.mutation.GetType(); ok {
		_spec.SetField(apikey.FieldType, field.TypeEnum, value)
	}
	if value, ok := aku.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := aku.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := aku.mutation.Environment(); ok {
		_spec.SetField(apikey.FieldEnvironment, field.TypeEnum, value)
	}
	if value, ok := aku.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if aku.mutation.NameCleared() {
		_spec.ClearField(apikey.FieldName, field.TypeString)
	}
	if value, ok := aku.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
	}
	if aku.mutation.ExpiresAtCleared() {
		_spec.ClearField(apikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := aku.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if aku.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := aku.mutation.RevokedAt(); ok {
		_spec.SetField(apikey.FieldRevokedAt, field.TypeTime, value)
	}
	if aku.mutation.RevokedAtCleared() {
		_spec.ClearField(apikey.FieldRevokedAt, field.TypeTime)
	}
	if aku.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.ApplicationTable,
			Columns: []string{apikey.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aku.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.ApplicationTable,
			Columns: []string{apikey.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aku.mutation.done = true
	return n, nil
}

// ApiKeyUpdateOne is the builder for updating a single ApiKey entity.
type ApiKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiKeyMutation
}

// SetApplicationID sets the "application_id" field.
func (akuo *ApiKeyUpdateOne) SetApplicationID(s string) *ApiKeyUpdateOne {
	akuo.mutation.SetApplicationID(s)
	return akuo
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableApplicationID(s *string) *ApiKeyUpdateOne {
	if s != nil {
		akuo.SetApplicationID(*s)
	}
	return akuo
}

// SetType sets the "type" field.
func (akuo *ApiKeyUpdateOne) SetType(a apikey.Type) *ApiKeyUpdateOne {
	akuo.mutation.SetType(a)
	return akuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableType(a *apikey.Type) *ApiKeyUpdateOne {
	if a != nil {
		akuo.SetType(*a)
	}
	return akuo
}

// SetKeyPrefix sets the "key_prefix" field.
func (akuo *ApiKeyUpdateOne) SetKeyPrefix(s string) *ApiKeyUpdateOne {
	akuo.mutation.SetKeyPrefix(s)
	return akuo
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableKeyPrefix(s *string) *ApiKeyUpdateOne {
	if s != nil {
		akuo.SetKeyPrefix(*s)
	}
	return akuo
}

// SetKeyHash sets the "key_hash" field.
func (akuo *ApiKeyUpdateOne) SetKeyHash(s string) *ApiKeyUpdateOne {
	akuo.mutation.SetKeyHash(s)
	return akuo
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableKeyHash(s *string) *ApiKeyUpdateOne {
	if s != nil {
		akuo.SetKeyHash(*s)
	}
	return akuo
}

// SetEnvironment sets the "environment" field.
func (akuo *ApiKeyUpdateOne) SetEnvironment(a apikey.Environment) *ApiKeyUpdateOne {
	akuo.mutation.SetEnvironment(a)
	return akuo
}

// SetNillableEnvironment sets the "environment" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableEnvironment(a *apikey.Environment) *ApiKeyUpdateOne {
	if a != nil {
		akuo.SetEnvironment(*a)
	}
	return akuo
}

// SetName sets the "name" field.
func (akuo *ApiKeyUpdateOne) SetName(s string) *ApiKeyUpdateOne {
	akuo.mutation.SetName(s)
	return akuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableName(s *string) *ApiKeyUpdateOne {
	if s != nil {
		akuo.SetName(*s)
	}
	return akuo
}

// ClearName clears the value of the "name" field.
func (akuo *ApiKeyUpdateOne) ClearName() *ApiKeyUpdateOne {
	akuo.mutation.ClearName()
	return akuo
}

// SetExpiresAt sets the "expires_at" field.
func (akuo *ApiKeyUpdateOne) SetExpiresAt(t time.Time) *ApiKeyUpdateOne {
	akuo.mutation.SetExpiresAt(t)
	return akuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableExpiresAt(t *time.Time) *ApiKeyUpdateOne {
	if t != nil {
		akuo.SetExpiresAt(*t)
	}
	return akuo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (akuo *ApiKeyUpdateOne) ClearExpiresAt() *ApiKeyUpdateOne {
	akuo.mutation.ClearExpiresAt()
	return akuo
}

// SetLastUsedAt sets the "last_used_at" field.
func (akuo *ApiKeyUpdateOne) SetLastUsedAt(t time.Time) *ApiKeyUpdateOne {
	akuo.mutation.SetLastUsedAt(t)
	return akuo
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableLastUsedAt(t *time.Time) *ApiKeyUpdateOne {
	if t != nil {
		akuo.SetLastUsedAt(*t)
	}
	return akuo
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (akuo *ApiKeyUpdateOne) ClearLastUsedAt() *ApiKeyUpdateOne {
	akuo.mutation.ClearLastUsedAt()
	return akuo
}

// SetRevokedAt sets the "revoked_at" field.
func (akuo *ApiKeyUpdateOne) SetRevokedAt(t time.Time) *ApiKeyUpdateOne {
	akuo.mutation.SetRevokedAt(t)
	return akuo
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableRevokedAt(t *time.Time) *ApiKeyUpdateOne {
	if t != nil {
		akuo.SetRevokedAt(*t)
	}
	return akuo
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (akuo *ApiKeyUpdateOne) ClearRevokedAt() *ApiKeyUpdateOne {
	akuo.mutation.ClearRevokedAt()
	return akuo
}

// SetApplication sets the "application" edge to the Application entity.
func (akuo *ApiKeyUpdateOne) SetApplication(a *Application) *ApiKeyUpdateOne {
	return akuo.SetApplicationID(a.ID)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (akuo *ApiKeyUpdateOne) Mutation() *ApiKeyMutation {
	return akuo.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (akuo *ApiKeyUpdateOne) ClearApplication() *ApiKeyUpdateOne {
	akuo.mutation.ClearApplication()
	return akuo
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (akuo *ApiKeyUpdateOne) Where(ps ...predicate.ApiKey) *ApiKeyUpdateOne {
	akuo.mutation.Where(ps...)
	return akuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (akuo *ApiKeyUpdateOne) Select(field string, fields ...string) *ApiKeyUpdateOne {
	akuo.fields = append([]string{field}, fields...)
	return akuo
}

// Save executes the query and returns the updated ApiKey entity.
func (akuo *ApiKeyUpdateOne) Save(ctx context.Context) (*ApiKey, error) {
	return withHooks(ctx, akuo.sqlSave, akuo.mutation, akuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (akuo *ApiKeyUpdateOne) SaveX(ctx context.Context) *ApiKey {
	node, err := akuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (akuo *ApiKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := akuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akuo *ApiKeyUpdateOne) ExecX(ctx context.Context) {
	if err := akuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (akuo *ApiKeyUpdateOne) check() error {
	if v, ok := akuo.mutation.ApplicationID(); ok {
		if err := apikey.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "ApiKey.application_id": %w`, err)}
		}
	}
	if v, ok := akuo.mutation.GetType(); ok {
		if err := apikey.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ApiKey.type": %w`, err)}
		}
	}
	if v, ok := akuo.mutation.KeyPrefix(); ok {
		if err := apikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_prefix": %w`, err)}
		}
	}
	if v, ok := akuo.mutation.KeyHash(); ok {
		if err := apikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_hash": %w`, err)}
		}
	}
	if v, ok := akuo.mutation.Environment(); ok {
		if err := apikey.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "ApiKey.environment": %w`, err)}
		}
	}
	if akuo.mutation.ApplicationCleared() && len(akuo.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKey.application"`)
	}
	return nil
}

func (akuo *ApiKeyUpdateOne) sqlSave(ctx context.Context) (_node *ApiKey, err error) {
	if err := akuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	id, ok := akuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := akuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := akuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := akuo.mutation.GetType(); ok {
		_spec.SetField(apikey.FieldType, field.TypeEnum, value)
	}
	if value, ok := akuo.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := akuo.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := akuo.mutation.Environment(); ok {
		_spec.SetField(apikey.FieldEnvironment, field.TypeEnum, value)
	}
	if value, ok := akuo.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if akuo.mutation.NameCleared() {
		_spec.ClearField(apikey.FieldName, field.TypeString)
	}
	if value, ok := akuo.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
	}
	if akuo.mutation.ExpiresAtCleared() {
		_spec.ClearField(apikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := akuo.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if akuo.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := akuo.mutation.RevokedAt(); ok {
		_spec.SetField(apikey.FieldRevokedAt, field.TypeTime, value)
	}
	if akuo.mutation.RevokedAtCleared() {
		_spec.ClearField(apikey.FieldRevokedAt, field.TypeTime)
	}
	if akuo.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.ApplicationTable,
			Columns: []string{apikey.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := akuo.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.ApplicationTable,
			Columns: []string{apikey.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiKey{config: akuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, akuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	akuo.mutation.done = true
	return _node, nil
}
