// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/auditlog"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/tenant"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (alu *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	alu.mutation.Where(ps...)
	return alu
}

// SetTenantID sets the "tenant_id" field.
func (alu *AuditLogUpdate) SetTenantID(s string) *AuditLogUpdate {
	alu.mutation.SetTenantID(s)
	return alu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableTenantID(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetTenantID(*s)
	}
	return alu
}

// SetApplicationID sets the "application_id" field.
func (alu *AuditLogUpdate) SetApplicationID(s string) *AuditLogUpdate {
	alu.mutation.SetApplicationID(s)
	return alu
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableApplicationID(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetApplicationID(*s)
	}
	return alu
}

// ClearApplicationID clears the value of the "application_id" field.
func (alu *AuditLogUpdate) ClearApplicationID() *AuditLogUpdate {
	alu.mutation.ClearApplicationID()
	return alu
}

// SetUserID sets the "user_id" field.
func (alu *AuditLogUpdate) SetUserID(s string) *AuditLogUpdate {
	alu.mutation.SetUserID(s)
	return alu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableUserID(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetUserID(*s)
	}
	return alu
}

// ClearUserID clears the value of the "user_id" field.
func (alu *AuditLogUpdate) ClearUserID() *AuditLogUpdate {
	alu.mutation.ClearUserID()
	return alu
}

// SetAPIKeyID sets the "api_key_id" field.
func (alu *AuditLogUpdate) SetAPIKeyID(s string) *AuditLogUpdate {
	alu.mutation.SetAPIKeyID(s)
	return alu
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableAPIKeyID(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetAPIKeyID(*s)
	}
	return alu
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (alu *AuditLogUpdate) ClearAPIKeyID() *AuditLogUpdate {
	alu.mutation.ClearAPIKeyID()
	return alu
}

// SetActorType sets the "actor_type" field.
func (alu *AuditLogUpdate) SetActorType(at auditlog.ActorType) *AuditLogUpdate {
	alu.mutation.SetActorType(at)
	return alu
}

// SetNillableActorType sets the "actor_type" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableActorType(at *auditlog.ActorType) *AuditLogUpdate {
	if at != nil {
		alu.SetActorType(*at)
	}
	return alu
}

// SetEventType sets the "event_type" field.
func (alu *AuditLogUpdate) SetEventType(s string) *AuditLogUpdate {
	alu.mutation.SetEventType(s)
	return alu
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableEventType(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetEventType(*s)
	}
	return alu
}

// SetIPAddress sets the "ip_address" field.
func (alu *AuditLogUpdate) SetIPAddress(s string) *AuditLogUpdate {
	alu.mutation.SetIPAddress(s)
	return alu
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableIPAddress(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetIPAddress(*s)
	}
	return alu
}

// ClearIPAddress clears the value of the "ip_address" field.
func (alu *AuditLogUpdate) ClearIPAddress() *AuditLogUpdate {
	alu.mutation.ClearIPAddress()
	return alu
}

// SetRequestOrigin sets the "request_origin" field.
func (alu *AuditLogUpdate) SetRequestOrigin(s string) *AuditLogUpdate {
	alu.mutation.SetRequestOrigin(s)
	return alu
}

// SetNillableRequestOrigin sets the "request_origin" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableRequestOrigin(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetRequestOrigin(*s)
	}
	return alu
}

// ClearRequestOrigin clears the value of the "request_origin" field.
func (alu *AuditLogUpdate) ClearRequestOrigin() *AuditLogUpdate {
	alu.mutation.ClearRequestOrigin()
	return alu
}

// SetUserAgent sets the "user_agent" field.
func (alu *AuditLogUpdate) SetUserAgent(s string) *AuditLogUpdate {
	alu.mutation.SetUserAgent(s)
	return alu
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableUserAgent(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetUserAgent(*s)
	}
	return alu
}

// ClearUserAgent clears the value of the "user_agent" field.
func (alu *AuditLogUpdate) ClearUserAgent() *AuditLogUpdate {
	alu.mutation.ClearUserAgent()
	return alu
}

// SetMetadata sets the "metadata" field.
func (alu *AuditLogUpdate) SetMetadata(m map[string]interface{}) *AuditLogUpdate {
	alu.mutation.SetMetadata(m)
	return alu
}

// ClearMetadata clears the value of the "metadata" field.
func (alu *AuditLogUpdate) ClearMetadata() *AuditLogUpdate {
	alu.mutation.ClearMetadata()
	return alu
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (alu *AuditLogUpdate) SetTenant(t *Tenant) *AuditLogUpdate {
	return alu.SetTenantID(t.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (alu *AuditLogUpdate) Mutation() *AuditLogMutation {
	return alu.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (alu *AuditLogUpdate) ClearTenant() *AuditLogUpdate {
	alu.mutation.ClearTenant()
	return alu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (alu *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, alu.sqlSave, alu.mutation, alu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (alu *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := alu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (alu *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := alu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alu *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := alu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (alu *AuditLogUpdate) check() error {
	if v, ok := alu.mutation.TenantID(); ok {
		if err := auditlog.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.tenant_id": %w`, err)}
		}
	}
	if v, ok := alu.mutation.ActorType(); ok {
		if err := auditlog.ActorTypeValidator(v); err != nil {
			return &ValidationError{Name: "actor_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_type": %w`, err)}
		}
	}
	if v, ok := alu.mutation.EventType(); ok {
		if err := auditlog.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.event_type": %w`, err)}
		}
	}
	if alu.mutation.TenantCleared() && len(alu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditLog.tenant"`)
	}
	return nil
}

func (alu *AuditLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := alu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeString))
	if ps := alu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := alu.mutation.ApplicationID(); ok {
		_spec.SetField(auditlog.FieldApplicationID, field.TypeString, value)
	}
	if alu.mutation.ApplicationIDCleared() {
		_spec.ClearField(auditlog.FieldApplicationID, field.TypeString)
	}
	if value, ok := alu.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeString, value)
	}
	if alu.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeString)
	}
	if value, ok := alu.mutation.APIKeyID(); ok {
		_spec.SetField(auditlog.FieldAPIKeyID, field.TypeString, value)
	}
	if alu.mutation.APIKeyIDCleared() {
		_spec.ClearField(auditlog.FieldAPIKeyID, field.TypeString)
	}
	if value, ok := alu.mutation.ActorType(); ok {
		_spec.SetField(auditlog.FieldActorType, field.TypeEnum, value)
	}
	if value, ok := alu.mutation.EventType(); ok {
		_spec.SetField(auditlog.FieldEventType, field.TypeString, value)
	}
	if value, ok := alu.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if alu.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := alu.mutation.RequestOrigin(); ok {
		_spec.SetField(auditlog.FieldRequestOrigin, field.TypeString, value)
	}
	if alu.mutation.RequestOriginCleared() {
		_spec.ClearField(auditlog.FieldRequestOrigin, field.TypeString)
	}
	if value, ok := alu.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if alu.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := alu.mutation.Metadata(); ok {
		_spec.SetField(auditlog.FieldMetadata, field.TypeJSON, value)
	}
	if alu.mutation.MetadataCleared() {
		_spec.ClearField(auditlog.FieldMetadata, field.TypeJSON)
	}
	if alu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: []string{auditlog.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := alu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: []string{auditlog.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, alu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	alu.mutation.done = true
	return n, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetTenantID sets the "tenant_id" field.
func (aluo *AuditLogUpdateOne) SetTenantID(s string) *AuditLogUpdateOne {
	aluo.mutation.SetTenantID(s)
	return aluo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableTenantID(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetTenantID(*s)
	}
	return aluo
}

// SetApplicationID sets the "application_id" field.
func (aluo *AuditLogUpdateOne) SetApplicationID(s string) *AuditLogUpdateOne {
	aluo.mutation.SetApplicationID(s)
	return aluo
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableApplicationID(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetApplicationID(*s)
	}
	return aluo
}

// ClearApplicationID clears the value of the "application_id" field.
func (aluo *AuditLogUpdateOne) ClearApplicationID() *AuditLogUpdateOne {
	aluo.mutation.ClearApplicationID()
	return aluo
}

// SetUserID sets the "user_id" field.
func (aluo *AuditLogUpdateOne) SetUserID(s string) *AuditLogUpdateOne {
	aluo.mutation.SetUserID(s)
	return aluo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableUserID(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetUserID(*s)
	}
	return aluo
}

// ClearUserID clears the value of the "user_id" field.
func (aluo *AuditLogUpdateOne) ClearUserID() *AuditLogUpdateOne {
	aluo.mutation.ClearUserID()
	return aluo
}

// SetAPIKeyID sets the "api_key_id" field.
func (aluo *AuditLogUpdateOne) SetAPIKeyID(s string) *AuditLogUpdateOne {
	aluo.mutation.SetAPIKeyID(s)
	return aluo
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableAPIKeyID(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetAPIKeyID(*s)
	}
	return aluo
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (aluo *AuditLogUpdateOne) ClearAPIKeyID() *AuditLogUpdateOne {
	aluo.mutation.ClearAPIKeyID()
	return aluo
}

// SetActorType sets the "actor_type" field.
func (aluo *AuditLogUpdateOne) SetActorType(at auditlog.ActorType) *AuditLogUpdateOne {
	aluo.mutation.SetActorType(at)
	return aluo
}

// SetNillableActorType sets the "actor_type" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableActorType(at *auditlog.ActorType) *AuditLogUpdateOne {
	if at != nil {
		aluo.SetActorType(*at)
	}
	return aluo
}

// SetEventType sets the "event_type" field.
func (aluo *AuditLogUpdateOne) SetEventType(s string) *AuditLogUpdateOne {
	aluo.mutation.SetEventType(s)
	return aluo
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableEventType(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetEventType(*s)
	}
	return aluo
}

// SetIPAddress sets the "ip_address" field.
func (aluo *AuditLogUpdateOne) SetIPAddress(s string) *AuditLogUpdateOne {
	aluo.mutation.SetIPAddress(s)
	return aluo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableIPAddress(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetIPAddress(*s)
	}
	return aluo
}

// ClearIPAddress clears the value of the "ip_address" field.
func (aluo *AuditLogUpdateOne) ClearIPAddress() *AuditLogUpdateOne {
	aluo.mutation.ClearIPAddress()
	return aluo
}

// SetRequestOrigin sets the "request_origin" field.
func (aluo *AuditLogUpdateOne) SetRequestOrigin(s string) *AuditLogUpdateOne {
	aluo.mutation.SetRequestOrigin(s)
	return aluo
}

// SetNillableRequestOrigin sets the "request_origin" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableRequestOrigin(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetRequestOrigin(*s)
	}
	return aluo
}

// ClearRequestOrigin clears the value of the "request_origin" field.
func (aluo *AuditLogUpdateOne) ClearRequestOrigin() *AuditLogUpdateOne {
	aluo.mutation.ClearRequestOrigin()
	return aluo
}

// SetUserAgent sets the "user_agent" field.
func (aluo *AuditLogUpdateOne) SetUserAgent(s string) *AuditLogUpdateOne {
	aluo.mutation.SetUserAgent(s)
	return aluo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableUserAgent(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetUserAgent(*s)
	}
	return aluo
}

// ClearUserAgent clears the value of the "user_agent" field.
func (aluo *AuditLogUpdateOne) ClearUserAgent() *AuditLogUpdateOne {
	aluo.mutation.ClearUserAgent()
	return aluo
}

// SetMetadata sets the "metadata" field.
func (aluo *AuditLogUpdateOne) SetMetadata(m map[string]interface{}) *AuditLogUpdateOne {
	aluo.mutation.SetMetadata(m)
	return aluo
}

// ClearMetadata clears the value of the "metadata" field.
func (aluo *AuditLogUpdateOne) ClearMetadata() *AuditLogUpdateOne {
	aluo.mutation.ClearMetadata()
	return aluo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (aluo *AuditLogUpdateOne) SetTenant(t *Tenant) *AuditLogUpdateOne {
	return aluo.SetTenantID(t.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (aluo *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return aluo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (aluo *AuditLogUpdateOne) ClearTenant() *AuditLogUpdateOne {
	aluo.mutation.ClearTenant()
	return aluo
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (aluo *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	aluo.mutation.Where(ps...)
	return aluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aluo *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	aluo.fields = append([]string{field}, fields...)
	return aluo
}

// Save executes the query and returns the updated AuditLog entity.
func (aluo *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, aluo.sqlSave, aluo.mutation, aluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := aluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aluo *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := aluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := aluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aluo *AuditLogUpdateOne) check() error {
	if v, ok := aluo.mutation.TenantID(); ok {
		if err := auditlog.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.tenant_id": %w`, err)}
		}
	}
	if v, ok := aluo.mutation.ActorType(); ok {
		if err := auditlog.ActorTypeValidator(v); err != nil {
			return &ValidationError{Name: "actor_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_type": %w`, err)}
		}
	}
	if v, ok := aluo.mutation.EventType(); ok {
		if err := auditlog.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.event_type": %w`, err)}
		}
	}
	if aluo.mutation.TenantCleared() && len(aluo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditLog.tenant"`)
	}
	return nil
}

func (aluo *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := aluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeString))
	id, ok := aluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aluo.mutation.ApplicationID(); ok {
		_spec.SetField(auditlog.FieldApplicationID, field.TypeString, value)
	}
	if aluo.mutation.ApplicationIDCleared() {
		_spec.ClearField(auditlog.FieldApplicationID, field.TypeString)
	}
	if value, ok := aluo.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeString, value)
	}
	if aluo.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeString)
	}
	if value, ok := aluo.mutation.APIKeyID(); ok {
		_spec.SetField(auditlog.FieldAPIKeyID, field.TypeString, value)
	}
	if aluo.mutation.APIKeyIDCleared() {
		_spec.ClearField(auditlog.FieldAPIKeyID, field.TypeString)
	}
	if value, ok := aluo.mutation.ActorType(); ok {
		_spec.SetField(auditlog.FieldActorType, field.TypeEnum, value)
	}
	if value, ok := aluo.mutation.EventType(); ok {
		_spec.SetField(auditlog.FieldEventType, field.TypeString, value)
	}
	if value, ok := aluo.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if aluo.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := aluo.mutation.RequestOrigin(); ok {
		_spec.SetField(auditlog.FieldRequestOrigin, field.TypeString, value)
	}
	if aluo.mutation.RequestOriginCleared() {
		_spec.ClearField(auditlog.FieldRequestOrigin, field.TypeString)
	}
	if value, ok := aluo.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if aluo.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := aluo.mutation.Metadata(); ok {
		_spec.SetField(auditlog.FieldMetadata, field.TypeJSON, value)
	}
	if aluo.mutation.MetadataCleared() {
		_spec.ClearField(auditlog.FieldMetadata, field.TypeJSON)
	}
	if aluo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: []string{auditlog.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aluo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.TenantTable,
			Columns: []string{auditlog.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuditLog{config: aluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aluo.mutation.done = true
	return _node, nil
}
