// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/managedtenant"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/tenant"
)

// ManagedTenantUpdate is the builder for updating ManagedTenant entities.
type ManagedTenantUpdate struct {
	config
	hooks    []Hook
	mutation *ManagedTenantMutation
}

// Where appends a list predicates to the ManagedTenantUpdate builder.
func (mtu *ManagedTenantUpdate) Where(ps ...predicate.ManagedTenant) *ManagedTenantUpdate {
	mtu.mutation.Where(ps...)
	return mtu
}

// SetTenantID sets the "tenant_id" field.
func (mtu *ManagedTenantUpdate) SetTenantID(s string) *ManagedTenantUpdate {
	mtu.mutation.SetTenantID(s)
	return mtu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (mtu *ManagedTenantUpdate) SetNillableTenantID(s *string) *ManagedTenantUpdate {
	if s != nil {
		mtu.SetTenantID(*s)
	}
	return mtu
}

// SetRole sets the "role" field.
func (mtu *ManagedTenantUpdate) SetRole(m managedtenant.Role) *ManagedTenantUpdate {
	mtu.mutation.SetRole(m)
	return mtu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (mtu *ManagedTenantUpdate) SetNillableRole(m *managedtenant.Role) *ManagedTenantUpdate {
	if m != nil {
		mtu.SetRole(*m)
	}
	return mtu
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (mtu *ManagedTenantUpdate) SetTenant(t *Tenant) *ManagedTenantUpdate {
	return mtu.SetTenantID(t.ID)
}

// Mutation returns the ManagedTenantMutation object of the builder.
func (mtu *ManagedTenantUpdate) Mutation() *ManagedTenantMutation {
	return mtu.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (mtu *ManagedTenantUpdate) ClearTenant() *ManagedTenantUpdate {
	mtu.mutation.ClearTenant()
	return mtu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mtu *ManagedTenantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mtu.sqlSave, mtu.mutation, mtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtu *ManagedTenantUpdate) SaveX(ctx context.Context) int {
	affected, err := mtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mtu *ManagedTenantUpdate) Exec(ctx context.Context) error {
	_, err := mtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtu *ManagedTenantUpdate) ExecX(ctx context.Context) {
	if err := mtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtu *ManagedTenantUpdate) check() error {
	if v, ok := mtu.mutation.TenantID(); ok {
		if err := managedtenant.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ManagedTenant.tenant_id": %w`, err)}
		}
	}
	if v, ok := mtu.mutation.Role(); ok {
		if err := managedtenant.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ManagedTenant.role": %w`, err)}
		}
	}
	if mtu.mutation.TenantCleared() && len(mtu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedTenant.tenant"`)
	}
	return nil
}

func (mtu *ManagedTenantUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedtenant.Table, managedtenant.Columns, sqlgraph.NewFieldSpec(managedtenant.FieldID, field.TypeString))
	if ps := mtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtu.mutation.Role(); ok {
		_spec.SetField(managedtenant.FieldRole, field.TypeEnum, value)
	}
	if mtu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedtenant.TenantTable,
			Columns: []string{managedtenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedtenant.TenantTable,
			Columns: []string{managedtenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedtenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mtu.mutation.done = true
	return n, nil
}

// ManagedTenantUpdateOne is the builder for updating a single ManagedTenant entity.
type ManagedTenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ManagedTenantMutation
}

// SetTenantID sets the "tenant_id" field.
func (mtuo *ManagedTenantUpdateOne) SetTenantID(s string) *ManagedTenantUpdateOne {
	mtuo.mutation.SetTenantID(s)
	return mtuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (mtuo *ManagedTenantUpdateOne) SetNillableTenantID(s *string) *ManagedTenantUpdateOne {
	if s != nil {
		mtuo.SetTenantID(*s)
	}
	return mtuo
}

// SetRole sets the "role" field.
func (mtuo *ManagedTenantUpdateOne) SetRole(m managedtenant.Role) *ManagedTenantUpdateOne {
	mtuo.mutation.SetRole(m)
	return mtuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (mtuo *ManagedTenantUpdateOne) SetNillableRole(m *managedtenant.Role) *ManagedTenantUpdateOne {
	if m != nil {
		mtuo.SetRole(*m)
	}
	return mtuo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (mtuo *ManagedTenantUpdateOne) SetTenant(t *Tenant) *ManagedTenantUpdateOne {
	return mtuo.SetTenantID(t.ID)
}

// Mutation returns the ManagedTenantMutation object of the builder.
func (mtuo *ManagedTenantUpdateOne) Mutation() *ManagedTenantMutation {
	return mtuo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (mtuo *ManagedTenantUpdateOne) ClearTenant() *ManagedTenantUpdateOne {
	mtuo.mutation.ClearTenant()
	return mtuo
}

// Where appends a list predicates to the ManagedTenantUpdate builder.
func (mtuo *ManagedTenantUpdateOne) Where(ps ...predicate.ManagedTenant) *ManagedTenantUpdateOne {
	mtuo.mutation.Where(ps...)
	return mtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mtuo *ManagedTenantUpdateOne) Select(field string, fields ...string) *ManagedTenantUpdateOne {
	mtuo.fields = append([]string{field}, fields...)
	return mtuo
}

// Save executes the query and returns the updated ManagedTenant entity.
func (mtuo *ManagedTenantUpdateOne) Save(ctx context.Context) (*ManagedTenant, error) {
	return withHooks(ctx, mtuo.sqlSave, mtuo.mutation, mtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtuo *ManagedTenantUpdateOne) SaveX(ctx context.Context) *ManagedTenant {
	node, err := mtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mtuo *ManagedTenantUpdateOne) Exec(ctx context.Context) error {
	_, err := mtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtuo *ManagedTenantUpdateOne) ExecX(ctx context.Context) {
	if err := mtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtuo *ManagedTenantUpdateOne) check() error {
	if v, ok := mtuo.mutation.TenantID(); ok {
		if err := managedtenant.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ManagedTenant.tenant_id": %w`, err)}
		}
	}
	if v, ok := mtuo.mutation.Role(); ok {
		if err := managedtenant.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ManagedTenant.role": %w`, err)}
		}
	}
	if mtuo.mutation.TenantCleared() && len(mtuo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ManagedTenant.tenant"`)
	}
	return nil
}

func (mtuo *ManagedTenantUpdateOne) sqlSave(ctx context.Context) (_node *ManagedTenant, err error) {
	if err := mtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedtenant.Table, managedtenant.Columns, sqlgraph.NewFieldSpec(managedtenant.FieldID, field.TypeString))
	id, ok := mtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ManagedTenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managedtenant.FieldID)
		for _, f := range fields {
			if !managedtenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != managedtenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtuo.mutation.Role(); ok {
		_spec.SetField(managedtenant.FieldRole, field.TypeEnum, value)
	}
	if mtuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedtenant.TenantTable,
			Columns: []string{managedtenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtuo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedtenant.TenantTable,
			Columns: []string{managedtenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ManagedTenant{config: mtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedtenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mtuo.mutation.done = true
	return _node, nil
}
