// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/organization"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/orgmember"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/role"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/user"
)

// OrgMemberCreate is the builder for creating a OrgMember entity.
type OrgMemberCreate struct {
	config
	mutation *OrgMemberMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (omc *OrgMemberCreate) SetOrganizationID(s string) *OrgMemberCreate {
	omc.mutation.SetOrganizationID(s)
	return omc
}

// SetUserID sets the "user_id" field.
func (omc *OrgMemberCreate) SetUserID(s string) *OrgMemberCreate {
	omc.mutation.SetUserID(s)
	return omc
}

// SetRoleID sets the "role_id" field.
func (omc *OrgMemberCreate) SetRoleID(s string) *OrgMemberCreate {
	omc.mutation.SetRoleID(s)
	return omc
}

// SetAssignedByUserID sets the "assigned_by_user_id" field.
func (omc *OrgMemberCreate) SetAssignedByUserID(s string) *OrgMemberCreate {
	omc.mutation.SetAssignedByUserID(s)
	return omc
}

// SetNillableAssignedByUserID sets the "assigned_by_user_id" field if the given value is not nil.
func (omc *OrgMemberCreate) SetNillableAssignedByUserID(s *string) *OrgMemberCreate {
	if s != nil {
		omc.SetAssignedByUserID(*s)
	}
	return omc
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (omc *OrgMemberCreate) SetUpdatedByUserID(s string) *OrgMemberCreate {
	omc.mutation.SetUpdatedByUserID(s)
	return omc
}

// SetNillableUpdatedByUserID sets the "updated_by_user_id" field if the given value is not nil.
func (omc *OrgMemberCreate) SetNillableUpdatedByUserID(s *string) *OrgMemberCreate {
	if s != nil {
		omc.SetUpdatedByUserID(*s)
	}
	return omc
}

// SetCreatedAt sets the "created_at" field.
func (omc *OrgMemberCreate) SetCreatedAt(t time.Time) *OrgMemberCreate {
	omc.mutation.SetCreatedAt(t)
	return omc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (omc *OrgMemberCreate) SetNillableCreatedAt(t *time.Time) *OrgMemberCreate {
	if t != nil {
		omc.SetCreatedAt(*t)
	}
	return omc
}

// SetUpdatedAt sets the "updated_at" field.
func (omc *OrgMemberCreate) SetUpdatedAt(t time.Time) *OrgMemberCreate {
	omc.mutation.SetUpdatedAt(t)
	return omc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (omc *OrgMemberCreate) SetNillableUpdatedAt(t *time.Time) *OrgMemberCreate {
	if t != nil {
		omc.SetUpdatedAt(*t)
	}
	return omc
}

// SetID sets the "id" field.
func (omc *OrgMemberCreate) SetID(s string) *OrgMemberCreate {
	omc.mutation.SetID(s)
	return omc
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (omc *OrgMemberCreate) SetOrganization(o *Organization) *OrgMemberCreate {
	return omc.SetOrganizationID(o.ID)
}

// SetUser sets the "user" edge to the User entity.
func (omc *OrgMemberCreate) SetUser(u *User) *OrgMemberCreate {
	return omc.SetUserID(u.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (omc *OrgMemberCreate) SetRole(r *Role) *OrgMemberCreate {
	return omc.SetRoleID(r.ID)
}

// Mutation returns the OrgMemberMutation object of the builder.
func (omc *OrgMemberCreate) Mutation() *OrgMemberMutation {
	return omc.mutation
}

// Save creates the OrgMember in the database.
func (omc *OrgMemberCreate) Save(ctx context.Context) (*OrgMember, error) {
	omc.defaults()
	return withHooks(ctx, omc.sqlSave, omc.mutation, omc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (omc *OrgMemberCreate) SaveX(ctx context.Context) *OrgMember {
	v, err := omc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (omc *OrgMemberCreate) Exec(ctx context.Context) error {
	_, err := omc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omc *OrgMemberCreate) ExecX(ctx context.Context) {
	if err := omc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (omc *OrgMemberCreate) defaults() {
	if _, ok := omc.mutation.CreatedAt(); !ok {
		v := orgmember.DefaultCreatedAt()
		omc.mutation.SetCreatedAt(v)
	}
	if _, ok := omc.mutation.UpdatedAt(); !ok {
		v := orgmember.DefaultUpdatedAt()
		omc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omc *OrgMemberCreate) check() error {
	if _, ok := omc.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "OrgMember.organization_id"`)}
	}
	if v, ok := omc.mutation.OrganizationID(); ok {
		if err := orgmember.OrganizationIDValidator(v); err != nil {
			return &ValidationError{Name: "organization_id", err: fmt.Errorf(`ent: validator failed for field "OrgMember.organization_id": %w`, err)}
		}
	}
	if _, ok := omc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrgMember.user_id"`)}
	}
	if v, ok := omc.mutation.UserID(); ok {
		if err := orgmember.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OrgMember.user_id": %w`, err)}
		}
	}
	if _, ok := omc.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "OrgMember.role_id"`)}
	}
	if v, ok := omc.mutation.RoleID(); ok {
		if err := orgmember.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "OrgMember.role_id": %w`, err)}
		}
	}
	if _, ok := omc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrgMember.created_at"`)}
	}
	if _, ok := omc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrgMember.updated_at"`)}
	}
	if len(omc.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrgMember.organization"`)}
	}
	if len(omc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OrgMember.user"`)}
	}
	if len(omc.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "OrgMember.role"`)}
	}
	return nil
}

func (omc *OrgMemberCreate) sqlSave(ctx context.Context) (*OrgMember, error) {
	if err := omc.check(); err != nil {
		return nil, err
	}
	_node, _spec := omc.createSpec()
	if err := sqlgraph.CreateNode(ctx, omc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OrgMember.ID type: %T", _spec.ID.Value)
		}
	}
	omc.mutation.id = &_node.ID
	omc.mutation.done = true
	return _node, nil
}

func (omc *OrgMemberCreate) createSpec() (*OrgMember, *sqlgraph.CreateSpec) {
	var (
		_node = &OrgMember{config: omc.config}
		_spec = sqlgraph.NewCreateSpec(orgmember.Table, sqlgraph.NewFieldSpec(orgmember.FieldID, field.TypeString))
	)
	if id, ok := omc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := omc.mutation.AssignedByUserID(); ok {
		_spec.SetField(orgmember.FieldAssignedByUserID, field.TypeString, value)
		_node.AssignedByUserID = &value
	}
	if value, ok := omc.mutation.UpdatedByUserID(); ok {
		_spec.SetField(orgmember.FieldUpdatedByUserID, field.TypeString, value)
		_node.UpdatedByUserID = &value
	}
	if value, ok := omc.mutation.CreatedAt(); ok {
		_spec.SetField(orgmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := omc.mutation.UpdatedAt(); ok {
		_spec.SetField(orgmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := omc.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgmember.OrganizationTable,
			Columns: []string{orgmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := omc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgmember.UserTable,
			Columns: []string{orgmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := omc.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgmember.RoleTable,
			Columns: []string{orgmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrgMemberCreateBulk is the builder for creating many OrgMember entities in bulk.
type OrgMemberCreateBulk struct {
	config
	err      error
	builders []*OrgMemberCreate
}

// Save creates the OrgMember entities in the database.
func (omcb *OrgMemberCreateBulk) Save(ctx context.Context) ([]*OrgMember, error) {
	if omcb.err != nil {
		return nil, omcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(omcb.builders))
	nodes := make([]*OrgMember, len(omcb.builders))
	mutators := make([]Mutator, len(omcb.builders))
	for i := range omcb.builders {
		func(i int, root context.Context) {
			builder := omcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, omcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, omcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, omcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (omcb *OrgMemberCreateBulk) SaveX(ctx context.Context) []*OrgMember {
	v, err := omcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (omcb *OrgMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := omcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omcb *OrgMemberCreateBulk) ExecX(ctx context.Context) {
	if err := omcb.Exec(ctx); err != nil {
		panic(err)
	}
}
