// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/recoverycontact"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/user"
)

// RecoveryContactCreate is the builder for creating a RecoveryContact entity.
type RecoveryContactCreate struct {
	config
	mutation *RecoveryContactMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (rcc *RecoveryContactCreate) SetUserID(s string) *RecoveryContactCreate {
	rcc.mutation.SetUserID(s)
	return rcc
}

// SetGuardianEmail sets the "guardian_email" field.
func (rcc *RecoveryContactCreate) SetGuardianEmail(s string) *RecoveryContactCreate {
	rcc.mutation.SetGuardianEmail(s)
	return rcc
}

// SetGuardianName sets the "guardian_name" field.
func (rcc *RecoveryContactCreate) SetGuardianName(s string) *RecoveryContactCreate {
	rcc.mutation.SetGuardianName(s)
	return rcc
}

// SetShareIndex sets the "share_index" field.
func (rcc *RecoveryContactCreate) SetShareIndex(i int) *RecoveryContactCreate {
	rcc.mutation.SetShareIndex(i)
	return rcc
}

// SetShareHash sets the "share_hash" field.
func (rcc *RecoveryContactCreate) SetShareHash(s string) *RecoveryContactCreate {
	rcc.mutation.SetShareHash(s)
	return rcc
}

// SetStatus sets the "status" field.
func (rcc *RecoveryContactCreate) SetStatus(r recoverycontact.Status) *RecoveryContactCreate {
	rcc.mutation.SetStatus(r)
	return rcc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rcc *RecoveryContactCreate) SetNillableStatus(r *recoverycontact.Status) *RecoveryContactCreate {
	if r != nil {
		rcc.SetStatus(*r)
	}
	return rcc
}

// SetInvitationTokenHash sets the "invitation_token_hash" field.
func (rcc *RecoveryContactCreate) SetInvitationTokenHash(s string) *RecoveryContactCreate {
	rcc.mutation.SetInvitationTokenHash(s)
	return rcc
}

// SetNillableInvitationTokenHash sets the "invitation_token_hash" field if the given value is not nil.
func (rcc *RecoveryContactCreate) SetNillableInvitationTokenHash(s *string) *RecoveryContactCreate {
	if s != nil {
		rcc.SetInvitationTokenHash(*s)
	}
	return rcc
}

// SetInvitationExpiresAt sets the "invitation_expires_at" field.
func (rcc *RecoveryContactCreate) SetInvitationExpiresAt(t time.Time) *RecoveryContactCreate {
	rcc.mutation.SetInvitationExpiresAt(t)
	return rcc
}

// SetNillableInvitationExpiresAt sets the "invitation_expires_at" field if the given value is not nil.
func (rcc *RecoveryContactCreate) SetNillableInvitationExpiresAt(t *time.Time) *RecoveryContactCreate {
	if t != nil {
		rcc.SetInvitationExpiresAt(*t)
	}
	return rcc
}

// SetCreatedAt sets the "created_at" field.
func (rcc *RecoveryContactCreate) SetCreatedAt(t time.Time) *RecoveryContactCreate {
	rcc.mutation.SetCreatedAt(t)
	return rcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rcc *RecoveryContactCreate) SetNillableCreatedAt(t *time.Time) *RecoveryContactCreate {
	if t != nil {
		rcc.SetCreatedAt(*t)
	}
	return rcc
}

// SetUpdatedAt sets the "updated_at" field.
func (rcc *RecoveryContactCreate) SetUpdatedAt(t time.Time) *RecoveryContactCreate {
	rcc.mutation.SetUpdatedAt(t)
	return rcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rcc *RecoveryContactCreate) SetNillableUpdatedAt(t *time.Time) *RecoveryContactCreate {
	if t != nil {
		rcc.SetUpdatedAt(*t)
	}
	return rcc
}

// SetID sets the "id" field.
func (rcc *RecoveryContactCreate) SetID(s string) *RecoveryContactCreate {
	rcc.mutation.SetID(s)
	return rcc
}

// SetUser sets the "user" edge to the User entity.
func (rcc *RecoveryContactCreate) SetUser(u *User) *RecoveryContactCreate {
	return rcc.SetUserID(u.ID)
}

// Mutation returns the RecoveryContactMutation object of the builder.
func (rcc *RecoveryContactCreate) Mutation() *RecoveryContactMutation {
	return rcc.mutation
}

// Save creates the RecoveryContact in the database.
func (rcc *RecoveryContactCreate) Save(ctx context.Context) (*RecoveryContact, error) {
	rcc.defaults()
	return withHooks(ctx, rcc.sqlSave, rcc.mutation, rcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rcc *RecoveryContactCreate) SaveX(ctx context.Context) *RecoveryContact {
	v, err := rcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcc *RecoveryContactCreate) Exec(ctx context.Context) error {
	_, err := rcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcc *RecoveryContactCreate) ExecX(ctx context.Context) {
	if err := rcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rcc *RecoveryContactCreate) defaults() {
	if _, ok := rcc.mutation.Status(); !ok {
		v := recoverycontact.DefaultStatus
		rcc.mutation.SetStatus(v)
	}
	if _, ok := rcc.mutation.CreatedAt(); !ok {
		v := recoverycontact.DefaultCreatedAt()
		rcc.mutation.SetCreatedAt(v)
	}
	if _, ok := rcc.mutation.UpdatedAt(); !ok {
		v := recoverycontact.DefaultUpdatedAt()
		rcc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rcc *RecoveryContactCreate) check() error {
	if _, ok := rcc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RecoveryContact.user_id"`)}
	}
	if v, ok := rcc.mutation.UserID(); ok {
		if err := recoverycontact.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RecoveryContact.user_id": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.GuardianEmail(); !ok {
		return &ValidationError{Name: "guardian_email", err: errors.New(`ent: missing required field "RecoveryContact.guardian_email"`)}
	}
	if v, ok := rcc.mutation.GuardianEmail(); ok {
		if err := recoverycontact.GuardianEmailValidator(v); err != nil {
			return &ValidationError{Name: "guardian_email", err: fmt.Errorf(`ent: validator failed for field "RecoveryContact.guardian_email": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.GuardianName(); !ok {
		return &ValidationError{Name: "guardian_name", err: errors.New(`ent: missing required field "RecoveryContact.guardian_name"`)}
	}
	if v, ok := rcc.mutation.GuardianName(); ok {
		if err := recoverycontact.GuardianNameValidator(v); err != nil {
			return &ValidationError{Name: "guardian_name", err: fmt.Errorf(`ent: validator failed for field "RecoveryContact.guardian_name": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.ShareIndex(); !ok {
		return &ValidationError{Name: "share_index", err: errors.New(`ent: missing required field "RecoveryContact.share_index"`)}
	}
	if _, ok := rcc.mutation.ShareHash(); !ok {
		return &ValidationError{Name: "share_hash", err: errors.New(`ent: missing required field "RecoveryContact.share_hash"`)}
	}
	if v, ok := rcc.mutation.ShareHash(); ok {
		if err := recoverycontact.ShareHashValidator(v); err != nil {
			return &ValidationError{Name: "share_hash", err: fmt.Errorf(`ent: validator failed for field "RecoveryContact.share_hash": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RecoveryContact.status"`)}
	}
	if v, ok := rcc.mutation.Status(); ok {
		if err := recoverycontact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecoveryContact.status": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecoveryContact.created_at"`)}
	}
	if _, ok := rcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RecoveryContact.updated_at"`)}
	}
	if len(rcc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RecoveryContact.user"`)}
	}
	return nil
}

func (rcc *RecoveryContactCreate) sqlSave(ctx context.Context) (*RecoveryContact, error) {
	if err := rcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RecoveryContact.ID type: %T", _spec.ID.Value)
		}
	}
	rcc.mutation.id = &_node.ID
	rcc.mutation.done = true
	return _node, nil
}

func (rcc *RecoveryContactCreate) createSpec() (*RecoveryContact, *sqlgraph.CreateSpec) {
	var (
		_node = &RecoveryContact{config: rcc.config}
		_spec = sqlgraph.NewCreateSpec(recoverycontact.Table, sqlgraph.NewFieldSpec(recoverycontact.FieldID, field.TypeString))
	)
	if id, ok := rcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rcc.mutation.GuardianEmail(); ok {
		_spec.SetField(recoverycontact.FieldGuardianEmail, field.TypeString, value)
		_node.GuardianEmail = value
	}
	if value, ok := rcc.mutation.GuardianName(); ok {
		_spec.SetField(recoverycontact.FieldGuardianName, field.TypeString, value)
		_node.GuardianName = value
	}
	if value, ok := rcc.mutation.ShareIndex(); ok {
		_spec.SetField(recoverycontact.FieldShareIndex, field.TypeInt, value)
		_node.ShareIndex = value
	}
	if value, ok := rcc.mutation.ShareHash(); ok {
		_spec.SetField(recoverycontact.FieldShareHash, field.TypeString, value)
		_node.ShareHash = value
	}
	if value, ok := rcc.mutation.Status(); ok {
		_spec.SetField(recoverycontact.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rcc.mutation.InvitationTokenHash(); ok {
		_spec.SetField(recoverycontact.FieldInvitationTokenHash, field.TypeString, value)
		_node.InvitationTokenHash = &value
	}
	if value, ok := rcc.mutation.InvitationExpiresAt(); ok {
		_spec.SetField(recoverycontact.FieldInvitationExpiresAt, field.TypeTime, value)
		_node.InvitationExpiresAt = &value
	}
	if value, ok := rcc.mutation.CreatedAt(); ok {
		_spec.SetField(recoverycontact.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rcc.mutation.UpdatedAt(); ok {
		_spec.SetField(recoverycontact.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := rcc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recoverycontact.UserTable,
			Columns: []string{recoverycontact.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecoveryContactCreateBulk is the builder for creating many RecoveryContact entities in bulk.
type RecoveryContactCreateBulk struct {
	config
	err      error
	builders []*RecoveryContactCreate
}

// Save creates the RecoveryContact entities in the database.
func (rccb *RecoveryContactCreateBulk) Save(ctx context.Context) ([]*RecoveryContact, error) {
	if rccb.err != nil {
		return nil, rccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rccb.builders))
	nodes := make([]*RecoveryContact, len(rccb.builders))
	mutators := make([]Mutator, len(rccb.builders))
	for i := range rccb.builders {
		func(i int, root context.Context) {
			builder := rccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecoveryContactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rccb *RecoveryContactCreateBulk) SaveX(ctx context.Context) []*RecoveryContact {
	v, err := rccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rccb *RecoveryContactCreateBulk) Exec(ctx context.Context) error {
	_, err := rccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rccb *RecoveryContactCreateBulk) ExecX(ctx context.Context) {
	if err := rccb.Exec(ctx); err != nil {
		panic(err)
	}
}
