// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/recoveryrequest"
)

// RecoveryRequestDelete is the builder for deleting a RecoveryRequest entity.
type RecoveryRequestDelete struct {
	config
	hooks    []Hook
	mutation *RecoveryRequestMutation
}

// Where appends a list predicates to the RecoveryRequestDelete builder.
func (rrd *RecoveryRequestDelete) Where(ps ...predicate.RecoveryRequest) *RecoveryRequestDelete {
	rrd.mutation.Where(ps...)
	return rrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rrd *RecoveryRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rrd.sqlExec, rrd.mutation, rrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rrd *RecoveryRequestDelete) ExecX(ctx context.Context) int {
	n, err := rrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rrd *RecoveryRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recoveryrequest.Table, sqlgraph.NewFieldSpec(recoveryrequest.FieldID, field.TypeString))
	if ps := rrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rrd.mutation.done = true
	return affected, err
}

// RecoveryRequestDeleteOne is the builder for deleting a single RecoveryRequest entity.
type RecoveryRequestDeleteOne struct {
	rrd *RecoveryRequestDelete
}

// Where appends a list predicates to the RecoveryRequestDelete builder.
func (rrdo *RecoveryRequestDeleteOne) Where(ps ...predicate.RecoveryRequest) *RecoveryRequestDeleteOne {
	rrdo.rrd.mutation.Where(ps...)
	return rrdo
}

// Exec executes the deletion query.
func (rrdo *RecoveryRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := rrdo.rrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recoveryrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rrdo *RecoveryRequestDeleteOne) ExecX(ctx context.Context) {
	if err := rrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
