// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/recoveryrequest"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/user"
)

// RecoveryRequestCreate is the builder for creating a RecoveryRequest entity.
type RecoveryRequestCreate struct {
	config
	mutation *RecoveryRequestMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (rrc *RecoveryRequestCreate) SetUserID(s string) *RecoveryRequestCreate {
	rrc.mutation.SetUserID(s)
	return rrc
}

// SetInitiatedFromIP sets the "initiated_from_ip" field.
func (rrc *RecoveryRequestCreate) SetInitiatedFromIP(s string) *RecoveryRequestCreate {
	rrc.mutation.SetInitiatedFromIP(s)
	return rrc
}

// SetInitiatedFromSubnet sets the "initiated_from_subnet" field.
func (rrc *RecoveryRequestCreate) SetInitiatedFromSubnet(s string) *RecoveryRequestCreate {
	rrc.mutation.SetInitiatedFromSubnet(s)
	return rrc
}

// SetInitiatedFromUserAgent sets the "initiated_from_user_agent" field.
func (rrc *RecoveryRequestCreate) SetInitiatedFromUserAgent(s string) *RecoveryRequestCreate {
	rrc.mutation.SetInitiatedFromUserAgent(s)
	return rrc
}

// SetIsTrustedDeviceOrigin sets the "is_trusted_device_origin" field.
func (rrc *RecoveryRequestCreate) SetIsTrustedDeviceOrigin(b bool) *RecoveryRequestCreate {
	rrc.mutation.SetIsTrustedDeviceOrigin(b)
	return rrc
}

// SetNillableIsTrustedDeviceOrigin sets the "is_trusted_device_origin" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableIsTrustedDeviceOrigin(b *bool) *RecoveryRequestCreate {
	if b != nil {
		rrc.SetIsTrustedDeviceOrigin(*b)
	}
	return rrc
}

// SetProofMethodUsed sets the "proof_method_used" field.
func (rrc *RecoveryRequestCreate) SetProofMethodUsed(rmu recoveryrequest.ProofMethodUsed) *RecoveryRequestCreate {
	rrc.mutation.SetProofMethodUsed(rmu)
	return rrc
}

// SetNillableProofMethodUsed sets the "proof_method_used" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableProofMethodUsed(rmu *recoveryrequest.ProofMethodUsed) *RecoveryRequestCreate {
	if rmu != nil {
		rrc.SetProofMethodUsed(*rmu)
	}
	return rrc
}

// SetStatus sets the "status" field.
func (rrc *RecoveryRequestCreate) SetStatus(r recoveryrequest.Status) *RecoveryRequestCreate {
	rrc.mutation.SetStatus(r)
	return rrc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableStatus(r *recoveryrequest.Status) *RecoveryRequestCreate {
	if r != nil {
		rrc.SetStatus(*r)
	}
	return rrc
}

// SetSubmittedSharesCount sets the "submitted_shares_count" field.
func (rrc *RecoveryRequestCreate) SetSubmittedSharesCount(i int) *RecoveryRequestCreate {
	rrc.mutation.SetSubmittedSharesCount(i)
	return rrc
}

// SetNillableSubmittedSharesCount sets the "submitted_shares_count" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableSubmittedSharesCount(i *int) *RecoveryRequestCreate {
	if i != nil {
		rrc.SetSubmittedSharesCount(*i)
	}
	return rrc
}

// SetSubmittedShareIndexes sets the "submitted_share_indexes" field.
func (rrc *RecoveryRequestCreate) SetSubmittedShareIndexes(i []int) *RecoveryRequestCreate {
	rrc.mutation.SetSubmittedShareIndexes(i)
	return rrc
}

// SetFreezeStartedAt sets the "freeze_started_at" field.
func (rrc *RecoveryRequestCreate) SetFreezeStartedAt(t time.Time) *RecoveryRequestCreate {
	rrc.mutation.SetFreezeStartedAt(t)
	return rrc
}

// SetNillableFreezeStartedAt sets the "freeze_started_at" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableFreezeStartedAt(t *time.Time) *RecoveryRequestCreate {
	if t != nil {
		rrc.SetFreezeStartedAt(*t)
	}
	return rrc
}

// SetFreezeExpiresAt sets the "freeze_expires_at" field.
func (rrc *RecoveryRequestCreate) SetFreezeExpiresAt(t time.Time) *RecoveryRequestCreate {
	rrc.mutation.SetFreezeExpiresAt(t)
	return rrc
}

// SetNillableFreezeExpiresAt sets the "freeze_expires_at" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableFreezeExpiresAt(t *time.Time) *RecoveryRequestCreate {
	if t != nil {
		rrc.SetFreezeExpiresAt(*t)
	}
	return rrc
}

// SetCancellationTokenHash sets the "cancellation_token_hash" field.
func (rrc *RecoveryRequestCreate) SetCancellationTokenHash(s string) *RecoveryRequestCreate {
	rrc.mutation.SetCancellationTokenHash(s)
	return rrc
}

// SetClaimTokenHash sets the "claim_token_hash" field.
func (rrc *RecoveryRequestCreate) SetClaimTokenHash(s string) *RecoveryRequestCreate {
	rrc.mutation.SetClaimTokenHash(s)
	return rrc
}

// SetNillableClaimTokenHash sets the "claim_token_hash" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableClaimTokenHash(s *string) *RecoveryRequestCreate {
	if s != nil {
		rrc.SetClaimTokenHash(*s)
	}
	return rrc
}

// SetClaimTokenExpiresAt sets the "claim_token_expires_at" field.
func (rrc *RecoveryRequestCreate) SetClaimTokenExpiresAt(t time.Time) *RecoveryRequestCreate {
	rrc.mutation.SetClaimTokenExpiresAt(t)
	return rrc
}

// SetNillableClaimTokenExpiresAt sets the "claim_token_expires_at" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableClaimTokenExpiresAt(t *time.Time) *RecoveryRequestCreate {
	if t != nil {
		rrc.SetClaimTokenExpiresAt(*t)
	}
	return rrc
}

// SetCompletedAt sets the "completed_at" field.
func (rrc *RecoveryRequestCreate) SetCompletedAt(t time.Time) *RecoveryRequestCreate {
	rrc.mutation.SetCompletedAt(t)
	return rrc
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableCompletedAt(t *time.Time) *RecoveryRequestCreate {
	if t != nil {
		rrc.SetCompletedAt(*t)
	}
	return rrc
}

// SetCancelledAt sets the "cancelled_at" field.
func (rrc *RecoveryRequestCreate) SetCancelledAt(t time.Time) *RecoveryRequestCreate {
	rrc.mutation.SetCancelledAt(t)
	return rrc
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableCancelledAt(t *time.Time) *RecoveryRequestCreate {
	if t != nil {
		rrc.SetCancelledAt(*t)
	}
	return rrc
}

// SetCreatedAt sets the "created_at" field.
func (rrc *RecoveryRequestCreate) SetCreatedAt(t time.Time) *RecoveryRequestCreate {
	rrc.mutation.SetCreatedAt(t)
	return rrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableCreatedAt(t *time.Time) *RecoveryRequestCreate {
	if t != nil {
		rrc.SetCreatedAt(*t)
	}
	return rrc
}

// SetUpdatedAt sets the "updated_at" field.
func (rrc *RecoveryRequestCreate) SetUpdatedAt(t time.Time) *RecoveryRequestCreate {
	rrc.mutation.SetUpdatedAt(t)
	return rrc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rrc *RecoveryRequestCreate) SetNillableUpdatedAt(t *time.Time) *RecoveryRequestCreate {
	if t != nil {
		rrc.SetUpdatedAt(*t)
	}
	return rrc
}

// SetID sets the "id" field.
func (rrc *RecoveryRequestCreate) SetID(s string) *RecoveryRequestCreate {
	rrc.mutation.SetID(s)
	return rrc
}

// SetUser sets the "user" edge to the User entity.
func (rrc *RecoveryRequestCreate) SetUser(u *User) *RecoveryRequestCreate {
	return rrc.SetUserID(u.ID)
}

// Mutation returns the RecoveryRequestMutation object of the builder.
func (rrc *RecoveryRequestCreate) Mutation() *RecoveryRequestMutation {
	return rrc.mutation
}

// Save creates the RecoveryRequest in the database.
func (rrc *RecoveryRequestCreate) Save(ctx context.Context) (*RecoveryRequest, error) {
	rrc.defaults()
	return withHooks(ctx, rrc.sqlSave, rrc.mutation, rrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rrc *RecoveryRequestCreate) SaveX(ctx context.Context) *RecoveryRequest {
	v, err := rrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rrc *RecoveryRequestCreate) Exec(ctx context.Context) error {
	_, err := rrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rrc *RecoveryRequestCreate) ExecX(ctx context.Context) {
	if err := rrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rrc *RecoveryRequestCreate) defaults() {
	if _, ok := rrc.mutation.IsTrustedDeviceOrigin(); !ok {
		v := recoveryrequest.DefaultIsTrustedDeviceOrigin
		rrc.mutation.SetIsTrustedDeviceOrigin(v)
	}
	if _, ok := rrc.mutation.Status(); !ok {
		v := recoveryrequest.DefaultStatus
		rrc.mutation.SetStatus(v)
	}
	if _, ok := rrc.mutation.SubmittedSharesCount(); !ok {
		v := recoveryrequest.DefaultSubmittedSharesCount
		rrc.mutation.SetSubmittedSharesCount(v)
	}
	if _, ok := rrc.mutation.CreatedAt(); !ok {
		v := recoveryrequest.DefaultCreatedAt()
		rrc.mutation.SetCreatedAt(v)
	}
	if _, ok := rrc.mutation.UpdatedAt(); !ok {
		v := recoveryrequest.DefaultUpdatedAt()
		rrc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rrc *RecoveryRequestCreate) check() error {
	if _, ok := rrc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RecoveryRequest.user_id"`)}
	}
	if v, ok := rrc.mutation.UserID(); ok {
		if err := recoveryrequest.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RecoveryRequest.user_id": %w`, err)}
		}
	}
	if _, ok := rrc.mutation.InitiatedFromIP(); !ok {
		return &ValidationError{Name: "initiated_from_ip", err: errors.New(`ent: missing required field "RecoveryRequest.initiated_from_ip"`)}
	}
	if v, ok := rrc.mutation.InitiatedFromIP(); ok {
		if err := recoveryrequest.InitiatedFromIPValidator(v); err != nil {
			return &ValidationError{Name: "initiated_from_ip", err: fmt.Errorf(`ent: validator failed for field "RecoveryRequest.initiated_from_ip": %w`, err)}
		}
	}
	if _, ok := rrc.mutation.InitiatedFromSubnet(); !ok {
		return &ValidationError{Name: "initiated_from_subnet", err: errors.New(`ent: missing required field "RecoveryRequest.initiated_from_subnet"`)}
	}
	if v, ok := rrc.mutation.InitiatedFromSubnet(); ok {
		if err := recoveryrequest.InitiatedFromSubnetValidator(v); err != nil {
			return &ValidationError{Name: "initiated_from_subnet", err: fmt.Errorf(`ent: validator failed for field "RecoveryRequest.initiated_from_subnet": %w`, err)}
		}
	}
	if _, ok := rrc.mutation.InitiatedFromUserAgent(); !ok {
		return &ValidationError{Name: "initiated_from_user_agent", err: errors.New(`ent: missing required field "RecoveryRequest.initiated_from_user_agent"`)}
	}
	if v, ok := rrc.mutation.InitiatedFromUserAgent(); ok {
		if err := recoveryrequest.InitiatedFromUserAgentValidator(v); err != nil {
			return &ValidationError{Name: "initiated_from_user_agent", err: fmt.Errorf(`ent: validator failed for field "RecoveryRequest.initiated_from_user_agent": %w`, err)}
		}
	}
	if _, ok := rrc.mutation.IsTrustedDeviceOrigin(); !ok {
		return &ValidationError{Name: "is_trusted_device_origin", err: errors.New(`ent: missing required field "RecoveryRequest.is_trusted_device_origin"`)}
	}
	if v, ok := rrc.mutation.ProofMethodUsed(); ok {
		if err := recoveryrequest.ProofMethodUsedValidator(v); err != nil {
			return &ValidationError{Name: "proof_method_used", err: fmt.Errorf(`ent: validator failed for field "RecoveryRequest.proof_method_used": %w`, err)}
		}
	}
	if _, ok := rrc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RecoveryRequest.status"`)}
	}
	if v, ok := rrc.mutation.Status(); ok {
		if err := recoveryrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecoveryRequest.status": %w`, err)}
		}
	}
	if _, ok := rrc.mutation.SubmittedSharesCount(); !ok {
		return &ValidationError{Name: "submitted_shares_count", err: errors.New(`ent: missing required field "RecoveryRequest.submitted_shares_count"`)}
	}
	if _, ok := rrc.mutation.CancellationTokenHash(); !ok {
		return &ValidationError{Name: "cancellation_token_hash", err: errors.New(`ent: missing required field "RecoveryRequest.cancellation_token_hash"`)}
	}
	if v, ok := rrc.mutation.CancellationTokenHash(); ok {
		if err := recoveryrequest.CancellationTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "cancellation_token_hash", err: fmt.Errorf(`ent: validator failed for field "RecoveryRequest.cancellation_token_hash": %w`, err)}
		}
	}
	if _, ok := rrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecoveryRequest.created_at"`)}
	}
	if _, ok := rrc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RecoveryRequest.updated_at"`)}
	}
	if len(rrc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RecoveryRequest.user"`)}
	}
	return nil
}

func (rrc *RecoveryRequestCreate) sqlSave(ctx context.Context) (*RecoveryRequest, error) {
	if err := rrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RecoveryRequest.ID type: %T", _spec.ID.Value)
		}
	}
	rrc.mutation.id = &_node.ID
	rrc.mutation.done = true
	return _node, nil
}

func (rrc *RecoveryRequestCreate) createSpec() (*RecoveryRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &RecoveryRequest{config: rrc.config}
		_spec = sqlgraph.NewCreateSpec(recoveryrequest.Table, sqlgraph.NewFieldSpec(recoveryrequest.FieldID, field.TypeString))
	)
	if id, ok := rrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rrc.mutation.InitiatedFromIP(); ok {
		_spec.SetField(recoveryrequest.FieldInitiatedFromIP, field.TypeString, value)
		_node.InitiatedFromIP = value
	}
	if value, ok := rrc.mutation.InitiatedFromSubnet(); ok {
		_spec.SetField(recoveryrequest.FieldInitiatedFromSubnet, field.TypeString, value)
		_node.InitiatedFromSubnet = value
	}
	if value, ok := rrc.mutation.InitiatedFromUserAgent(); ok {
		_spec.SetField(recoveryrequest.FieldInitiatedFromUserAgent, field.TypeString, value)
		_node.InitiatedFromUserAgent = value
	}
	if value, ok := rrc.mutation.IsTrustedDeviceOrigin(); ok {
		_spec.SetField(recoveryrequest.FieldIsTrustedDeviceOrigin, field.TypeBool, value)
		_node.IsTrustedDeviceOrigin = value
	}
	if value, ok := rrc.mutation.ProofMethodUsed(); ok {
		_spec.SetField(recoveryrequest.FieldProofMethodUsed, field.TypeEnum, value)
		_node.ProofMethodUsed = &value
	}
	if value, ok := rrc.mutation.Status(); ok {
		_spec.SetField(recoveryrequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rrc.mutation.SubmittedSharesCount(); ok {
		_spec.SetField(recoveryrequest.FieldSubmittedSharesCount, field.TypeInt, value)
		_node.SubmittedSharesCount = value
	}
	if value, ok := rrc.mutation.SubmittedShareIndexes(); ok {
		_spec.SetField(recoveryrequest.FieldSubmittedShareIndexes, field.TypeJSON, value)
		_node.SubmittedShareIndexes = value
	}
	if value, ok := rrc.mutation.FreezeStartedAt(); ok {
		_spec.SetField(recoveryrequest.FieldFreezeStartedAt, field.TypeTime, value)
		_node.FreezeStartedAt = &value
	}
	if value, ok := rrc.mutation.FreezeExpiresAt(); ok {
		_spec.SetField(recoveryrequest.FieldFreezeExpiresAt, field.TypeTime, value)
		_node.FreezeExpiresAt = &value
	}
	if value, ok := rrc.mutation.CancellationTokenHash(); ok {
		_spec.SetField(recoveryrequest.FieldCancellationTokenHash, field.TypeString, value)
		_node.CancellationTokenHash = value
	}
	if value, ok := rrc.mutation.ClaimTokenHash(); ok {
		_spec.SetField(recoveryrequest.FieldClaimTokenHash, field.TypeString, value)
		_node.ClaimTokenHash = &value
	}
	if value, ok := rrc.mutation.ClaimTokenExpiresAt(); ok {
		_spec.SetField(recoveryrequest.FieldClaimTokenExpiresAt, field.TypeTime, value)
		_node.ClaimTokenExpiresAt = &value
	}
	if value, ok := rrc.mutation.CompletedAt(); ok {
		_spec.SetField(recoveryrequest.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := rrc.mutation.CancelledAt(); ok {
		_spec.SetField(recoveryrequest.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := rrc.mutation.CreatedAt(); ok {
		_spec.SetField(recoveryrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rrc.mutation.UpdatedAt(); ok {
		_spec.SetField(recoveryrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := rrc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recoveryrequest.UserTable,
			Columns: []string{recoveryrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecoveryRequestCreateBulk is the builder for creating many RecoveryRequest entities in bulk.
type RecoveryRequestCreateBulk struct {
	config
	err      error
	builders []*RecoveryRequestCreate
}

// Save creates the RecoveryRequest entities in the database.
func (rrcb *RecoveryRequestCreateBulk) Save(ctx context.Context) ([]*RecoveryRequest, error) {
	if rrcb.err != nil {
		return nil, rrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rrcb.builders))
	nodes := make([]*RecoveryRequest, len(rrcb.builders))
	mutators := make([]Mutator, len(rrcb.builders))
	for i := range rrcb.builders {
		func(i int, root context.Context) {
			builder := rrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecoveryRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rrcb *RecoveryRequestCreateBulk) SaveX(ctx context.Context) []*RecoveryRequest {
	v, err := rrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rrcb *RecoveryRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := rrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rrcb *RecoveryRequestCreateBulk) ExecX(ctx context.Context) {
	if err := rrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
