// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/apikey"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/application"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/auditlog"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/identity"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/managedtenant"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/organization"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/orginvitation"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/orgmember"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/permission"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/pushdevice"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/recoverycontact"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/recoveryrequest"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/role"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/samlconnection"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/sandboxmessage"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/schema"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/securityblacklist"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/session"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/sessionappactivity"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/socialauthstate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/tenant"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/tenantenvironment"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/trusteddevice"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/twofactormethod"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/user"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/useripsubnethistory"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/userpasswordhistory"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/userrole"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/webhookendpoint"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/webhookevent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescApplicationID is the schema descriptor for application_id field.
	apikeyDescApplicationID := apikeyFields[1].Descriptor()
	// apikey.ApplicationIDValidator is a validator for the "application_id" field. It is called by the builders before save.
	apikey.ApplicationIDValidator = apikeyDescApplicationID.Validators[0].(func(string) error)
	// apikeyDescKeyPrefix is the schema descriptor for key_prefix field.
	apikeyDescKeyPrefix := apikeyFields[3].Descriptor()
	// apikey.KeyPrefixValidator is a validator for the "key_prefix" field. It is called by the builders before save.
	apikey.KeyPrefixValidator = apikeyDescKeyPrefix.Validators[0].(func(string) error)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[4].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[10].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	applicationFields := schema.Application{}.Fields()
	_ = applicationFields
	// applicationDescTenantID is the schema descriptor for tenant_id field.
	applicationDescTenantID := applicationFields[1].Descriptor()
	// application.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	application.TenantIDValidator = applicationDescTenantID.Validators[0].(func(string) error)
	// applicationDescName is the schema descriptor for name field.
	applicationDescName := applicationFields[2].Descriptor()
	// application.NameValidator is a validator for the "name" field. It is called by the builders before save.
	application.NameValidator = applicationDescName.Validators[0].(func(string) error)
	// applicationDescCreatedAt is the schema descriptor for created_at field.
	applicationDescCreatedAt := applicationFields[6].Descriptor()
	// application.DefaultCreatedAt holds the default value on creation for the created_at field.
	application.DefaultCreatedAt = applicationDescCreatedAt.Default.(func() time.Time)
	// applicationDescUpdatedAt is the schema descriptor for updated_at field.
	applicationDescUpdatedAt := applicationFields[7].Descriptor()
	// application.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	application.DefaultUpdatedAt = applicationDescUpdatedAt.Default.(func() time.Time)
	// application.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	application.UpdateDefaultUpdatedAt = applicationDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescTenantID is the schema descriptor for tenant_id field.
	auditlogDescTenantID := auditlogFields[1].Descriptor()
	// auditlog.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	auditlog.TenantIDValidator = auditlogDescTenantID.Validators[0].(func(string) error)
	// auditlogDescEventType is the schema descriptor for event_type field.
	auditlogDescEventType := auditlogFields[6].Descriptor()
	// auditlog.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	auditlog.EventTypeValidator = auditlogDescEventType.Validators[0].(func(string) error)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[11].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	identityFields := schema.Identity{}.Fields()
	_ = identityFields
	// identityDescUserID is the schema descriptor for user_id field.
	identityDescUserID := identityFields[1].Descriptor()
	// identity.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	identity.UserIDValidator = identityDescUserID.Validators[0].(func(string) error)
	// identityDescProvider is the schema descriptor for provider field.
	identityDescProvider := identityFields[2].Descriptor()
	// identity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	identity.ProviderValidator = identityDescProvider.Validators[0].(func(string) error)
	// identityDescProviderUserID is the schema descriptor for provider_user_id field.
	identityDescProviderUserID := identityFields[3].Descriptor()
	// identity.ProviderUserIDValidator is a validator for the "provider_user_id" field. It is called by the builders before save.
	identity.ProviderUserIDValidator = identityDescProviderUserID.Validators[0].(func(string) error)
	// identityDescCreatedAt is the schema descriptor for created_at field.
	identityDescCreatedAt := identityFields[9].Descriptor()
	// identity.DefaultCreatedAt holds the default value on creation for the created_at field.
	identity.DefaultCreatedAt = identityDescCreatedAt.Default.(func() time.Time)
	// identityDescUpdatedAt is the schema descriptor for updated_at field.
	identityDescUpdatedAt := identityFields[10].Descriptor()
	// identity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	identity.DefaultUpdatedAt = identityDescUpdatedAt.Default.(func() time.Time)
	// identity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	identity.UpdateDefaultUpdatedAt = identityDescUpdatedAt.UpdateDefault.(func() time.Time)
	managedtenantFields := schema.ManagedTenant{}.Fields()
	_ = managedtenantFields
	// managedtenantDescTenantID is the schema descriptor for tenant_id field.
	managedtenantDescTenantID := managedtenantFields[1].Descriptor()
	// managedtenant.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	managedtenant.TenantIDValidator = managedtenantDescTenantID.Validators[0].(func(string) error)
	// managedtenantDescManagedTenantID is the schema descriptor for managed_tenant_id field.
	managedtenantDescManagedTenantID := managedtenantFields[2].Descriptor()
	// managedtenant.ManagedTenantIDValidator is a validator for the "managed_tenant_id" field. It is called by the builders before save.
	managedtenant.ManagedTenantIDValidator = managedtenantDescManagedTenantID.Validators[0].(func(string) error)
	// managedtenantDescOwnerUserID is the schema descriptor for owner_user_id field.
	managedtenantDescOwnerUserID := managedtenantFields[3].Descriptor()
	// managedtenant.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	managedtenant.OwnerUserIDValidator = managedtenantDescOwnerUserID.Validators[0].(func(string) error)
	// managedtenantDescCreatedAt is the schema descriptor for created_at field.
	managedtenantDescCreatedAt := managedtenantFields[5].Descriptor()
	// managedtenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	managedtenant.DefaultCreatedAt = managedtenantDescCreatedAt.Default.(func() time.Time)
	orginvitationFields := schema.OrgInvitation{}.Fields()
	_ = orginvitationFields
	// orginvitationDescOrganizationID is the schema descriptor for organization_id field.
	orginvitationDescOrganizationID := orginvitationFields[1].Descriptor()
	// orginvitation.OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	orginvitation.OrganizationIDValidator = orginvitationDescOrganizationID.Validators[0].(func(string) error)
	// orginvitationDescEmail is the schema descriptor for email field.
	orginvitationDescEmail := orginvitationFields[2].Descriptor()
	// orginvitation.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	orginvitation.EmailValidator = orginvitationDescEmail.Validators[0].(func(string) error)
	// orginvitationDescRoleID is the schema descriptor for role_id field.
	orginvitationDescRoleID := orginvitationFields[3].Descriptor()
	// orginvitation.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	orginvitation.RoleIDValidator = orginvitationDescRoleID.Validators[0].(func(string) error)
	// orginvitationDescInvitationToken is the schema descriptor for invitation_token field.
	orginvitationDescInvitationToken := orginvitationFields[5].Descriptor()
	// orginvitation.InvitationTokenValidator is a validator for the "invitation_token" field. It is called by the builders before save.
	orginvitation.InvitationTokenValidator = orginvitationDescInvitationToken.Validators[0].(func(string) error)
	// orginvitationDescCreatedAt is the schema descriptor for created_at field.
	orginvitationDescCreatedAt := orginvitationFields[8].Descriptor()
	// orginvitation.DefaultCreatedAt holds the default value on creation for the created_at field.
	orginvitation.DefaultCreatedAt = orginvitationDescCreatedAt.Default.(func() time.Time)
	orgmemberFields := schema.OrgMember{}.Fields()
	_ = orgmemberFields
	// orgmemberDescOrganizationID is the schema descriptor for organization_id field.
	orgmemberDescOrganizationID := orgmemberFields[1].Descriptor()
	// orgmember.OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	orgmember.OrganizationIDValidator = orgmemberDescOrganizationID.Validators[0].(func(string) error)
	// orgmemberDescUserID is the schema descriptor for user_id field.
	orgmemberDescUserID := orgmemberFields[2].Descriptor()
	// orgmember.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	orgmember.UserIDValidator = orgmemberDescUserID.Validators[0].(func(string) error)
	// orgmemberDescRoleID is the schema descriptor for role_id field.
	orgmemberDescRoleID := orgmemberFields[3].Descriptor()
	// orgmember.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	orgmember.RoleIDValidator = orgmemberDescRoleID.Validators[0].(func(string) error)
	// orgmemberDescCreatedAt is the schema descriptor for created_at field.
	orgmemberDescCreatedAt := orgmemberFields[6].Descriptor()
	// orgmember.DefaultCreatedAt holds the default value on creation for the created_at field.
	orgmember.DefaultCreatedAt = orgmemberDescCreatedAt.Default.(func() time.Time)
	// orgmemberDescUpdatedAt is the schema descriptor for updated_at field.
	orgmemberDescUpdatedAt := orgmemberFields[7].Descriptor()
	// orgmember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orgmember.DefaultUpdatedAt = orgmemberDescUpdatedAt.Default.(func() time.Time)
	// orgmember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orgmember.UpdateDefaultUpdatedAt = orgmemberDescUpdatedAt.UpdateDefault.(func() time.Time)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescTenantID is the schema descriptor for tenant_id field.
	organizationDescTenantID := organizationFields[1].Descriptor()
	// organization.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	organization.TenantIDValidator = organizationDescTenantID.Validators[0].(func(string) error)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[3].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[4].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = organizationDescSlug.Validators[0].(func(string) error)
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[7].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescRoleID is the schema descriptor for role_id field.
	permissionDescRoleID := permissionFields[1].Descriptor()
	// permission.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	permission.RoleIDValidator = permissionDescRoleID.Validators[0].(func(string) error)
	// permissionDescAction is the schema descriptor for action field.
	permissionDescAction := permissionFields[2].Descriptor()
	// permission.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	permission.ActionValidator = permissionDescAction.Validators[0].(func(string) error)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[5].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	pushdeviceFields := schema.PushDevice{}.Fields()
	_ = pushdeviceFields
	// pushdeviceDescUserID is the schema descriptor for user_id field.
	pushdeviceDescUserID := pushdeviceFields[1].Descriptor()
	// pushdevice.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	pushdevice.UserIDValidator = pushdeviceDescUserID.Validators[0].(func(string) error)
	// pushdeviceDescDeviceToken is the schema descriptor for device_token field.
	pushdeviceDescDeviceToken := pushdeviceFields[5].Descriptor()
	// pushdevice.DeviceTokenValidator is a validator for the "device_token" field. It is called by the builders before save.
	pushdevice.DeviceTokenValidator = pushdeviceDescDeviceToken.Validators[0].(func(string) error)
	// pushdeviceDescPublicKeyPem is the schema descriptor for public_key_pem field.
	pushdeviceDescPublicKeyPem := pushdeviceFields[6].Descriptor()
	// pushdevice.PublicKeyPemValidator is a validator for the "public_key_pem" field. It is called by the builders before save.
	pushdevice.PublicKeyPemValidator = pushdeviceDescPublicKeyPem.Validators[0].(func(string) error)
	// pushdeviceDescCreatedAt is the schema descriptor for created_at field.
	pushdeviceDescCreatedAt := pushdeviceFields[12].Descriptor()
	// pushdevice.DefaultCreatedAt holds the default value on creation for the created_at field.
	pushdevice.DefaultCreatedAt = pushdeviceDescCreatedAt.Default.(func() time.Time)
	recoverycontactFields := schema.RecoveryContact{}.Fields()
	_ = recoverycontactFields
	// recoverycontactDescUserID is the schema descriptor for user_id field.
	recoverycontactDescUserID := recoverycontactFields[1].Descriptor()
	// recoverycontact.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	recoverycontact.UserIDValidator = recoverycontactDescUserID.Validators[0].(func(string) error)
	// recoverycontactDescGuardianEmail is the schema descriptor for guardian_email field.
	recoverycontactDescGuardianEmail := recoverycontactFields[2].Descriptor()
	// recoverycontact.GuardianEmailValidator is a validator for the "guardian_email" field. It is called by the builders before save.
	recoverycontact.GuardianEmailValidator = recoverycontactDescGuardianEmail.Validators[0].(func(string) error)
	// recoverycontactDescGuardianName is the schema descriptor for guardian_name field.
	recoverycontactDescGuardianName := recoverycontactFields[3].Descriptor()
	// recoverycontact.GuardianNameValidator is a validator for the "guardian_name" field. It is called by the builders before save.
	recoverycontact.GuardianNameValidator = recoverycontactDescGuardianName.Validators[0].(func(string) error)
	// recoverycontactDescShareHash is the schema descriptor for share_hash field.
	recoverycontactDescShareHash := recoverycontactFields[5].Descriptor()
	// recoverycontact.ShareHashValidator is a validator for the "share_hash" field. It is called by the builders before save.
	recoverycontact.ShareHashValidator = recoverycontactDescShareHash.Validators[0].(func(string) error)
	// recoverycontactDescCreatedAt is the schema descriptor for created_at field.
	recoverycontactDescCreatedAt := recoverycontactFields[9].Descriptor()
	// recoverycontact.DefaultCreatedAt holds the default value on creation for the created_at field.
	recoverycontact.DefaultCreatedAt = recoverycontactDescCreatedAt.Default.(func() time.Time)
	// recoverycontactDescUpdatedAt is the schema descriptor for updated_at field.
	recoverycontactDescUpdatedAt := recoverycontactFields[10].Descriptor()
	// recoverycontact.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	recoverycontact.DefaultUpdatedAt = recoverycontactDescUpdatedAt.Default.(func() time.Time)
	// recoverycontact.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	recoverycontact.UpdateDefaultUpdatedAt = recoverycontactDescUpdatedAt.UpdateDefault.(func() time.Time)
	recoveryrequestFields := schema.RecoveryRequest{}.Fields()
	_ = recoveryrequestFields
	// recoveryrequestDescUserID is the schema descriptor for user_id field.
	recoveryrequestDescUserID := recoveryrequestFields[1].Descriptor()
	// recoveryrequest.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	recoveryrequest.UserIDValidator = recoveryrequestDescUserID.Validators[0].(func(string) error)
	// recoveryrequestDescInitiatedFromIP is the schema descriptor for initiated_from_ip field.
	recoveryrequestDescInitiatedFromIP := recoveryrequestFields[2].Descriptor()
	// recoveryrequest.InitiatedFromIPValidator is a validator for the "initiated_from_ip" field. It is called by the builders before save.
	recoveryrequest.InitiatedFromIPValidator = recoveryrequestDescInitiatedFromIP.Validators[0].(func(string) error)
	// recoveryrequestDescInitiatedFromSubnet is the schema descriptor for initiated_from_subnet field.
	recoveryrequestDescInitiatedFromSubnet := recoveryrequestFields[3].Descriptor()
	// recoveryrequest.InitiatedFromSubnetValidator is a validator for the "initiated_from_subnet" field. It is called by the builders before save.
	recoveryrequest.InitiatedFromSubnetValidator = recoveryrequestDescInitiatedFromSubnet.Validators[0].(func(string) error)
	// recoveryrequestDescInitiatedFromUserAgent is the schema descriptor for initiated_from_user_agent field.
	recoveryrequestDescInitiatedFromUserAgent := recoveryrequestFields[4].Descriptor()
	// recoveryrequest.InitiatedFromUserAgentValidator is a validator for the "initiated_from_user_agent" field. It is called by the builders before save.
	recoveryrequest.InitiatedFromUserAgentValidator = recoveryrequestDescInitiatedFromUserAgent.Validators[0].(func(string) error)
	// recoveryrequestDescIsTrustedDeviceOrigin is the schema descriptor for is_trusted_device_origin field.
	recoveryrequestDescIsTrustedDeviceOrigin := recoveryrequestFields[5].Descriptor()
	// recoveryrequest.DefaultIsTrustedDeviceOrigin holds the default value on creation for the is_trusted_device_origin field.
	recoveryrequest.DefaultIsTrustedDeviceOrigin = recoveryrequestDescIsTrustedDeviceOrigin.Default.(bool)
	// recoveryrequestDescSubmittedSharesCount is the schema descriptor for submitted_shares_count field.
	recoveryrequestDescSubmittedSharesCount := recoveryrequestFields[8].Descriptor()
	// recoveryrequest.DefaultSubmittedSharesCount holds the default value on creation for the submitted_shares_count field.
	recoveryrequest.DefaultSubmittedSharesCount = recoveryrequestDescSubmittedSharesCount.Default.(int)
	// recoveryrequestDescCancellationTokenHash is the schema descriptor for cancellation_token_hash field.
	recoveryrequestDescCancellationTokenHash := recoveryrequestFields[12].Descriptor()
	// recoveryrequest.CancellationTokenHashValidator is a validator for the "cancellation_token_hash" field. It is called by the builders before save.
	recoveryrequest.CancellationTokenHashValidator = recoveryrequestDescCancellationTokenHash.Validators[0].(func(string) error)
	// recoveryrequestDescCreatedAt is the schema descriptor for created_at field.
	recoveryrequestDescCreatedAt := recoveryrequestFields[17].Descriptor()
	// recoveryrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	recoveryrequest.DefaultCreatedAt = recoveryrequestDescCreatedAt.Default.(func() time.Time)
	// recoveryrequestDescUpdatedAt is the schema descriptor for updated_at field.
	recoveryrequestDescUpdatedAt := recoveryrequestFields[18].Descriptor()
	// recoveryrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	recoveryrequest.DefaultUpdatedAt = recoveryrequestDescUpdatedAt.Default.(func() time.Time)
	// recoveryrequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	recoveryrequest.UpdateDefaultUpdatedAt = recoveryrequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescTenantID is the schema descriptor for tenant_id field.
	roleDescTenantID := roleFields[1].Descriptor()
	// role.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	role.TenantIDValidator = roleDescTenantID.Validators[0].(func(string) error)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[2].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescSlug is the schema descriptor for slug field.
	roleDescSlug := roleFields[3].Descriptor()
	// role.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	role.SlugValidator = roleDescSlug.Validators[0].(func(string) error)
	// roleDescIsSystemRole is the schema descriptor for is_system_role field.
	roleDescIsSystemRole := roleFields[5].Descriptor()
	// role.DefaultIsSystemRole holds the default value on creation for the is_system_role field.
	role.DefaultIsSystemRole = roleDescIsSystemRole.Default.(bool)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[8].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[9].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	samlconnectionFields := schema.SAMLConnection{}.Fields()
	_ = samlconnectionFields
	// samlconnectionDescOrganizationID is the schema descriptor for organization_id field.
	samlconnectionDescOrganizationID := samlconnectionFields[1].Descriptor()
	// samlconnection.OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	samlconnection.OrganizationIDValidator = samlconnectionDescOrganizationID.Validators[0].(func(string) error)
	// samlconnectionDescIdpEntityID is the schema descriptor for idp_entity_id field.
	samlconnectionDescIdpEntityID := samlconnectionFields[2].Descriptor()
	// samlconnection.IdpEntityIDValidator is a validator for the "idp_entity_id" field. It is called by the builders before save.
	samlconnection.IdpEntityIDValidator = samlconnectionDescIdpEntityID.Validators[0].(func(string) error)
	// samlconnectionDescIdpSSOURL is the schema descriptor for idp_sso_url field.
	samlconnectionDescIdpSSOURL := samlconnectionFields[3].Descriptor()
	// samlconnection.IdpSSOURLValidator is a validator for the "idp_sso_url" field. It is called by the builders before save.
	samlconnection.IdpSSOURLValidator = samlconnectionDescIdpSSOURL.Validators[0].(func(string) error)
	// samlconnectionDescIdpCertificate is the schema descriptor for idp_certificate field.
	samlconnectionDescIdpCertificate := samlconnectionFields[4].Descriptor()
	// samlconnection.IdpCertificateValidator is a validator for the "idp_certificate" field. It is called by the builders before save.
	samlconnection.IdpCertificateValidator = samlconnectionDescIdpCertificate.Validators[0].(func(string) error)
	// samlconnectionDescEnforceSSO is the schema descriptor for enforce_sso field.
	samlconnectionDescEnforceSSO := samlconnectionFields[7].Descriptor()
	// samlconnection.DefaultEnforceSSO holds the default value on creation for the enforce_sso field.
	samlconnection.DefaultEnforceSSO = samlconnectionDescEnforceSSO.Default.(bool)
	// samlconnectionDescCreatedAt is the schema descriptor for created_at field.
	samlconnectionDescCreatedAt := samlconnectionFields[9].Descriptor()
	// samlconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	samlconnection.DefaultCreatedAt = samlconnectionDescCreatedAt.Default.(func() time.Time)
	// samlconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	samlconnectionDescUpdatedAt := samlconnectionFields[10].Descriptor()
	// samlconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	samlconnection.DefaultUpdatedAt = samlconnectionDescUpdatedAt.Default.(func() time.Time)
	// samlconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	samlconnection.UpdateDefaultUpdatedAt = samlconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	sandboxmessageFields := schema.SandboxMessage{}.Fields()
	_ = sandboxmessageFields
	// sandboxmessageDescTenantID is the schema descriptor for tenant_id field.
	sandboxmessageDescTenantID := sandboxmessageFields[1].Descriptor()
	// sandboxmessage.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	sandboxmessage.TenantIDValidator = sandboxmessageDescTenantID.Validators[0].(func(string) error)
	// sandboxmessageDescRecipient is the schema descriptor for recipient field.
	sandboxmessageDescRecipient := sandboxmessageFields[4].Descriptor()
	// sandboxmessage.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	sandboxmessage.RecipientValidator = sandboxmessageDescRecipient.Validators[0].(func(string) error)
	// sandboxmessageDescCreatedAt is the schema descriptor for created_at field.
	sandboxmessageDescCreatedAt := sandboxmessageFields[10].Descriptor()
	// sandboxmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	sandboxmessage.DefaultCreatedAt = sandboxmessageDescCreatedAt.Default.(func() time.Time)
	securityblacklistFields := schema.SecurityBlacklist{}.Fields()
	_ = securityblacklistFields
	// securityblacklistDescTenantID is the schema descriptor for tenant_id field.
	securityblacklistDescTenantID := securityblacklistFields[1].Descriptor()
	// securityblacklist.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	securityblacklist.TenantIDValidator = securityblacklistDescTenantID.Validators[0].(func(string) error)
	// securityblacklistDescUserID is the schema descriptor for user_id field.
	securityblacklistDescUserID := securityblacklistFields[2].Descriptor()
	// securityblacklist.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	securityblacklist.UserIDValidator = securityblacklistDescUserID.Validators[0].(func(string) error)
	// securityblacklistDescReason is the schema descriptor for reason field.
	securityblacklistDescReason := securityblacklistFields[6].Descriptor()
	// securityblacklist.DefaultReason holds the default value on creation for the reason field.
	securityblacklist.DefaultReason = securityblacklistDescReason.Default.(string)
	// securityblacklistDescCreatedAt is the schema descriptor for created_at field.
	securityblacklistDescCreatedAt := securityblacklistFields[8].Descriptor()
	// securityblacklist.DefaultCreatedAt holds the default value on creation for the created_at field.
	securityblacklist.DefaultCreatedAt = securityblacklistDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescUserID is the schema descriptor for user_id field.
	sessionDescUserID := sessionFields[1].Descriptor()
	// session.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	session.UserIDValidator = sessionDescUserID.Validators[0].(func(string) error)
	// sessionDescRefreshTokenHash is the schema descriptor for refresh_token_hash field.
	sessionDescRefreshTokenHash := sessionFields[2].Descriptor()
	// session.RefreshTokenHashValidator is a validator for the "refresh_token_hash" field. It is called by the builders before save.
	session.RefreshTokenHashValidator = sessionDescRefreshTokenHash.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[14].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	sessionappactivityFields := schema.SessionAppActivity{}.Fields()
	_ = sessionappactivityFields
	// sessionappactivityDescSessionID is the schema descriptor for session_id field.
	sessionappactivityDescSessionID := sessionappactivityFields[1].Descriptor()
	// sessionappactivity.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	sessionappactivity.SessionIDValidator = sessionappactivityDescSessionID.Validators[0].(func(string) error)
	// sessionappactivityDescApplicationID is the schema descriptor for application_id field.
	sessionappactivityDescApplicationID := sessionappactivityFields[2].Descriptor()
	// sessionappactivity.ApplicationIDValidator is a validator for the "application_id" field. It is called by the builders before save.
	sessionappactivity.ApplicationIDValidator = sessionappactivityDescApplicationID.Validators[0].(func(string) error)
	// sessionappactivityDescFirstSeenAt is the schema descriptor for first_seen_at field.
	sessionappactivityDescFirstSeenAt := sessionappactivityFields[3].Descriptor()
	// sessionappactivity.DefaultFirstSeenAt holds the default value on creation for the first_seen_at field.
	sessionappactivity.DefaultFirstSeenAt = sessionappactivityDescFirstSeenAt.Default.(func() time.Time)
	// sessionappactivityDescLastActiveAt is the schema descriptor for last_active_at field.
	sessionappactivityDescLastActiveAt := sessionappactivityFields[4].Descriptor()
	// sessionappactivity.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	sessionappactivity.DefaultLastActiveAt = sessionappactivityDescLastActiveAt.Default.(func() time.Time)
	socialauthstateFields := schema.SocialAuthState{}.Fields()
	_ = socialauthstateFields
	// socialauthstateDescTenantID is the schema descriptor for tenant_id field.
	socialauthstateDescTenantID := socialauthstateFields[1].Descriptor()
	// socialauthstate.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	socialauthstate.TenantIDValidator = socialauthstateDescTenantID.Validators[0].(func(string) error)
	// socialauthstateDescApplicationID is the schema descriptor for application_id field.
	socialauthstateDescApplicationID := socialauthstateFields[2].Descriptor()
	// socialauthstate.ApplicationIDValidator is a validator for the "application_id" field. It is called by the builders before save.
	socialauthstate.ApplicationIDValidator = socialauthstateDescApplicationID.Validators[0].(func(string) error)
	// socialauthstateDescEnvironment is the schema descriptor for environment field.
	socialauthstateDescEnvironment := socialauthstateFields[3].Descriptor()
	// socialauthstate.EnvironmentValidator is a validator for the "environment" field. It is called by the builders before save.
	socialauthstate.EnvironmentValidator = socialauthstateDescEnvironment.Validators[0].(func(string) error)
	// socialauthstateDescProvider is the schema descriptor for provider field.
	socialauthstateDescProvider := socialauthstateFields[4].Descriptor()
	// socialauthstate.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	socialauthstate.ProviderValidator = socialauthstateDescProvider.Validators[0].(func(string) error)
	// socialauthstateDescRedirectURI is the schema descriptor for redirect_uri field.
	socialauthstateDescRedirectURI := socialauthstateFields[5].Descriptor()
	// socialauthstate.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	socialauthstate.RedirectURIValidator = socialauthstateDescRedirectURI.Validators[0].(func(string) error)
	// socialauthstateDescCreatedAt is the schema descriptor for created_at field.
	socialauthstateDescCreatedAt := socialauthstateFields[8].Descriptor()
	// socialauthstate.DefaultCreatedAt holds the default value on creation for the created_at field.
	socialauthstate.DefaultCreatedAt = socialauthstateDescCreatedAt.Default.(func() time.Time)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescDomainVerified is the schema descriptor for domain_verified field.
	tenantDescDomainVerified := tenantFields[4].Descriptor()
	// tenant.DefaultDomainVerified holds the default value on creation for the domain_verified field.
	tenant.DefaultDomainVerified = tenantDescDomainVerified.Default.(bool)
	// tenantDescFirstAdminClaimed is the schema descriptor for first_admin_claimed field.
	tenantDescFirstAdminClaimed := tenantFields[6].Descriptor()
	// tenant.DefaultFirstAdminClaimed holds the default value on creation for the first_admin_claimed field.
	tenant.DefaultFirstAdminClaimed = tenantDescFirstAdminClaimed.Default.(bool)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[7].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[8].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	tenantenvironmentFields := schema.TenantEnvironment{}.Fields()
	_ = tenantenvironmentFields
	// tenantenvironmentDescTenantID is the schema descriptor for tenant_id field.
	tenantenvironmentDescTenantID := tenantenvironmentFields[1].Descriptor()
	// tenantenvironment.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	tenantenvironment.TenantIDValidator = tenantenvironmentDescTenantID.Validators[0].(func(string) error)
	// tenantenvironmentDescCreatedAt is the schema descriptor for created_at field.
	tenantenvironmentDescCreatedAt := tenantenvironmentFields[11].Descriptor()
	// tenantenvironment.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantenvironment.DefaultCreatedAt = tenantenvironmentDescCreatedAt.Default.(func() time.Time)
	// tenantenvironmentDescUpdatedAt is the schema descriptor for updated_at field.
	tenantenvironmentDescUpdatedAt := tenantenvironmentFields[12].Descriptor()
	// tenantenvironment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantenvironment.DefaultUpdatedAt = tenantenvironmentDescUpdatedAt.Default.(func() time.Time)
	// tenantenvironment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantenvironment.UpdateDefaultUpdatedAt = tenantenvironmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	trusteddeviceFields := schema.TrustedDevice{}.Fields()
	_ = trusteddeviceFields
	// trusteddeviceDescUserID is the schema descriptor for user_id field.
	trusteddeviceDescUserID := trusteddeviceFields[1].Descriptor()
	// trusteddevice.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	trusteddevice.UserIDValidator = trusteddeviceDescUserID.Validators[0].(func(string) error)
	// trusteddeviceDescDeviceTokenHash is the schema descriptor for device_token_hash field.
	trusteddeviceDescDeviceTokenHash := trusteddeviceFields[2].Descriptor()
	// trusteddevice.DeviceTokenHashValidator is a validator for the "device_token_hash" field. It is called by the builders before save.
	trusteddevice.DeviceTokenHashValidator = trusteddeviceDescDeviceTokenHash.Validators[0].(func(string) error)
	// trusteddeviceDescFingerprintHash is the schema descriptor for fingerprint_hash field.
	trusteddeviceDescFingerprintHash := trusteddeviceFields[3].Descriptor()
	// trusteddevice.FingerprintHashValidator is a validator for the "fingerprint_hash" field. It is called by the builders before save.
	trusteddevice.FingerprintHashValidator = trusteddeviceDescFingerprintHash.Validators[0].(func(string) error)
	// trusteddeviceDescLastIPAddress is the schema descriptor for last_ip_address field.
	trusteddeviceDescLastIPAddress := trusteddeviceFields[5].Descriptor()
	// trusteddevice.LastIPAddressValidator is a validator for the "last_ip_address" field. It is called by the builders before save.
	trusteddevice.LastIPAddressValidator = trusteddeviceDescLastIPAddress.Validators[0].(func(string) error)
	// trusteddeviceDescLastIPSubnet is the schema descriptor for last_ip_subnet field.
	trusteddeviceDescLastIPSubnet := trusteddeviceFields[6].Descriptor()
	// trusteddevice.LastIPSubnetValidator is a validator for the "last_ip_subnet" field. It is called by the builders before save.
	trusteddevice.LastIPSubnetValidator = trusteddeviceDescLastIPSubnet.Validators[0].(func(string) error)
	// trusteddeviceDescFirstSeenAt is the schema descriptor for first_seen_at field.
	trusteddeviceDescFirstSeenAt := trusteddeviceFields[8].Descriptor()
	// trusteddevice.DefaultFirstSeenAt holds the default value on creation for the first_seen_at field.
	trusteddevice.DefaultFirstSeenAt = trusteddeviceDescFirstSeenAt.Default.(func() time.Time)
	// trusteddeviceDescLastSeenAt is the schema descriptor for last_seen_at field.
	trusteddeviceDescLastSeenAt := trusteddeviceFields[9].Descriptor()
	// trusteddevice.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	trusteddevice.DefaultLastSeenAt = trusteddeviceDescLastSeenAt.Default.(func() time.Time)
	// trusteddevice.UpdateDefaultLastSeenAt holds the default value on update for the last_seen_at field.
	trusteddevice.UpdateDefaultLastSeenAt = trusteddeviceDescLastSeenAt.UpdateDefault.(func() time.Time)
	twofactormethodFields := schema.TwoFactorMethod{}.Fields()
	_ = twofactormethodFields
	// twofactormethodDescUserID is the schema descriptor for user_id field.
	twofactormethodDescUserID := twofactormethodFields[1].Descriptor()
	// twofactormethod.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	twofactormethod.UserIDValidator = twofactormethodDescUserID.Validators[0].(func(string) error)
	// twofactormethodDescSignCount is the schema descriptor for sign_count field.
	twofactormethodDescSignCount := twofactormethodFields[7].Descriptor()
	// twofactormethod.DefaultSignCount holds the default value on creation for the sign_count field.
	twofactormethod.DefaultSignCount = twofactormethodDescSignCount.Default.(uint32)
	// twofactormethodDescIsEnabled is the schema descriptor for is_enabled field.
	twofactormethodDescIsEnabled := twofactormethodFields[9].Descriptor()
	// twofactormethod.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	twofactormethod.DefaultIsEnabled = twofactormethodDescIsEnabled.Default.(bool)
	// twofactormethodDescCreatedAt is the schema descriptor for created_at field.
	twofactormethodDescCreatedAt := twofactormethodFields[11].Descriptor()
	// twofactormethod.DefaultCreatedAt holds the default value on creation for the created_at field.
	twofactormethod.DefaultCreatedAt = twofactormethodDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTenantID is the schema descriptor for tenant_id field.
	userDescTenantID := userFields[1].Descriptor()
	// user.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	user.TenantIDValidator = userDescTenantID.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[6].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescPhoneVerified is the schema descriptor for phone_verified field.
	userDescPhoneVerified := userFields[12].Descriptor()
	// user.DefaultPhoneVerified holds the default value on creation for the phone_verified field.
	user.DefaultPhoneVerified = userDescPhoneVerified.Default.(bool)
	// userDescRecoveryFailedAttempts is the schema descriptor for recovery_failed_attempts field.
	userDescRecoveryFailedAttempts := userFields[20].Descriptor()
	// user.DefaultRecoveryFailedAttempts holds the default value on creation for the recovery_failed_attempts field.
	user.DefaultRecoveryFailedAttempts = userDescRecoveryFailedAttempts.Default.(int)
	// userDescSecurityReviewRequired is the schema descriptor for security_review_required field.
	userDescSecurityReviewRequired := userFields[22].Descriptor()
	// user.DefaultSecurityReviewRequired holds the default value on creation for the security_review_required field.
	user.DefaultSecurityReviewRequired = userDescSecurityReviewRequired.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[23].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[24].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	useripsubnethistoryFields := schema.UserIpSubnetHistory{}.Fields()
	_ = useripsubnethistoryFields
	// useripsubnethistoryDescUserID is the schema descriptor for user_id field.
	useripsubnethistoryDescUserID := useripsubnethistoryFields[1].Descriptor()
	// useripsubnethistory.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	useripsubnethistory.UserIDValidator = useripsubnethistoryDescUserID.Validators[0].(func(string) error)
	// useripsubnethistoryDescSubnet is the schema descriptor for subnet field.
	useripsubnethistoryDescSubnet := useripsubnethistoryFields[2].Descriptor()
	// useripsubnethistory.SubnetValidator is a validator for the "subnet" field. It is called by the builders before save.
	useripsubnethistory.SubnetValidator = useripsubnethistoryDescSubnet.Validators[0].(func(string) error)
	// useripsubnethistoryDescLoginCount is the schema descriptor for login_count field.
	useripsubnethistoryDescLoginCount := useripsubnethistoryFields[4].Descriptor()
	// useripsubnethistory.DefaultLoginCount holds the default value on creation for the login_count field.
	useripsubnethistory.DefaultLoginCount = useripsubnethistoryDescLoginCount.Default.(int)
	// useripsubnethistoryDescFirstSeenAt is the schema descriptor for first_seen_at field.
	useripsubnethistoryDescFirstSeenAt := useripsubnethistoryFields[5].Descriptor()
	// useripsubnethistory.DefaultFirstSeenAt holds the default value on creation for the first_seen_at field.
	useripsubnethistory.DefaultFirstSeenAt = useripsubnethistoryDescFirstSeenAt.Default.(func() time.Time)
	// useripsubnethistoryDescLastSeenAt is the schema descriptor for last_seen_at field.
	useripsubnethistoryDescLastSeenAt := useripsubnethistoryFields[6].Descriptor()
	// useripsubnethistory.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	useripsubnethistory.DefaultLastSeenAt = useripsubnethistoryDescLastSeenAt.Default.(func() time.Time)
	// useripsubnethistory.UpdateDefaultLastSeenAt holds the default value on update for the last_seen_at field.
	useripsubnethistory.UpdateDefaultLastSeenAt = useripsubnethistoryDescLastSeenAt.UpdateDefault.(func() time.Time)
	userpasswordhistoryFields := schema.UserPasswordHistory{}.Fields()
	_ = userpasswordhistoryFields
	// userpasswordhistoryDescUserID is the schema descriptor for user_id field.
	userpasswordhistoryDescUserID := userpasswordhistoryFields[1].Descriptor()
	// userpasswordhistory.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userpasswordhistory.UserIDValidator = userpasswordhistoryDescUserID.Validators[0].(func(string) error)
	// userpasswordhistoryDescPasswordHash is the schema descriptor for password_hash field.
	userpasswordhistoryDescPasswordHash := userpasswordhistoryFields[2].Descriptor()
	// userpasswordhistory.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	userpasswordhistory.PasswordHashValidator = userpasswordhistoryDescPasswordHash.Validators[0].(func(string) error)
	// userpasswordhistoryDescCreatedAt is the schema descriptor for created_at field.
	userpasswordhistoryDescCreatedAt := userpasswordhistoryFields[3].Descriptor()
	// userpasswordhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	userpasswordhistory.DefaultCreatedAt = userpasswordhistoryDescCreatedAt.Default.(func() time.Time)
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescUserID is the schema descriptor for user_id field.
	userroleDescUserID := userroleFields[1].Descriptor()
	// userrole.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userrole.UserIDValidator = userroleDescUserID.Validators[0].(func(string) error)
	// userroleDescRoleID is the schema descriptor for role_id field.
	userroleDescRoleID := userroleFields[2].Descriptor()
	// userrole.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	userrole.RoleIDValidator = userroleDescRoleID.Validators[0].(func(string) error)
	// userroleDescCreatedAt is the schema descriptor for created_at field.
	userroleDescCreatedAt := userroleFields[5].Descriptor()
	// userrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrole.DefaultCreatedAt = userroleDescCreatedAt.Default.(func() time.Time)
	// userroleDescUpdatedAt is the schema descriptor for updated_at field.
	userroleDescUpdatedAt := userroleFields[6].Descriptor()
	// userrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userrole.DefaultUpdatedAt = userroleDescUpdatedAt.Default.(func() time.Time)
	// userrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userrole.UpdateDefaultUpdatedAt = userroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	webhookendpointFields := schema.WebhookEndpoint{}.Fields()
	_ = webhookendpointFields
	// webhookendpointDescTenantID is the schema descriptor for tenant_id field.
	webhookendpointDescTenantID := webhookendpointFields[1].Descriptor()
	// webhookendpoint.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	webhookendpoint.TenantIDValidator = webhookendpointDescTenantID.Validators[0].(func(string) error)
	// webhookendpointDescURL is the schema descriptor for url field.
	webhookendpointDescURL := webhookendpointFields[2].Descriptor()
	// webhookendpoint.URLValidator is a validator for the "url" field. It is called by the builders before save.
	webhookendpoint.URLValidator = webhookendpointDescURL.Validators[0].(func(string) error)
	// webhookendpointDescSecretKeyEncrypted is the schema descriptor for secret_key_encrypted field.
	webhookendpointDescSecretKeyEncrypted := webhookendpointFields[4].Descriptor()
	// webhookendpoint.SecretKeyEncryptedValidator is a validator for the "secret_key_encrypted" field. It is called by the builders before save.
	webhookendpoint.SecretKeyEncryptedValidator = webhookendpointDescSecretKeyEncrypted.Validators[0].(func(string) error)
	// webhookendpointDescIsActive is the schema descriptor for is_active field.
	webhookendpointDescIsActive := webhookendpointFields[7].Descriptor()
	// webhookendpoint.DefaultIsActive holds the default value on creation for the is_active field.
	webhookendpoint.DefaultIsActive = webhookendpointDescIsActive.Default.(bool)
	// webhookendpointDescFailureCount is the schema descriptor for failure_count field.
	webhookendpointDescFailureCount := webhookendpointFields[8].Descriptor()
	// webhookendpoint.DefaultFailureCount holds the default value on creation for the failure_count field.
	webhookendpoint.DefaultFailureCount = webhookendpointDescFailureCount.Default.(int)
	// webhookendpointDescCreatedAt is the schema descriptor for created_at field.
	webhookendpointDescCreatedAt := webhookendpointFields[10].Descriptor()
	// webhookendpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	webhookendpoint.DefaultCreatedAt = webhookendpointDescCreatedAt.Default.(func() time.Time)
	webhookeventFields := schema.WebhookEvent{}.Fields()
	_ = webhookeventFields
	// webhookeventDescWebhookEndpointID is the schema descriptor for webhook_endpoint_id field.
	webhookeventDescWebhookEndpointID := webhookeventFields[1].Descriptor()
	// webhookevent.WebhookEndpointIDValidator is a validator for the "webhook_endpoint_id" field. It is called by the builders before save.
	webhookevent.WebhookEndpointIDValidator = webhookeventDescWebhookEndpointID.Validators[0].(func(string) error)
	// webhookeventDescEventType is the schema descriptor for event_type field.
	webhookeventDescEventType := webhookeventFields[2].Descriptor()
	// webhookevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	webhookevent.EventTypeValidator = webhookeventDescEventType.Validators[0].(func(string) error)
	// webhookeventDescCreatedAt is the schema descriptor for created_at field.
	webhookeventDescCreatedAt := webhookeventFields[8].Descriptor()
	// webhookevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	webhookevent.DefaultCreatedAt = webhookeventDescCreatedAt.Default.(func() time.Time)
}
