// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/socialauthstate"
)

// SocialAuthStateCreate is the builder for creating a SocialAuthState entity.
type SocialAuthStateCreate struct {
	config
	mutation *SocialAuthStateMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (sasc *SocialAuthStateCreate) SetTenantID(s string) *SocialAuthStateCreate {
	sasc.mutation.SetTenantID(s)
	return sasc
}

// SetApplicationID sets the "application_id" field.
func (sasc *SocialAuthStateCreate) SetApplicationID(s string) *SocialAuthStateCreate {
	sasc.mutation.SetApplicationID(s)
	return sasc
}

// SetEnvironment sets the "environment" field.
func (sasc *SocialAuthStateCreate) SetEnvironment(s string) *SocialAuthStateCreate {
	sasc.mutation.SetEnvironment(s)
	return sasc
}

// SetProvider sets the "provider" field.
func (sasc *SocialAuthStateCreate) SetProvider(s string) *SocialAuthStateCreate {
	sasc.mutation.SetProvider(s)
	return sasc
}

// SetRedirectURI sets the "redirect_uri" field.
func (sasc *SocialAuthStateCreate) SetRedirectURI(s string) *SocialAuthStateCreate {
	sasc.mutation.SetRedirectURI(s)
	return sasc
}

// SetPostCallbackRedirect sets the "post_callback_redirect" field.
func (sasc *SocialAuthStateCreate) SetPostCallbackRedirect(s string) *SocialAuthStateCreate {
	sasc.mutation.SetPostCallbackRedirect(s)
	return sasc
}

// SetNillablePostCallbackRedirect sets the "post_callback_redirect" field if the given value is not nil.
func (sasc *SocialAuthStateCreate) SetNillablePostCallbackRedirect(s *string) *SocialAuthStateCreate {
	if s != nil {
		sasc.SetPostCallbackRedirect(*s)
	}
	return sasc
}

// SetExpiresAt sets the "expires_at" field.
func (sasc *SocialAuthStateCreate) SetExpiresAt(t time.Time) *SocialAuthStateCreate {
	sasc.mutation.SetExpiresAt(t)
	return sasc
}

// SetCreatedAt sets the "created_at" field.
func (sasc *SocialAuthStateCreate) SetCreatedAt(t time.Time) *SocialAuthStateCreate {
	sasc.mutation.SetCreatedAt(t)
	return sasc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sasc *SocialAuthStateCreate) SetNillableCreatedAt(t *time.Time) *SocialAuthStateCreate {
	if t != nil {
		sasc.SetCreatedAt(*t)
	}
	return sasc
}

// SetID sets the "id" field.
func (sasc *SocialAuthStateCreate) SetID(s string) *SocialAuthStateCreate {
	sasc.mutation.SetID(s)
	return sasc
}

// Mutation returns the SocialAuthStateMutation object of the builder.
func (sasc *SocialAuthStateCreate) Mutation() *SocialAuthStateMutation {
	return sasc.mutation
}

// Save creates the SocialAuthState in the database.
func (sasc *SocialAuthStateCreate) Save(ctx context.Context) (*SocialAuthState, error) {
	sasc.defaults()
	return withHooks(ctx, sasc.sqlSave, sasc.mutation, sasc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sasc *SocialAuthStateCreate) SaveX(ctx context.Context) *SocialAuthState {
	v, err := sasc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sasc *SocialAuthStateCreate) Exec(ctx context.Context) error {
	_, err := sasc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sasc *SocialAuthStateCreate) ExecX(ctx context.Context) {
	if err := sasc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sasc *SocialAuthStateCreate) defaults() {
	if _, ok := sasc.mutation.CreatedAt(); !ok {
		v := socialauthstate.DefaultCreatedAt()
		sasc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sasc *SocialAuthStateCreate) check() error {
	if _, ok := sasc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SocialAuthState.tenant_id"`)}
	}
	if v, ok := sasc.mutation.TenantID(); ok {
		if err := socialauthstate.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SocialAuthState.tenant_id": %w`, err)}
		}
	}
	if _, ok := sasc.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "SocialAuthState.application_id"`)}
	}
	if v, ok := sasc.mutation.ApplicationID(); ok {
		if err := socialauthstate.ApplicationIDValidator(v); err != nil {
			return &ValidationError{Name: "application_id", err: fmt.Errorf(`ent: validator failed for field "SocialAuthState.application_id": %w`, err)}
		}
	}
	if _, ok := sasc.mutation.Environment(); !ok {
		return &ValidationError{Name: "environment", err: errors.New(`ent: missing required field "SocialAuthState.environment"`)}
	}
	if v, ok := sasc.mutation.Environment(); ok {
		if err := socialauthstate.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "SocialAuthState.environment": %w`, err)}
		}
	}
	if _, ok := sasc.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "SocialAuthState.provider"`)}
	}
	if v, ok := sasc.mutation.Provider(); ok {
		if err := socialauthstate.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "SocialAuthState.provider": %w`, err)}
		}
	}
	if _, ok := sasc.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "SocialAuthState.redirect_uri"`)}
	}
	if v, ok := sasc.mutation.RedirectURI(); ok {
		if err := socialauthstate.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "SocialAuthState.redirect_uri": %w`, err)}
		}
	}
	if _, ok := sasc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "SocialAuthState.expires_at"`)}
	}
	if _, ok := sasc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SocialAuthState.created_at"`)}
	}
	return nil
}

func (sasc *SocialAuthStateCreate) sqlSave(ctx context.Context) (*SocialAuthState, error) {
	if err := sasc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sasc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sasc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SocialAuthState.ID type: %T", _spec.ID.Value)
		}
	}
	sasc.mutation.id = &_node.ID
	sasc.mutation.done = true
	return _node, nil
}

func (sasc *SocialAuthStateCreate) createSpec() (*SocialAuthState, *sqlgraph.CreateSpec) {
	var (
		_node = &SocialAuthState{config: sasc.config}
		_spec = sqlgraph.NewCreateSpec(socialauthstate.Table, sqlgraph.NewFieldSpec(socialauthstate.FieldID, field.TypeString))
	)
	if id, ok := sasc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sasc.mutation.TenantID(); ok {
		_spec.SetField(socialauthstate.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := sasc.mutation.ApplicationID(); ok {
		_spec.SetField(socialauthstate.FieldApplicationID, field.TypeString, value)
		_node.ApplicationID = value
	}
	if value, ok := sasc.mutation.Environment(); ok {
		_spec.SetField(socialauthstate.FieldEnvironment, field.TypeString, value)
		_node.Environment = value
	}
	if value, ok := sasc.mutation.Provider(); ok {
		_spec.SetField(socialauthstate.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := sasc.mutation.RedirectURI(); ok {
		_spec.SetField(socialauthstate.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := sasc.mutation.PostCallbackRedirect(); ok {
		_spec.SetField(socialauthstate.FieldPostCallbackRedirect, field.TypeString, value)
		_node.PostCallbackRedirect = value
	}
	if value, ok := sasc.mutation.ExpiresAt(); ok {
		_spec.SetField(socialauthstate.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := sasc.mutation.CreatedAt(); ok {
		_spec.SetField(socialauthstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SocialAuthStateCreateBulk is the builder for creating many SocialAuthState entities in bulk.
type SocialAuthStateCreateBulk struct {
	config
	err      error
	builders []*SocialAuthStateCreate
}

// Save creates the SocialAuthState entities in the database.
func (sascb *SocialAuthStateCreateBulk) Save(ctx context.Context) ([]*SocialAuthState, error) {
	if sascb.err != nil {
		return nil, sascb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sascb.builders))
	nodes := make([]*SocialAuthState, len(sascb.builders))
	mutators := make([]Mutator, len(sascb.builders))
	for i := range sascb.builders {
		func(i int, root context.Context) {
			builder := sascb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SocialAuthStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sascb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sascb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sascb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sascb *SocialAuthStateCreateBulk) SaveX(ctx context.Context) []*SocialAuthState {
	v, err := sascb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sascb *SocialAuthStateCreateBulk) Exec(ctx context.Context) error {
	_, err := sascb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sascb *SocialAuthStateCreateBulk) ExecX(ctx context.Context) {
	if err := sascb.Exec(ctx); err != nil {
		panic(err)
	}
}
