// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/socialauthstate"
)

// SocialAuthState is the model entity for the SocialAuthState schema.
type SocialAuthState struct {
	config `json:"-"`
	// ID of the ent.
	// The state token itself — 32 random hex bytes used as the primary key and CSRF nonce
	ID string `json:"id,omitempty"`
	// Owning Tenant ID — scopes the callback lookup to the correct tenant
	TenantID string `json:"tenant_id,omitempty"`
	// Application ID that initiated the social login request
	ApplicationID string `json:"application_id,omitempty"`
	// Environment mode: test or live — must match the pk_ key used
	Environment string `json:"environment,omitempty"`
	// Social provider name (google, github, discord, microsoft, apple, facebook, x, linkedin, oidc)
	Provider string `json:"provider,omitempty"`
	// Client-supplied redirect URI — validated against application.exact_redirect_uris, returned to client after successful callback
	RedirectURI string `json:"redirect_uri,omitempty"`
	// Optional deep-link URL to redirect to after our callback completes (e.g. the SPA page that triggered the flow)
	PostCallbackRedirect string `json:"post_callback_redirect,omitempty"`
	// Expiration timestamp — 10 minutes from creation. Requests arriving after this are rejected with 400 state_expired
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// State token creation timestamp
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SocialAuthState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case socialauthstate.FieldID, socialauthstate.FieldTenantID, socialauthstate.FieldApplicationID, socialauthstate.FieldEnvironment, socialauthstate.FieldProvider, socialauthstate.FieldRedirectURI, socialauthstate.FieldPostCallbackRedirect:
			values[i] = new(sql.NullString)
		case socialauthstate.FieldExpiresAt, socialauthstate.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SocialAuthState fields.
func (sas *SocialAuthState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case socialauthstate.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				sas.ID = value.String
			}
		case socialauthstate.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				sas.TenantID = value.String
			}
		case socialauthstate.FieldApplicationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_id", values[i])
			} else if value.Valid {
				sas.ApplicationID = value.String
			}
		case socialauthstate.FieldEnvironment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value.Valid {
				sas.Environment = value.String
			}
		case socialauthstate.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				sas.Provider = value.String
			}
		case socialauthstate.FieldRedirectURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_uri", values[i])
			} else if value.Valid {
				sas.RedirectURI = value.String
			}
		case socialauthstate.FieldPostCallbackRedirect:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_callback_redirect", values[i])
			} else if value.Valid {
				sas.PostCallbackRedirect = value.String
			}
		case socialauthstate.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				sas.ExpiresAt = value.Time
			}
		case socialauthstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sas.CreatedAt = value.Time
			}
		default:
			sas.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SocialAuthState.
// This includes values selected through modifiers, order, etc.
func (sas *SocialAuthState) Value(name string) (ent.Value, error) {
	return sas.selectValues.Get(name)
}

// Update returns a builder for updating this SocialAuthState.
// Note that you need to call SocialAuthState.Unwrap() before calling this method if this SocialAuthState
// was returned from a transaction, and the transaction was committed or rolled back.
func (sas *SocialAuthState) Update() *SocialAuthStateUpdateOne {
	return NewSocialAuthStateClient(sas.config).UpdateOne(sas)
}

// Unwrap unwraps the SocialAuthState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sas *SocialAuthState) Unwrap() *SocialAuthState {
	_tx, ok := sas.config.driver.(*txDriver)
	if !ok {
		panic("ent: SocialAuthState is not a transactional entity")
	}
	sas.config.driver = _tx.drv
	return sas
}

// String implements the fmt.Stringer.
func (sas *SocialAuthState) String() string {
	var builder strings.Builder
	builder.WriteString("SocialAuthState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sas.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(sas.TenantID)
	builder.WriteString(", ")
	builder.WriteString("application_id=")
	builder.WriteString(sas.ApplicationID)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(sas.Environment)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(sas.Provider)
	builder.WriteString(", ")
	builder.WriteString("redirect_uri=")
	builder.WriteString(sas.RedirectURI)
	builder.WriteString(", ")
	builder.WriteString("post_callback_redirect=")
	builder.WriteString(sas.PostCallbackRedirect)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(sas.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sas.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SocialAuthStates is a parsable slice of SocialAuthState.
type SocialAuthStates []*SocialAuthState
