// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/tenant"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/tenantenvironment"
)

// TenantEnvironmentCreate is the builder for creating a TenantEnvironment entity.
type TenantEnvironmentCreate struct {
	config
	mutation *TenantEnvironmentMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (tec *TenantEnvironmentCreate) SetTenantID(s string) *TenantEnvironmentCreate {
	tec.mutation.SetTenantID(s)
	return tec
}

// SetEnvironment sets the "environment" field.
func (tec *TenantEnvironmentCreate) SetEnvironment(t tenantenvironment.Environment) *TenantEnvironmentCreate {
	tec.mutation.SetEnvironment(t)
	return tec
}

// SetBrandingConfig sets the "branding_config" field.
func (tec *TenantEnvironmentCreate) SetBrandingConfig(m map[string]interface{}) *TenantEnvironmentCreate {
	tec.mutation.SetBrandingConfig(m)
	return tec
}

// SetPasswordPolicy sets the "password_policy" field.
func (tec *TenantEnvironmentCreate) SetPasswordPolicy(m map[string]interface{}) *TenantEnvironmentCreate {
	tec.mutation.SetPasswordPolicy(m)
	return tec
}

// SetSecurityPolicy sets the "security_policy" field.
func (tec *TenantEnvironmentCreate) SetSecurityPolicy(m map[string]interface{}) *TenantEnvironmentCreate {
	tec.mutation.SetSecurityPolicy(m)
	return tec
}

// SetRecoveryPolicy sets the "recovery_policy" field.
func (tec *TenantEnvironmentCreate) SetRecoveryPolicy(m map[string]interface{}) *TenantEnvironmentCreate {
	tec.mutation.SetRecoveryPolicy(m)
	return tec
}

// SetSocialProviders sets the "social_providers" field.
func (tec *TenantEnvironmentCreate) SetSocialProviders(m map[string]interface{}) *TenantEnvironmentCreate {
	tec.mutation.SetSocialProviders(m)
	return tec
}

// SetRolePolicy sets the "role_policy" field.
func (tec *TenantEnvironmentCreate) SetRolePolicy(m map[string]interface{}) *TenantEnvironmentCreate {
	tec.mutation.SetRolePolicy(m)
	return tec
}

// SetSessionPolicy sets the "session_policy" field.
func (tec *TenantEnvironmentCreate) SetSessionPolicy(m map[string]interface{}) *TenantEnvironmentCreate {
	tec.mutation.SetSessionPolicy(m)
	return tec
}

// SetPublishedAt sets the "published_at" field.
func (tec *TenantEnvironmentCreate) SetPublishedAt(t time.Time) *TenantEnvironmentCreate {
	tec.mutation.SetPublishedAt(t)
	return tec
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (tec *TenantEnvironmentCreate) SetNillablePublishedAt(t *time.Time) *TenantEnvironmentCreate {
	if t != nil {
		tec.SetPublishedAt(*t)
	}
	return tec
}

// SetCreatedAt sets the "created_at" field.
func (tec *TenantEnvironmentCreate) SetCreatedAt(t time.Time) *TenantEnvironmentCreate {
	tec.mutation.SetCreatedAt(t)
	return tec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tec *TenantEnvironmentCreate) SetNillableCreatedAt(t *time.Time) *TenantEnvironmentCreate {
	if t != nil {
		tec.SetCreatedAt(*t)
	}
	return tec
}

// SetUpdatedAt sets the "updated_at" field.
func (tec *TenantEnvironmentCreate) SetUpdatedAt(t time.Time) *TenantEnvironmentCreate {
	tec.mutation.SetUpdatedAt(t)
	return tec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tec *TenantEnvironmentCreate) SetNillableUpdatedAt(t *time.Time) *TenantEnvironmentCreate {
	if t != nil {
		tec.SetUpdatedAt(*t)
	}
	return tec
}

// SetID sets the "id" field.
func (tec *TenantEnvironmentCreate) SetID(s string) *TenantEnvironmentCreate {
	tec.mutation.SetID(s)
	return tec
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (tec *TenantEnvironmentCreate) SetTenant(t *Tenant) *TenantEnvironmentCreate {
	return tec.SetTenantID(t.ID)
}

// Mutation returns the TenantEnvironmentMutation object of the builder.
func (tec *TenantEnvironmentCreate) Mutation() *TenantEnvironmentMutation {
	return tec.mutation
}

// Save creates the TenantEnvironment in the database.
func (tec *TenantEnvironmentCreate) Save(ctx context.Context) (*TenantEnvironment, error) {
	tec.defaults()
	return withHooks(ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TenantEnvironmentCreate) SaveX(ctx context.Context) *TenantEnvironment {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TenantEnvironmentCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TenantEnvironmentCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tec *TenantEnvironmentCreate) defaults() {
	if _, ok := tec.mutation.CreatedAt(); !ok {
		v := tenantenvironment.DefaultCreatedAt()
		tec.mutation.SetCreatedAt(v)
	}
	if _, ok := tec.mutation.UpdatedAt(); !ok {
		v := tenantenvironment.DefaultUpdatedAt()
		tec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TenantEnvironmentCreate) check() error {
	if _, ok := tec.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantEnvironment.tenant_id"`)}
	}
	if v, ok := tec.mutation.TenantID(); ok {
		if err := tenantenvironment.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "TenantEnvironment.tenant_id": %w`, err)}
		}
	}
	if _, ok := tec.mutation.Environment(); !ok {
		return &ValidationError{Name: "environment", err: errors.New(`ent: missing required field "TenantEnvironment.environment"`)}
	}
	if v, ok := tec.mutation.Environment(); ok {
		if err := tenantenvironment.EnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "environment", err: fmt.Errorf(`ent: validator failed for field "TenantEnvironment.environment": %w`, err)}
		}
	}
	if _, ok := tec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantEnvironment.created_at"`)}
	}
	if _, ok := tec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantEnvironment.updated_at"`)}
	}
	if len(tec.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "TenantEnvironment.tenant"`)}
	}
	return nil
}

func (tec *TenantEnvironmentCreate) sqlSave(ctx context.Context) (*TenantEnvironment, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TenantEnvironment.ID type: %T", _spec.ID.Value)
		}
	}
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TenantEnvironmentCreate) createSpec() (*TenantEnvironment, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantEnvironment{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(tenantenvironment.Table, sqlgraph.NewFieldSpec(tenantenvironment.FieldID, field.TypeString))
	)
	if id, ok := tec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tec.mutation.Environment(); ok {
		_spec.SetField(tenantenvironment.FieldEnvironment, field.TypeEnum, value)
		_node.Environment = value
	}
	if value, ok := tec.mutation.BrandingConfig(); ok {
		_spec.SetField(tenantenvironment.FieldBrandingConfig, field.TypeJSON, value)
		_node.BrandingConfig = value
	}
	if value, ok := tec.mutation.PasswordPolicy(); ok {
		_spec.SetField(tenantenvironment.FieldPasswordPolicy, field.TypeJSON, value)
		_node.PasswordPolicy = value
	}
	if value, ok := tec.mutation.SecurityPolicy(); ok {
		_spec.SetField(tenantenvironment.FieldSecurityPolicy, field.TypeJSON, value)
		_node.SecurityPolicy = value
	}
	if value, ok := tec.mutation.RecoveryPolicy(); ok {
		_spec.SetField(tenantenvironment.FieldRecoveryPolicy, field.TypeJSON, value)
		_node.RecoveryPolicy = value
	}
	if value, ok := tec.mutation.SocialProviders(); ok {
		_spec.SetField(tenantenvironment.FieldSocialProviders, field.TypeJSON, value)
		_node.SocialProviders = value
	}
	if value, ok := tec.mutation.RolePolicy(); ok {
		_spec.SetField(tenantenvironment.FieldRolePolicy, field.TypeJSON, value)
		_node.RolePolicy = value
	}
	if value, ok := tec.mutation.SessionPolicy(); ok {
		_spec.SetField(tenantenvironment.FieldSessionPolicy, field.TypeJSON, value)
		_node.SessionPolicy = value
	}
	if value, ok := tec.mutation.PublishedAt(); ok {
		_spec.SetField(tenantenvironment.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := tec.mutation.CreatedAt(); ok {
		_spec.SetField(tenantenvironment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tec.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantenvironment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tec.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantenvironment.TenantTable,
			Columns: []string{tenantenvironment.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenantEnvironmentCreateBulk is the builder for creating many TenantEnvironment entities in bulk.
type TenantEnvironmentCreateBulk struct {
	config
	err      error
	builders []*TenantEnvironmentCreate
}

// Save creates the TenantEnvironment entities in the database.
func (tecb *TenantEnvironmentCreateBulk) Save(ctx context.Context) ([]*TenantEnvironment, error) {
	if tecb.err != nil {
		return nil, tecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*TenantEnvironment, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantEnvironmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TenantEnvironmentCreateBulk) SaveX(ctx context.Context) []*TenantEnvironment {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TenantEnvironmentCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TenantEnvironmentCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
