// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/trusteddevice"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/user"
)

// TrustedDeviceQuery is the builder for querying TrustedDevice entities.
type TrustedDeviceQuery struct {
	config
	ctx        *QueryContext
	order      []trusteddevice.OrderOption
	inters     []Interceptor
	predicates []predicate.TrustedDevice
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrustedDeviceQuery builder.
func (tdq *TrustedDeviceQuery) Where(ps ...predicate.TrustedDevice) *TrustedDeviceQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit the number of records to be returned by this query.
func (tdq *TrustedDeviceQuery) Limit(limit int) *TrustedDeviceQuery {
	tdq.ctx.Limit = &limit
	return tdq
}

// Offset to start from.
func (tdq *TrustedDeviceQuery) Offset(offset int) *TrustedDeviceQuery {
	tdq.ctx.Offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *TrustedDeviceQuery) Unique(unique bool) *TrustedDeviceQuery {
	tdq.ctx.Unique = &unique
	return tdq
}

// Order specifies how the records should be ordered.
func (tdq *TrustedDeviceQuery) Order(o ...trusteddevice.OrderOption) *TrustedDeviceQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// QueryUser chains the current query on the "user" edge.
func (tdq *TrustedDeviceQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: tdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(trusteddevice.Table, trusteddevice.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, trusteddevice.UserTable, trusteddevice.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TrustedDevice entity from the query.
// Returns a *NotFoundError when no TrustedDevice was found.
func (tdq *TrustedDeviceQuery) First(ctx context.Context) (*TrustedDevice, error) {
	nodes, err := tdq.Limit(1).All(setContextOp(ctx, tdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trusteddevice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) FirstX(ctx context.Context) *TrustedDevice {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TrustedDevice ID from the query.
// Returns a *NotFoundError when no TrustedDevice ID was found.
func (tdq *TrustedDeviceQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tdq.Limit(1).IDs(setContextOp(ctx, tdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trusteddevice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) FirstIDX(ctx context.Context) string {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TrustedDevice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TrustedDevice entity is found.
// Returns a *NotFoundError when no TrustedDevice entities are found.
func (tdq *TrustedDeviceQuery) Only(ctx context.Context) (*TrustedDevice, error) {
	nodes, err := tdq.Limit(2).All(setContextOp(ctx, tdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trusteddevice.Label}
	default:
		return nil, &NotSingularError{trusteddevice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) OnlyX(ctx context.Context) *TrustedDevice {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TrustedDevice ID in the query.
// Returns a *NotSingularError when more than one TrustedDevice ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *TrustedDeviceQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tdq.Limit(2).IDs(setContextOp(ctx, tdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trusteddevice.Label}
	default:
		err = &NotSingularError{trusteddevice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) OnlyIDX(ctx context.Context) string {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TrustedDevices.
func (tdq *TrustedDeviceQuery) All(ctx context.Context) ([]*TrustedDevice, error) {
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryAll)
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TrustedDevice, *TrustedDeviceQuery]()
	return withInterceptors[[]*TrustedDevice](ctx, tdq, qr, tdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) AllX(ctx context.Context) []*TrustedDevice {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TrustedDevice IDs.
func (tdq *TrustedDeviceQuery) IDs(ctx context.Context) (ids []string, err error) {
	if tdq.ctx.Unique == nil && tdq.path != nil {
		tdq.Unique(true)
	}
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryIDs)
	if err = tdq.Select(trusteddevice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) IDsX(ctx context.Context) []string {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *TrustedDeviceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryCount)
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tdq, querierCount[*TrustedDeviceQuery](), tdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *TrustedDeviceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tdq.ctx, ent.OpQueryExist)
	switch _, err := tdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *TrustedDeviceQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrustedDeviceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *TrustedDeviceQuery) Clone() *TrustedDeviceQuery {
	if tdq == nil {
		return nil
	}
	return &TrustedDeviceQuery{
		config:     tdq.config,
		ctx:        tdq.ctx.Clone(),
		order:      append([]trusteddevice.OrderOption{}, tdq.order...),
		inters:     append([]Interceptor{}, tdq.inters...),
		predicates: append([]predicate.TrustedDevice{}, tdq.predicates...),
		withUser:   tdq.withUser.Clone(),
		// clone intermediate query.
		sql:  tdq.sql.Clone(),
		path: tdq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (tdq *TrustedDeviceQuery) WithUser(opts ...func(*UserQuery)) *TrustedDeviceQuery {
	query := (&UserClient{config: tdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tdq.withUser = query
	return tdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TrustedDevice.Query().
//		GroupBy(trusteddevice.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tdq *TrustedDeviceQuery) GroupBy(field string, fields ...string) *TrustedDeviceGroupBy {
	tdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrustedDeviceGroupBy{build: tdq}
	grbuild.flds = &tdq.ctx.Fields
	grbuild.label = trusteddevice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.TrustedDevice.Query().
//		Select(trusteddevice.FieldUserID).
//		Scan(ctx, &v)
func (tdq *TrustedDeviceQuery) Select(fields ...string) *TrustedDeviceSelect {
	tdq.ctx.Fields = append(tdq.ctx.Fields, fields...)
	sbuild := &TrustedDeviceSelect{TrustedDeviceQuery: tdq}
	sbuild.label = trusteddevice.Label
	sbuild.flds, sbuild.scan = &tdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrustedDeviceSelect configured with the given aggregations.
func (tdq *TrustedDeviceQuery) Aggregate(fns ...AggregateFunc) *TrustedDeviceSelect {
	return tdq.Select().Aggregate(fns...)
}

func (tdq *TrustedDeviceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tdq); err != nil {
				return err
			}
		}
	}
	for _, f := range tdq.ctx.Fields {
		if !trusteddevice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *TrustedDeviceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TrustedDevice, error) {
	var (
		nodes       = []*TrustedDevice{}
		_spec       = tdq.querySpec()
		loadedTypes = [1]bool{
			tdq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TrustedDevice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TrustedDevice{config: tdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tdq.withUser; query != nil {
		if err := tdq.loadUser(ctx, query, nodes, nil,
			func(n *TrustedDevice, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tdq *TrustedDeviceQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*TrustedDevice, init func(*TrustedDevice), assign func(*TrustedDevice, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TrustedDevice)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tdq *TrustedDeviceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	_spec.Node.Columns = tdq.ctx.Fields
	if len(tdq.ctx.Fields) > 0 {
		_spec.Unique = tdq.ctx.Unique != nil && *tdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *TrustedDeviceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(trusteddevice.Table, trusteddevice.Columns, sqlgraph.NewFieldSpec(trusteddevice.FieldID, field.TypeString))
	_spec.From = tdq.sql
	if unique := tdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tdq.path != nil {
		_spec.Unique = true
	}
	if fields := tdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trusteddevice.FieldID)
		for i := range fields {
			if fields[i] != trusteddevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tdq.withUser != nil {
			_spec.Node.AddColumnOnce(trusteddevice.FieldUserID)
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *TrustedDeviceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(trusteddevice.Table)
	columns := tdq.ctx.Fields
	if len(columns) == 0 {
		columns = trusteddevice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.ctx.Unique != nil && *tdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrustedDeviceGroupBy is the group-by builder for TrustedDevice entities.
type TrustedDeviceGroupBy struct {
	selector
	build *TrustedDeviceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *TrustedDeviceGroupBy) Aggregate(fns ...AggregateFunc) *TrustedDeviceGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the selector query and scans the result into the given value.
func (tdgb *TrustedDeviceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tdgb.build.ctx, ent.OpQueryGroupBy)
	if err := tdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrustedDeviceQuery, *TrustedDeviceGroupBy](ctx, tdgb.build, tdgb, tdgb.build.inters, v)
}

func (tdgb *TrustedDeviceGroupBy) sqlScan(ctx context.Context, root *TrustedDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tdgb.flds)+len(tdgb.fns))
		for _, f := range *tdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrustedDeviceSelect is the builder for selecting fields of TrustedDevice entities.
type TrustedDeviceSelect struct {
	*TrustedDeviceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tds *TrustedDeviceSelect) Aggregate(fns ...AggregateFunc) *TrustedDeviceSelect {
	tds.fns = append(tds.fns, fns...)
	return tds
}

// Scan applies the selector query and scans the result into the given value.
func (tds *TrustedDeviceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tds.ctx, ent.OpQuerySelect)
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrustedDeviceQuery, *TrustedDeviceSelect](ctx, tds.TrustedDeviceQuery, tds, tds.inters, v)
}

func (tds *TrustedDeviceSelect) sqlScan(ctx context.Context, root *TrustedDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tds.fns))
	for _, fn := range tds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
