// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/twofactormethod"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/user"
)

// TwoFactorMethodUpdate is the builder for updating TwoFactorMethod entities.
type TwoFactorMethodUpdate struct {
	config
	hooks    []Hook
	mutation *TwoFactorMethodMutation
}

// Where appends a list predicates to the TwoFactorMethodUpdate builder.
func (tfmu *TwoFactorMethodUpdate) Where(ps ...predicate.TwoFactorMethod) *TwoFactorMethodUpdate {
	tfmu.mutation.Where(ps...)
	return tfmu
}

// SetUserID sets the "user_id" field.
func (tfmu *TwoFactorMethodUpdate) SetUserID(s string) *TwoFactorMethodUpdate {
	tfmu.mutation.SetUserID(s)
	return tfmu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tfmu *TwoFactorMethodUpdate) SetNillableUserID(s *string) *TwoFactorMethodUpdate {
	if s != nil {
		tfmu.SetUserID(*s)
	}
	return tfmu
}

// SetType sets the "type" field.
func (tfmu *TwoFactorMethodUpdate) SetType(t twofactormethod.Type) *TwoFactorMethodUpdate {
	tfmu.mutation.SetType(t)
	return tfmu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tfmu *TwoFactorMethodUpdate) SetNillableType(t *twofactormethod.Type) *TwoFactorMethodUpdate {
	if t != nil {
		tfmu.SetType(*t)
	}
	return tfmu
}

// SetName sets the "name" field.
func (tfmu *TwoFactorMethodUpdate) SetName(s string) *TwoFactorMethodUpdate {
	tfmu.mutation.SetName(s)
	return tfmu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tfmu *TwoFactorMethodUpdate) SetNillableName(s *string) *TwoFactorMethodUpdate {
	if s != nil {
		tfmu.SetName(*s)
	}
	return tfmu
}

// ClearName clears the value of the "name" field.
func (tfmu *TwoFactorMethodUpdate) ClearName() *TwoFactorMethodUpdate {
	tfmu.mutation.ClearName()
	return tfmu
}

// SetSecretEncrypted sets the "secret_encrypted" field.
func (tfmu *TwoFactorMethodUpdate) SetSecretEncrypted(s string) *TwoFactorMethodUpdate {
	tfmu.mutation.SetSecretEncrypted(s)
	return tfmu
}

// SetNillableSecretEncrypted sets the "secret_encrypted" field if the given value is not nil.
func (tfmu *TwoFactorMethodUpdate) SetNillableSecretEncrypted(s *string) *TwoFactorMethodUpdate {
	if s != nil {
		tfmu.SetSecretEncrypted(*s)
	}
	return tfmu
}

// ClearSecretEncrypted clears the value of the "secret_encrypted" field.
func (tfmu *TwoFactorMethodUpdate) ClearSecretEncrypted() *TwoFactorMethodUpdate {
	tfmu.mutation.ClearSecretEncrypted()
	return tfmu
}

// SetCredentialID sets the "credential_id" field.
func (tfmu *TwoFactorMethodUpdate) SetCredentialID(s string) *TwoFactorMethodUpdate {
	tfmu.mutation.SetCredentialID(s)
	return tfmu
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (tfmu *TwoFactorMethodUpdate) SetNillableCredentialID(s *string) *TwoFactorMethodUpdate {
	if s != nil {
		tfmu.SetCredentialID(*s)
	}
	return tfmu
}

// ClearCredentialID clears the value of the "credential_id" field.
func (tfmu *TwoFactorMethodUpdate) ClearCredentialID() *TwoFactorMethodUpdate {
	tfmu.mutation.ClearCredentialID()
	return tfmu
}

// SetPublicKey sets the "public_key" field.
func (tfmu *TwoFactorMethodUpdate) SetPublicKey(b []byte) *TwoFactorMethodUpdate {
	tfmu.mutation.SetPublicKey(b)
	return tfmu
}

// ClearPublicKey clears the value of the "public_key" field.
func (tfmu *TwoFactorMethodUpdate) ClearPublicKey() *TwoFactorMethodUpdate {
	tfmu.mutation.ClearPublicKey()
	return tfmu
}

// SetIsEnabled sets the "is_enabled" field.
func (tfmu *TwoFactorMethodUpdate) SetIsEnabled(b bool) *TwoFactorMethodUpdate {
	tfmu.mutation.SetIsEnabled(b)
	return tfmu
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (tfmu *TwoFactorMethodUpdate) SetNillableIsEnabled(b *bool) *TwoFactorMethodUpdate {
	if b != nil {
		tfmu.SetIsEnabled(*b)
	}
	return tfmu
}

// SetLastUsedAt sets the "last_used_at" field.
func (tfmu *TwoFactorMethodUpdate) SetLastUsedAt(t time.Time) *TwoFactorMethodUpdate {
	tfmu.mutation.SetLastUsedAt(t)
	return tfmu
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (tfmu *TwoFactorMethodUpdate) SetNillableLastUsedAt(t *time.Time) *TwoFactorMethodUpdate {
	if t != nil {
		tfmu.SetLastUsedAt(*t)
	}
	return tfmu
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (tfmu *TwoFactorMethodUpdate) ClearLastUsedAt() *TwoFactorMethodUpdate {
	tfmu.mutation.ClearLastUsedAt()
	return tfmu
}

// SetUser sets the "user" edge to the User entity.
func (tfmu *TwoFactorMethodUpdate) SetUser(u *User) *TwoFactorMethodUpdate {
	return tfmu.SetUserID(u.ID)
}

// Mutation returns the TwoFactorMethodMutation object of the builder.
func (tfmu *TwoFactorMethodUpdate) Mutation() *TwoFactorMethodMutation {
	return tfmu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (tfmu *TwoFactorMethodUpdate) ClearUser() *TwoFactorMethodUpdate {
	tfmu.mutation.ClearUser()
	return tfmu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tfmu *TwoFactorMethodUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tfmu.sqlSave, tfmu.mutation, tfmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tfmu *TwoFactorMethodUpdate) SaveX(ctx context.Context) int {
	affected, err := tfmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tfmu *TwoFactorMethodUpdate) Exec(ctx context.Context) error {
	_, err := tfmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tfmu *TwoFactorMethodUpdate) ExecX(ctx context.Context) {
	if err := tfmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tfmu *TwoFactorMethodUpdate) check() error {
	if v, ok := tfmu.mutation.UserID(); ok {
		if err := twofactormethod.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "TwoFactorMethod.user_id": %w`, err)}
		}
	}
	if v, ok := tfmu.mutation.GetType(); ok {
		if err := twofactormethod.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TwoFactorMethod.type": %w`, err)}
		}
	}
	if tfmu.mutation.UserCleared() && len(tfmu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TwoFactorMethod.user"`)
	}
	return nil
}

func (tfmu *TwoFactorMethodUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tfmu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(twofactormethod.Table, twofactormethod.Columns, sqlgraph.NewFieldSpec(twofactormethod.FieldID, field.TypeString))
	if ps := tfmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tfmu.mutation.GetType(); ok {
		_spec.SetField(twofactormethod.FieldType, field.TypeEnum, value)
	}
	if value, ok := tfmu.mutation.Name(); ok {
		_spec.SetField(twofactormethod.FieldName, field.TypeString, value)
	}
	if tfmu.mutation.NameCleared() {
		_spec.ClearField(twofactormethod.FieldName, field.TypeString)
	}
	if value, ok := tfmu.mutation.SecretEncrypted(); ok {
		_spec.SetField(twofactormethod.FieldSecretEncrypted, field.TypeString, value)
	}
	if tfmu.mutation.SecretEncryptedCleared() {
		_spec.ClearField(twofactormethod.FieldSecretEncrypted, field.TypeString)
	}
	if value, ok := tfmu.mutation.CredentialID(); ok {
		_spec.SetField(twofactormethod.FieldCredentialID, field.TypeString, value)
	}
	if tfmu.mutation.CredentialIDCleared() {
		_spec.ClearField(twofactormethod.FieldCredentialID, field.TypeString)
	}
	if value, ok := tfmu.mutation.PublicKey(); ok {
		_spec.SetField(twofactormethod.FieldPublicKey, field.TypeBytes, value)
	}
	if tfmu.mutation.PublicKeyCleared() {
		_spec.ClearField(twofactormethod.FieldPublicKey, field.TypeBytes)
	}
	if value, ok := tfmu.mutation.IsEnabled(); ok {
		_spec.SetField(twofactormethod.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := tfmu.mutation.LastUsedAt(); ok {
		_spec.SetField(twofactormethod.FieldLastUsedAt, field.TypeTime, value)
	}
	if tfmu.mutation.LastUsedAtCleared() {
		_spec.ClearField(twofactormethod.FieldLastUsedAt, field.TypeTime)
	}
	if tfmu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   twofactormethod.UserTable,
			Columns: []string{twofactormethod.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tfmu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   twofactormethod.UserTable,
			Columns: []string{twofactormethod.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tfmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{twofactormethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tfmu.mutation.done = true
	return n, nil
}

// TwoFactorMethodUpdateOne is the builder for updating a single TwoFactorMethod entity.
type TwoFactorMethodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TwoFactorMethodMutation
}

// SetUserID sets the "user_id" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetUserID(s string) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetUserID(s)
	return tfmuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tfmuo *TwoFactorMethodUpdateOne) SetNillableUserID(s *string) *TwoFactorMethodUpdateOne {
	if s != nil {
		tfmuo.SetUserID(*s)
	}
	return tfmuo
}

// SetType sets the "type" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetType(t twofactormethod.Type) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetType(t)
	return tfmuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tfmuo *TwoFactorMethodUpdateOne) SetNillableType(t *twofactormethod.Type) *TwoFactorMethodUpdateOne {
	if t != nil {
		tfmuo.SetType(*t)
	}
	return tfmuo
}

// SetName sets the "name" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetName(s string) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetName(s)
	return tfmuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tfmuo *TwoFactorMethodUpdateOne) SetNillableName(s *string) *TwoFactorMethodUpdateOne {
	if s != nil {
		tfmuo.SetName(*s)
	}
	return tfmuo
}

// ClearName clears the value of the "name" field.
func (tfmuo *TwoFactorMethodUpdateOne) ClearName() *TwoFactorMethodUpdateOne {
	tfmuo.mutation.ClearName()
	return tfmuo
}

// SetSecretEncrypted sets the "secret_encrypted" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetSecretEncrypted(s string) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetSecretEncrypted(s)
	return tfmuo
}

// SetNillableSecretEncrypted sets the "secret_encrypted" field if the given value is not nil.
func (tfmuo *TwoFactorMethodUpdateOne) SetNillableSecretEncrypted(s *string) *TwoFactorMethodUpdateOne {
	if s != nil {
		tfmuo.SetSecretEncrypted(*s)
	}
	return tfmuo
}

// ClearSecretEncrypted clears the value of the "secret_encrypted" field.
func (tfmuo *TwoFactorMethodUpdateOne) ClearSecretEncrypted() *TwoFactorMethodUpdateOne {
	tfmuo.mutation.ClearSecretEncrypted()
	return tfmuo
}

// SetCredentialID sets the "credential_id" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetCredentialID(s string) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetCredentialID(s)
	return tfmuo
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (tfmuo *TwoFactorMethodUpdateOne) SetNillableCredentialID(s *string) *TwoFactorMethodUpdateOne {
	if s != nil {
		tfmuo.SetCredentialID(*s)
	}
	return tfmuo
}

// ClearCredentialID clears the value of the "credential_id" field.
func (tfmuo *TwoFactorMethodUpdateOne) ClearCredentialID() *TwoFactorMethodUpdateOne {
	tfmuo.mutation.ClearCredentialID()
	return tfmuo
}

// SetPublicKey sets the "public_key" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetPublicKey(b []byte) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetPublicKey(b)
	return tfmuo
}

// ClearPublicKey clears the value of the "public_key" field.
func (tfmuo *TwoFactorMethodUpdateOne) ClearPublicKey() *TwoFactorMethodUpdateOne {
	tfmuo.mutation.ClearPublicKey()
	return tfmuo
}

// SetIsEnabled sets the "is_enabled" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetIsEnabled(b bool) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetIsEnabled(b)
	return tfmuo
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (tfmuo *TwoFactorMethodUpdateOne) SetNillableIsEnabled(b *bool) *TwoFactorMethodUpdateOne {
	if b != nil {
		tfmuo.SetIsEnabled(*b)
	}
	return tfmuo
}

// SetLastUsedAt sets the "last_used_at" field.
func (tfmuo *TwoFactorMethodUpdateOne) SetLastUsedAt(t time.Time) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.SetLastUsedAt(t)
	return tfmuo
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (tfmuo *TwoFactorMethodUpdateOne) SetNillableLastUsedAt(t *time.Time) *TwoFactorMethodUpdateOne {
	if t != nil {
		tfmuo.SetLastUsedAt(*t)
	}
	return tfmuo
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (tfmuo *TwoFactorMethodUpdateOne) ClearLastUsedAt() *TwoFactorMethodUpdateOne {
	tfmuo.mutation.ClearLastUsedAt()
	return tfmuo
}

// SetUser sets the "user" edge to the User entity.
func (tfmuo *TwoFactorMethodUpdateOne) SetUser(u *User) *TwoFactorMethodUpdateOne {
	return tfmuo.SetUserID(u.ID)
}

// Mutation returns the TwoFactorMethodMutation object of the builder.
func (tfmuo *TwoFactorMethodUpdateOne) Mutation() *TwoFactorMethodMutation {
	return tfmuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (tfmuo *TwoFactorMethodUpdateOne) ClearUser() *TwoFactorMethodUpdateOne {
	tfmuo.mutation.ClearUser()
	return tfmuo
}

// Where appends a list predicates to the TwoFactorMethodUpdate builder.
func (tfmuo *TwoFactorMethodUpdateOne) Where(ps ...predicate.TwoFactorMethod) *TwoFactorMethodUpdateOne {
	tfmuo.mutation.Where(ps...)
	return tfmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tfmuo *TwoFactorMethodUpdateOne) Select(field string, fields ...string) *TwoFactorMethodUpdateOne {
	tfmuo.fields = append([]string{field}, fields...)
	return tfmuo
}

// Save executes the query and returns the updated TwoFactorMethod entity.
func (tfmuo *TwoFactorMethodUpdateOne) Save(ctx context.Context) (*TwoFactorMethod, error) {
	return withHooks(ctx, tfmuo.sqlSave, tfmuo.mutation, tfmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tfmuo *TwoFactorMethodUpdateOne) SaveX(ctx context.Context) *TwoFactorMethod {
	node, err := tfmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tfmuo *TwoFactorMethodUpdateOne) Exec(ctx context.Context) error {
	_, err := tfmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tfmuo *TwoFactorMethodUpdateOne) ExecX(ctx context.Context) {
	if err := tfmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tfmuo *TwoFactorMethodUpdateOne) check() error {
	if v, ok := tfmuo.mutation.UserID(); ok {
		if err := twofactormethod.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "TwoFactorMethod.user_id": %w`, err)}
		}
	}
	if v, ok := tfmuo.mutation.GetType(); ok {
		if err := twofactormethod.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TwoFactorMethod.type": %w`, err)}
		}
	}
	if tfmuo.mutation.UserCleared() && len(tfmuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TwoFactorMethod.user"`)
	}
	return nil
}

func (tfmuo *TwoFactorMethodUpdateOne) sqlSave(ctx context.Context) (_node *TwoFactorMethod, err error) {
	if err := tfmuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(twofactormethod.Table, twofactormethod.Columns, sqlgraph.NewFieldSpec(twofactormethod.FieldID, field.TypeString))
	id, ok := tfmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TwoFactorMethod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tfmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, twofactormethod.FieldID)
		for _, f := range fields {
			if !twofactormethod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != twofactormethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tfmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tfmuo.mutation.GetType(); ok {
		_spec.SetField(twofactormethod.FieldType, field.TypeEnum, value)
	}
	if value, ok := tfmuo.mutation.Name(); ok {
		_spec.SetField(twofactormethod.FieldName, field.TypeString, value)
	}
	if tfmuo.mutation.NameCleared() {
		_spec.ClearField(twofactormethod.FieldName, field.TypeString)
	}
	if value, ok := tfmuo.mutation.SecretEncrypted(); ok {
		_spec.SetField(twofactormethod.FieldSecretEncrypted, field.TypeString, value)
	}
	if tfmuo.mutation.SecretEncryptedCleared() {
		_spec.ClearField(twofactormethod.FieldSecretEncrypted, field.TypeString)
	}
	if value, ok := tfmuo.mutation.CredentialID(); ok {
		_spec.SetField(twofactormethod.FieldCredentialID, field.TypeString, value)
	}
	if tfmuo.mutation.CredentialIDCleared() {
		_spec.ClearField(twofactormethod.FieldCredentialID, field.TypeString)
	}
	if value, ok := tfmuo.mutation.PublicKey(); ok {
		_spec.SetField(twofactormethod.FieldPublicKey, field.TypeBytes, value)
	}
	if tfmuo.mutation.PublicKeyCleared() {
		_spec.ClearField(twofactormethod.FieldPublicKey, field.TypeBytes)
	}
	if value, ok := tfmuo.mutation.IsEnabled(); ok {
		_spec.SetField(twofactormethod.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := tfmuo.mutation.LastUsedAt(); ok {
		_spec.SetField(twofactormethod.FieldLastUsedAt, field.TypeTime, value)
	}
	if tfmuo.mutation.LastUsedAtCleared() {
		_spec.ClearField(twofactormethod.FieldLastUsedAt, field.TypeTime)
	}
	if tfmuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   twofactormethod.UserTable,
			Columns: []string{twofactormethod.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tfmuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   twofactormethod.UserTable,
			Columns: []string{twofactormethod.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TwoFactorMethod{config: tfmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tfmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{twofactormethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tfmuo.mutation.done = true
	return _node, nil
}
