// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/user"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/useripsubnethistory"
)

// UserIpSubnetHistoryQuery is the builder for querying UserIpSubnetHistory entities.
type UserIpSubnetHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []useripsubnethistory.OrderOption
	inters     []Interceptor
	predicates []predicate.UserIpSubnetHistory
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserIpSubnetHistoryQuery builder.
func (uishq *UserIpSubnetHistoryQuery) Where(ps ...predicate.UserIpSubnetHistory) *UserIpSubnetHistoryQuery {
	uishq.predicates = append(uishq.predicates, ps...)
	return uishq
}

// Limit the number of records to be returned by this query.
func (uishq *UserIpSubnetHistoryQuery) Limit(limit int) *UserIpSubnetHistoryQuery {
	uishq.ctx.Limit = &limit
	return uishq
}

// Offset to start from.
func (uishq *UserIpSubnetHistoryQuery) Offset(offset int) *UserIpSubnetHistoryQuery {
	uishq.ctx.Offset = &offset
	return uishq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uishq *UserIpSubnetHistoryQuery) Unique(unique bool) *UserIpSubnetHistoryQuery {
	uishq.ctx.Unique = &unique
	return uishq
}

// Order specifies how the records should be ordered.
func (uishq *UserIpSubnetHistoryQuery) Order(o ...useripsubnethistory.OrderOption) *UserIpSubnetHistoryQuery {
	uishq.order = append(uishq.order, o...)
	return uishq
}

// QueryUser chains the current query on the "user" edge.
func (uishq *UserIpSubnetHistoryQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: uishq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uishq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uishq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(useripsubnethistory.Table, useripsubnethistory.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, useripsubnethistory.UserTable, useripsubnethistory.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uishq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserIpSubnetHistory entity from the query.
// Returns a *NotFoundError when no UserIpSubnetHistory was found.
func (uishq *UserIpSubnetHistoryQuery) First(ctx context.Context) (*UserIpSubnetHistory, error) {
	nodes, err := uishq.Limit(1).All(setContextOp(ctx, uishq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{useripsubnethistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) FirstX(ctx context.Context) *UserIpSubnetHistory {
	node, err := uishq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserIpSubnetHistory ID from the query.
// Returns a *NotFoundError when no UserIpSubnetHistory ID was found.
func (uishq *UserIpSubnetHistoryQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = uishq.Limit(1).IDs(setContextOp(ctx, uishq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{useripsubnethistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) FirstIDX(ctx context.Context) string {
	id, err := uishq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserIpSubnetHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserIpSubnetHistory entity is found.
// Returns a *NotFoundError when no UserIpSubnetHistory entities are found.
func (uishq *UserIpSubnetHistoryQuery) Only(ctx context.Context) (*UserIpSubnetHistory, error) {
	nodes, err := uishq.Limit(2).All(setContextOp(ctx, uishq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{useripsubnethistory.Label}
	default:
		return nil, &NotSingularError{useripsubnethistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) OnlyX(ctx context.Context) *UserIpSubnetHistory {
	node, err := uishq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserIpSubnetHistory ID in the query.
// Returns a *NotSingularError when more than one UserIpSubnetHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (uishq *UserIpSubnetHistoryQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = uishq.Limit(2).IDs(setContextOp(ctx, uishq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{useripsubnethistory.Label}
	default:
		err = &NotSingularError{useripsubnethistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) OnlyIDX(ctx context.Context) string {
	id, err := uishq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserIpSubnetHistories.
func (uishq *UserIpSubnetHistoryQuery) All(ctx context.Context) ([]*UserIpSubnetHistory, error) {
	ctx = setContextOp(ctx, uishq.ctx, ent.OpQueryAll)
	if err := uishq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserIpSubnetHistory, *UserIpSubnetHistoryQuery]()
	return withInterceptors[[]*UserIpSubnetHistory](ctx, uishq, qr, uishq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) AllX(ctx context.Context) []*UserIpSubnetHistory {
	nodes, err := uishq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserIpSubnetHistory IDs.
func (uishq *UserIpSubnetHistoryQuery) IDs(ctx context.Context) (ids []string, err error) {
	if uishq.ctx.Unique == nil && uishq.path != nil {
		uishq.Unique(true)
	}
	ctx = setContextOp(ctx, uishq.ctx, ent.OpQueryIDs)
	if err = uishq.Select(useripsubnethistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) IDsX(ctx context.Context) []string {
	ids, err := uishq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uishq *UserIpSubnetHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uishq.ctx, ent.OpQueryCount)
	if err := uishq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uishq, querierCount[*UserIpSubnetHistoryQuery](), uishq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) CountX(ctx context.Context) int {
	count, err := uishq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uishq *UserIpSubnetHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uishq.ctx, ent.OpQueryExist)
	switch _, err := uishq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uishq *UserIpSubnetHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := uishq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserIpSubnetHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uishq *UserIpSubnetHistoryQuery) Clone() *UserIpSubnetHistoryQuery {
	if uishq == nil {
		return nil
	}
	return &UserIpSubnetHistoryQuery{
		config:     uishq.config,
		ctx:        uishq.ctx.Clone(),
		order:      append([]useripsubnethistory.OrderOption{}, uishq.order...),
		inters:     append([]Interceptor{}, uishq.inters...),
		predicates: append([]predicate.UserIpSubnetHistory{}, uishq.predicates...),
		withUser:   uishq.withUser.Clone(),
		// clone intermediate query.
		sql:  uishq.sql.Clone(),
		path: uishq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uishq *UserIpSubnetHistoryQuery) WithUser(opts ...func(*UserQuery)) *UserIpSubnetHistoryQuery {
	query := (&UserClient{config: uishq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uishq.withUser = query
	return uishq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserIpSubnetHistory.Query().
//		GroupBy(useripsubnethistory.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uishq *UserIpSubnetHistoryQuery) GroupBy(field string, fields ...string) *UserIpSubnetHistoryGroupBy {
	uishq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserIpSubnetHistoryGroupBy{build: uishq}
	grbuild.flds = &uishq.ctx.Fields
	grbuild.label = useripsubnethistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.UserIpSubnetHistory.Query().
//		Select(useripsubnethistory.FieldUserID).
//		Scan(ctx, &v)
func (uishq *UserIpSubnetHistoryQuery) Select(fields ...string) *UserIpSubnetHistorySelect {
	uishq.ctx.Fields = append(uishq.ctx.Fields, fields...)
	sbuild := &UserIpSubnetHistorySelect{UserIpSubnetHistoryQuery: uishq}
	sbuild.label = useripsubnethistory.Label
	sbuild.flds, sbuild.scan = &uishq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserIpSubnetHistorySelect configured with the given aggregations.
func (uishq *UserIpSubnetHistoryQuery) Aggregate(fns ...AggregateFunc) *UserIpSubnetHistorySelect {
	return uishq.Select().Aggregate(fns...)
}

func (uishq *UserIpSubnetHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uishq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uishq); err != nil {
				return err
			}
		}
	}
	for _, f := range uishq.ctx.Fields {
		if !useripsubnethistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uishq.path != nil {
		prev, err := uishq.path(ctx)
		if err != nil {
			return err
		}
		uishq.sql = prev
	}
	return nil
}

func (uishq *UserIpSubnetHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserIpSubnetHistory, error) {
	var (
		nodes       = []*UserIpSubnetHistory{}
		_spec       = uishq.querySpec()
		loadedTypes = [1]bool{
			uishq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserIpSubnetHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserIpSubnetHistory{config: uishq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uishq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uishq.withUser; query != nil {
		if err := uishq.loadUser(ctx, query, nodes, nil,
			func(n *UserIpSubnetHistory, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uishq *UserIpSubnetHistoryQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserIpSubnetHistory, init func(*UserIpSubnetHistory), assign func(*UserIpSubnetHistory, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*UserIpSubnetHistory)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uishq *UserIpSubnetHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uishq.querySpec()
	_spec.Node.Columns = uishq.ctx.Fields
	if len(uishq.ctx.Fields) > 0 {
		_spec.Unique = uishq.ctx.Unique != nil && *uishq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uishq.driver, _spec)
}

func (uishq *UserIpSubnetHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(useripsubnethistory.Table, useripsubnethistory.Columns, sqlgraph.NewFieldSpec(useripsubnethistory.FieldID, field.TypeString))
	_spec.From = uishq.sql
	if unique := uishq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uishq.path != nil {
		_spec.Unique = true
	}
	if fields := uishq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useripsubnethistory.FieldID)
		for i := range fields {
			if fields[i] != useripsubnethistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if uishq.withUser != nil {
			_spec.Node.AddColumnOnce(useripsubnethistory.FieldUserID)
		}
	}
	if ps := uishq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uishq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uishq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uishq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uishq *UserIpSubnetHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uishq.driver.Dialect())
	t1 := builder.Table(useripsubnethistory.Table)
	columns := uishq.ctx.Fields
	if len(columns) == 0 {
		columns = useripsubnethistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uishq.sql != nil {
		selector = uishq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uishq.ctx.Unique != nil && *uishq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uishq.predicates {
		p(selector)
	}
	for _, p := range uishq.order {
		p(selector)
	}
	if offset := uishq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uishq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserIpSubnetHistoryGroupBy is the group-by builder for UserIpSubnetHistory entities.
type UserIpSubnetHistoryGroupBy struct {
	selector
	build *UserIpSubnetHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uishgb *UserIpSubnetHistoryGroupBy) Aggregate(fns ...AggregateFunc) *UserIpSubnetHistoryGroupBy {
	uishgb.fns = append(uishgb.fns, fns...)
	return uishgb
}

// Scan applies the selector query and scans the result into the given value.
func (uishgb *UserIpSubnetHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uishgb.build.ctx, ent.OpQueryGroupBy)
	if err := uishgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserIpSubnetHistoryQuery, *UserIpSubnetHistoryGroupBy](ctx, uishgb.build, uishgb, uishgb.build.inters, v)
}

func (uishgb *UserIpSubnetHistoryGroupBy) sqlScan(ctx context.Context, root *UserIpSubnetHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uishgb.fns))
	for _, fn := range uishgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uishgb.flds)+len(uishgb.fns))
		for _, f := range *uishgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uishgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uishgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserIpSubnetHistorySelect is the builder for selecting fields of UserIpSubnetHistory entities.
type UserIpSubnetHistorySelect struct {
	*UserIpSubnetHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uishs *UserIpSubnetHistorySelect) Aggregate(fns ...AggregateFunc) *UserIpSubnetHistorySelect {
	uishs.fns = append(uishs.fns, fns...)
	return uishs
}

// Scan applies the selector query and scans the result into the given value.
func (uishs *UserIpSubnetHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uishs.ctx, ent.OpQuerySelect)
	if err := uishs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserIpSubnetHistoryQuery, *UserIpSubnetHistorySelect](ctx, uishs.UserIpSubnetHistoryQuery, uishs, uishs.inters, v)
}

func (uishs *UserIpSubnetHistorySelect) sqlScan(ctx context.Context, root *UserIpSubnetHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uishs.fns))
	for _, fn := range uishs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uishs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uishs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
