// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/webhookendpoint"
)

// WebhookEndpointDelete is the builder for deleting a WebhookEndpoint entity.
type WebhookEndpointDelete struct {
	config
	hooks    []Hook
	mutation *WebhookEndpointMutation
}

// Where appends a list predicates to the WebhookEndpointDelete builder.
func (wed *WebhookEndpointDelete) Where(ps ...predicate.WebhookEndpoint) *WebhookEndpointDelete {
	wed.mutation.Where(ps...)
	return wed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wed *WebhookEndpointDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wed.sqlExec, wed.mutation, wed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wed *WebhookEndpointDelete) ExecX(ctx context.Context) int {
	n, err := wed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wed *WebhookEndpointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(webhookendpoint.Table, sqlgraph.NewFieldSpec(webhookendpoint.FieldID, field.TypeString))
	if ps := wed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wed.mutation.done = true
	return affected, err
}

// WebhookEndpointDeleteOne is the builder for deleting a single WebhookEndpoint entity.
type WebhookEndpointDeleteOne struct {
	wed *WebhookEndpointDelete
}

// Where appends a list predicates to the WebhookEndpointDelete builder.
func (wedo *WebhookEndpointDeleteOne) Where(ps ...predicate.WebhookEndpoint) *WebhookEndpointDeleteOne {
	wedo.wed.mutation.Where(ps...)
	return wedo
}

// Exec executes the deletion query.
func (wedo *WebhookEndpointDeleteOne) Exec(ctx context.Context) error {
	n, err := wedo.wed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{webhookendpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wedo *WebhookEndpointDeleteOne) ExecX(ctx context.Context) {
	if err := wedo.Exec(ctx); err != nil {
		panic(err)
	}
}
