// Code generated by ent, DO NOT EDIT.

package twofactormethod

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldName, v))
}

// SecretEncrypted applies equality check predicate on the "secret_encrypted" field. It's identical to SecretEncryptedEQ.
func SecretEncrypted(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldSecretEncrypted, v))
}

// CredentialID applies equality check predicate on the "credential_id" field. It's identical to CredentialIDEQ.
func CredentialID(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldCredentialID, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v []byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldPublicKey, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldIsEnabled, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContainsFold(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldType, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContainsFold(FieldName, v))
}

// SecretEncryptedEQ applies the EQ predicate on the "secret_encrypted" field.
func SecretEncryptedEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldSecretEncrypted, v))
}

// SecretEncryptedNEQ applies the NEQ predicate on the "secret_encrypted" field.
func SecretEncryptedNEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldSecretEncrypted, v))
}

// SecretEncryptedIn applies the In predicate on the "secret_encrypted" field.
func SecretEncryptedIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldSecretEncrypted, vs...))
}

// SecretEncryptedNotIn applies the NotIn predicate on the "secret_encrypted" field.
func SecretEncryptedNotIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldSecretEncrypted, vs...))
}

// SecretEncryptedGT applies the GT predicate on the "secret_encrypted" field.
func SecretEncryptedGT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldSecretEncrypted, v))
}

// SecretEncryptedGTE applies the GTE predicate on the "secret_encrypted" field.
func SecretEncryptedGTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldSecretEncrypted, v))
}

// SecretEncryptedLT applies the LT predicate on the "secret_encrypted" field.
func SecretEncryptedLT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldSecretEncrypted, v))
}

// SecretEncryptedLTE applies the LTE predicate on the "secret_encrypted" field.
func SecretEncryptedLTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldSecretEncrypted, v))
}

// SecretEncryptedContains applies the Contains predicate on the "secret_encrypted" field.
func SecretEncryptedContains(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContains(FieldSecretEncrypted, v))
}

// SecretEncryptedHasPrefix applies the HasPrefix predicate on the "secret_encrypted" field.
func SecretEncryptedHasPrefix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasPrefix(FieldSecretEncrypted, v))
}

// SecretEncryptedHasSuffix applies the HasSuffix predicate on the "secret_encrypted" field.
func SecretEncryptedHasSuffix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasSuffix(FieldSecretEncrypted, v))
}

// SecretEncryptedIsNil applies the IsNil predicate on the "secret_encrypted" field.
func SecretEncryptedIsNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIsNull(FieldSecretEncrypted))
}

// SecretEncryptedNotNil applies the NotNil predicate on the "secret_encrypted" field.
func SecretEncryptedNotNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotNull(FieldSecretEncrypted))
}

// SecretEncryptedEqualFold applies the EqualFold predicate on the "secret_encrypted" field.
func SecretEncryptedEqualFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEqualFold(FieldSecretEncrypted, v))
}

// SecretEncryptedContainsFold applies the ContainsFold predicate on the "secret_encrypted" field.
func SecretEncryptedContainsFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContainsFold(FieldSecretEncrypted, v))
}

// CredentialIDEQ applies the EQ predicate on the "credential_id" field.
func CredentialIDEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credential_id" field.
func CredentialIDNEQ(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credential_id" field.
func CredentialIDIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credential_id" field.
func CredentialIDNotIn(vs ...string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDGT applies the GT predicate on the "credential_id" field.
func CredentialIDGT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldCredentialID, v))
}

// CredentialIDGTE applies the GTE predicate on the "credential_id" field.
func CredentialIDGTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldCredentialID, v))
}

// CredentialIDLT applies the LT predicate on the "credential_id" field.
func CredentialIDLT(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldCredentialID, v))
}

// CredentialIDLTE applies the LTE predicate on the "credential_id" field.
func CredentialIDLTE(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldCredentialID, v))
}

// CredentialIDContains applies the Contains predicate on the "credential_id" field.
func CredentialIDContains(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContains(FieldCredentialID, v))
}

// CredentialIDHasPrefix applies the HasPrefix predicate on the "credential_id" field.
func CredentialIDHasPrefix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasPrefix(FieldCredentialID, v))
}

// CredentialIDHasSuffix applies the HasSuffix predicate on the "credential_id" field.
func CredentialIDHasSuffix(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldHasSuffix(FieldCredentialID, v))
}

// CredentialIDIsNil applies the IsNil predicate on the "credential_id" field.
func CredentialIDIsNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIsNull(FieldCredentialID))
}

// CredentialIDNotNil applies the NotNil predicate on the "credential_id" field.
func CredentialIDNotNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotNull(FieldCredentialID))
}

// CredentialIDEqualFold applies the EqualFold predicate on the "credential_id" field.
func CredentialIDEqualFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEqualFold(FieldCredentialID, v))
}

// CredentialIDContainsFold applies the ContainsFold predicate on the "credential_id" field.
func CredentialIDContainsFold(v string) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldContainsFold(FieldCredentialID, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v []byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v []byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...[]byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...[]byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v []byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v []byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v []byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v []byte) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyIsNil applies the IsNil predicate on the "public_key" field.
func PublicKeyIsNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIsNull(FieldPublicKey))
}

// PublicKeyNotNil applies the NotNil predicate on the "public_key" field.
func PublicKeyNotNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotNull(FieldPublicKey))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldIsEnabled, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TwoFactorMethod) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TwoFactorMethod) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TwoFactorMethod) predicate.TwoFactorMethod {
	return predicate.TwoFactorMethod(sql.NotPredicates(p))
}
