// Code generated by ent, DO NOT EDIT.

package securityblacklist

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldTenantID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldUserID, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldIPAddress, v))
}

// Subnet applies equality check predicate on the "subnet" field. It's identical to SubnetEQ.
func Subnet(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldSubnet, v))
}

// FingerprintHash applies equality check predicate on the "fingerprint_hash" field. It's identical to FingerprintHashEQ.
func FingerprintHash(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldFingerprintHash, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldReason, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContainsFold(FieldTenantID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContainsFold(FieldUserID, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContainsFold(FieldIPAddress, v))
}

// SubnetEQ applies the EQ predicate on the "subnet" field.
func SubnetEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldSubnet, v))
}

// SubnetNEQ applies the NEQ predicate on the "subnet" field.
func SubnetNEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldSubnet, v))
}

// SubnetIn applies the In predicate on the "subnet" field.
func SubnetIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldSubnet, vs...))
}

// SubnetNotIn applies the NotIn predicate on the "subnet" field.
func SubnetNotIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldSubnet, vs...))
}

// SubnetGT applies the GT predicate on the "subnet" field.
func SubnetGT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldSubnet, v))
}

// SubnetGTE applies the GTE predicate on the "subnet" field.
func SubnetGTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldSubnet, v))
}

// SubnetLT applies the LT predicate on the "subnet" field.
func SubnetLT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldSubnet, v))
}

// SubnetLTE applies the LTE predicate on the "subnet" field.
func SubnetLTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldSubnet, v))
}

// SubnetContains applies the Contains predicate on the "subnet" field.
func SubnetContains(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContains(FieldSubnet, v))
}

// SubnetHasPrefix applies the HasPrefix predicate on the "subnet" field.
func SubnetHasPrefix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasPrefix(FieldSubnet, v))
}

// SubnetHasSuffix applies the HasSuffix predicate on the "subnet" field.
func SubnetHasSuffix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasSuffix(FieldSubnet, v))
}

// SubnetIsNil applies the IsNil predicate on the "subnet" field.
func SubnetIsNil() predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIsNull(FieldSubnet))
}

// SubnetNotNil applies the NotNil predicate on the "subnet" field.
func SubnetNotNil() predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotNull(FieldSubnet))
}

// SubnetEqualFold applies the EqualFold predicate on the "subnet" field.
func SubnetEqualFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEqualFold(FieldSubnet, v))
}

// SubnetContainsFold applies the ContainsFold predicate on the "subnet" field.
func SubnetContainsFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContainsFold(FieldSubnet, v))
}

// FingerprintHashEQ applies the EQ predicate on the "fingerprint_hash" field.
func FingerprintHashEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldFingerprintHash, v))
}

// FingerprintHashNEQ applies the NEQ predicate on the "fingerprint_hash" field.
func FingerprintHashNEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldFingerprintHash, v))
}

// FingerprintHashIn applies the In predicate on the "fingerprint_hash" field.
func FingerprintHashIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldFingerprintHash, vs...))
}

// FingerprintHashNotIn applies the NotIn predicate on the "fingerprint_hash" field.
func FingerprintHashNotIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldFingerprintHash, vs...))
}

// FingerprintHashGT applies the GT predicate on the "fingerprint_hash" field.
func FingerprintHashGT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldFingerprintHash, v))
}

// FingerprintHashGTE applies the GTE predicate on the "fingerprint_hash" field.
func FingerprintHashGTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldFingerprintHash, v))
}

// FingerprintHashLT applies the LT predicate on the "fingerprint_hash" field.
func FingerprintHashLT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldFingerprintHash, v))
}

// FingerprintHashLTE applies the LTE predicate on the "fingerprint_hash" field.
func FingerprintHashLTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldFingerprintHash, v))
}

// FingerprintHashContains applies the Contains predicate on the "fingerprint_hash" field.
func FingerprintHashContains(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContains(FieldFingerprintHash, v))
}

// FingerprintHashHasPrefix applies the HasPrefix predicate on the "fingerprint_hash" field.
func FingerprintHashHasPrefix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasPrefix(FieldFingerprintHash, v))
}

// FingerprintHashHasSuffix applies the HasSuffix predicate on the "fingerprint_hash" field.
func FingerprintHashHasSuffix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasSuffix(FieldFingerprintHash, v))
}

// FingerprintHashIsNil applies the IsNil predicate on the "fingerprint_hash" field.
func FingerprintHashIsNil() predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIsNull(FieldFingerprintHash))
}

// FingerprintHashNotNil applies the NotNil predicate on the "fingerprint_hash" field.
func FingerprintHashNotNil() predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotNull(FieldFingerprintHash))
}

// FingerprintHashEqualFold applies the EqualFold predicate on the "fingerprint_hash" field.
func FingerprintHashEqualFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEqualFold(FieldFingerprintHash, v))
}

// FingerprintHashContainsFold applies the ContainsFold predicate on the "fingerprint_hash" field.
func FingerprintHashContainsFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContainsFold(FieldFingerprintHash, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldContainsFold(FieldReason, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SecurityBlacklist) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SecurityBlacklist) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SecurityBlacklist) predicate.SecurityBlacklist {
	return predicate.SecurityBlacklist(sql.NotPredicates(p))
}
