// Code generated by ent, DO NOT EDIT.

package socialauthstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/hanan-bhatti/authn-2.0/apps/auth-engine/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldTenantID, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldApplicationID, v))
}

// Environment applies equality check predicate on the "environment" field. It's identical to EnvironmentEQ.
func Environment(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldEnvironment, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldProvider, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldRedirectURI, v))
}

// PostCallbackRedirect applies equality check predicate on the "post_callback_redirect" field. It's identical to PostCallbackRedirectEQ.
func PostCallbackRedirect(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldPostCallbackRedirect, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContainsFold(FieldTenantID, v))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldApplicationID, vs...))
}

// ApplicationIDGT applies the GT predicate on the "application_id" field.
func ApplicationIDGT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldApplicationID, v))
}

// ApplicationIDGTE applies the GTE predicate on the "application_id" field.
func ApplicationIDGTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldApplicationID, v))
}

// ApplicationIDLT applies the LT predicate on the "application_id" field.
func ApplicationIDLT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldApplicationID, v))
}

// ApplicationIDLTE applies the LTE predicate on the "application_id" field.
func ApplicationIDLTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldApplicationID, v))
}

// ApplicationIDContains applies the Contains predicate on the "application_id" field.
func ApplicationIDContains(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContains(FieldApplicationID, v))
}

// ApplicationIDHasPrefix applies the HasPrefix predicate on the "application_id" field.
func ApplicationIDHasPrefix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasPrefix(FieldApplicationID, v))
}

// ApplicationIDHasSuffix applies the HasSuffix predicate on the "application_id" field.
func ApplicationIDHasSuffix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasSuffix(FieldApplicationID, v))
}

// ApplicationIDEqualFold applies the EqualFold predicate on the "application_id" field.
func ApplicationIDEqualFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEqualFold(FieldApplicationID, v))
}

// ApplicationIDContainsFold applies the ContainsFold predicate on the "application_id" field.
func ApplicationIDContainsFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContainsFold(FieldApplicationID, v))
}

// EnvironmentEQ applies the EQ predicate on the "environment" field.
func EnvironmentEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldEnvironment, v))
}

// EnvironmentNEQ applies the NEQ predicate on the "environment" field.
func EnvironmentNEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldEnvironment, v))
}

// EnvironmentIn applies the In predicate on the "environment" field.
func EnvironmentIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldEnvironment, vs...))
}

// EnvironmentNotIn applies the NotIn predicate on the "environment" field.
func EnvironmentNotIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldEnvironment, vs...))
}

// EnvironmentGT applies the GT predicate on the "environment" field.
func EnvironmentGT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldEnvironment, v))
}

// EnvironmentGTE applies the GTE predicate on the "environment" field.
func EnvironmentGTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldEnvironment, v))
}

// EnvironmentLT applies the LT predicate on the "environment" field.
func EnvironmentLT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldEnvironment, v))
}

// EnvironmentLTE applies the LTE predicate on the "environment" field.
func EnvironmentLTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldEnvironment, v))
}

// EnvironmentContains applies the Contains predicate on the "environment" field.
func EnvironmentContains(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContains(FieldEnvironment, v))
}

// EnvironmentHasPrefix applies the HasPrefix predicate on the "environment" field.
func EnvironmentHasPrefix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasPrefix(FieldEnvironment, v))
}

// EnvironmentHasSuffix applies the HasSuffix predicate on the "environment" field.
func EnvironmentHasSuffix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasSuffix(FieldEnvironment, v))
}

// EnvironmentEqualFold applies the EqualFold predicate on the "environment" field.
func EnvironmentEqualFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEqualFold(FieldEnvironment, v))
}

// EnvironmentContainsFold applies the ContainsFold predicate on the "environment" field.
func EnvironmentContainsFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContainsFold(FieldEnvironment, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContainsFold(FieldProvider, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContainsFold(FieldRedirectURI, v))
}

// PostCallbackRedirectEQ applies the EQ predicate on the "post_callback_redirect" field.
func PostCallbackRedirectEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectNEQ applies the NEQ predicate on the "post_callback_redirect" field.
func PostCallbackRedirectNEQ(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectIn applies the In predicate on the "post_callback_redirect" field.
func PostCallbackRedirectIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldPostCallbackRedirect, vs...))
}

// PostCallbackRedirectNotIn applies the NotIn predicate on the "post_callback_redirect" field.
func PostCallbackRedirectNotIn(vs ...string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldPostCallbackRedirect, vs...))
}

// PostCallbackRedirectGT applies the GT predicate on the "post_callback_redirect" field.
func PostCallbackRedirectGT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectGTE applies the GTE predicate on the "post_callback_redirect" field.
func PostCallbackRedirectGTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectLT applies the LT predicate on the "post_callback_redirect" field.
func PostCallbackRedirectLT(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectLTE applies the LTE predicate on the "post_callback_redirect" field.
func PostCallbackRedirectLTE(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectContains applies the Contains predicate on the "post_callback_redirect" field.
func PostCallbackRedirectContains(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContains(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectHasPrefix applies the HasPrefix predicate on the "post_callback_redirect" field.
func PostCallbackRedirectHasPrefix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasPrefix(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectHasSuffix applies the HasSuffix predicate on the "post_callback_redirect" field.
func PostCallbackRedirectHasSuffix(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldHasSuffix(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectIsNil applies the IsNil predicate on the "post_callback_redirect" field.
func PostCallbackRedirectIsNil() predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIsNull(FieldPostCallbackRedirect))
}

// PostCallbackRedirectNotNil applies the NotNil predicate on the "post_callback_redirect" field.
func PostCallbackRedirectNotNil() predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotNull(FieldPostCallbackRedirect))
}

// PostCallbackRedirectEqualFold applies the EqualFold predicate on the "post_callback_redirect" field.
func PostCallbackRedirectEqualFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEqualFold(FieldPostCallbackRedirect, v))
}

// PostCallbackRedirectContainsFold applies the ContainsFold predicate on the "post_callback_redirect" field.
func PostCallbackRedirectContainsFold(v string) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldContainsFold(FieldPostCallbackRedirect, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SocialAuthState) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SocialAuthState) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SocialAuthState) predicate.SocialAuthState {
	return predicate.SocialAuthState(sql.NotPredicates(p))
}
