// Code generated by ent, DO NOT EDIT.

package webhookevent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the webhookevent type in the database.
	Label = "webhook_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWebhookEndpointID holds the string denoting the webhook_endpoint_id field in the database.
	FieldWebhookEndpointID = "webhook_endpoint_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeWebhookEndpoint holds the string denoting the webhook_endpoint edge name in mutations.
	EdgeWebhookEndpoint = "webhook_endpoint"
	// Table holds the table name of the webhookevent in the database.
	Table = "webhook_events"
	// WebhookEndpointTable is the table that holds the webhook_endpoint relation/edge.
	WebhookEndpointTable = "webhook_events"
	// WebhookEndpointInverseTable is the table name for the WebhookEndpoint entity.
	// It exists in this package in order to avoid circular dependency with the "webhookendpoint" package.
	WebhookEndpointInverseTable = "webhook_endpoints"
	// WebhookEndpointColumn is the table column denoting the webhook_endpoint relation/edge.
	WebhookEndpointColumn = "webhook_endpoint_id"
)

// Columns holds all SQL columns for webhookevent fields.
var Columns = []string{
	FieldID,
	FieldWebhookEndpointID,
	FieldEventType,
	FieldPayload,
	FieldStatusCode,
	FieldResponseBody,
	FieldErrorMessage,
	FieldStatus,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// WebhookEndpointIDValidator is a validator for the "webhook_endpoint_id" field. It is called by the builders before save.
	WebhookEndpointIDValidator func(string) error
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusSuccess Status = "success"
	StatusFailed  Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSuccess, StatusFailed:
		return nil
	default:
		return fmt.Errorf("webhookevent: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the WebhookEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWebhookEndpointID orders the results by the webhook_endpoint_id field.
func ByWebhookEndpointID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebhookEndpointID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByResponseBody orders the results by the response_body field.
func ByResponseBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBody, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByWebhookEndpointField orders the results by webhook_endpoint field.
func ByWebhookEndpointField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWebhookEndpointStep(), sql.OrderByField(field, opts...))
	}
}
func newWebhookEndpointStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WebhookEndpointInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WebhookEndpointTable, WebhookEndpointColumn),
	)
}
