/*
 * Authn Platform — Enterprise Identity Engine
 * File: apps/auth-engine/pkg/jwt/rsa.go
 * Tier: Shared Package / RSA Signing Key Management
 *
 * RS256 signing for OIDC ID tokens, together with the persistence of the RSA
 * private key that signs them.
 *
 * ID tokens are verified by relying parties, not by this engine, which is why
 * they are asymmetric where access tokens are not: a relying party needs the
 * public half to check a signature, and must never hold anything that could
 * forge one. The public half is published as JWKS; the private half never
 * leaves the process.
 *
 * Key identity has to survive a restart. Generating a fresh key on every boot
 * would invalidate every outstanding ID token and break relying parties that
 * cached the key set, so the key is persisted on first use and reloaded
 * thereafter.
 *
 * Persistence goes through the KeyStore interface. The file-backed
 * implementation here suits a single instance; several replicas each holding
 * their own file would sign with keys the others do not publish, so a
 * multi-replica deployment needs a shared implementation backed by the database
 * or a KMS.
 *
 * License: GNU AGPLv3 — Copyright (C) Authn Platform Authors
 */

package jwt

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"sync"
)

const (
	// defaultRSAKeyPath is the last-resort location for the signing key, used
	// when neither the caller nor the environment names one.
	defaultRSAKeyPath = ".keys/rsa_private.pem"

	// rsaKeyPathEnvVar names the environment variable consulted when the caller
	// passes no path.
	rsaKeyPathEnvVar = "AUTHN_RSA_KEY_PATH"

	// rsaKeyBits is the modulus size for generated keys. RFC 7518 sets 2048
	// bits as the floor for RS256, and relying parties reject anything smaller.
	rsaKeyBits = 2048

	// keyFileMode keeps the private key readable only by its owner. A signing
	// key that is group- or world-readable lets any local account mint tokens
	// for any user.
	keyFileMode = 0600

	// keyDirMode restricts the containing directory to its owner, so the key
	// cannot be replaced by another local account.
	keyDirMode = 0700
)

// globalRSAKey caches the process-wide signing key so that signing a token does
// not re-read and re-parse the key file. globalRSALock guards it.
var (
	globalRSALock sync.RWMutex
	globalRSAKey  *rsa.PrivateKey
)

// KeyStore abstracts where the RSA private key lives, so a deployment can move
// from a local file to a database or KMS without touching signing code.
type KeyStore interface {
	// LoadKey returns the stored key, or (nil, nil) when none is stored yet.
	LoadKey() (*rsa.PrivateKey, error)
	// SaveKey persists a key, overwriting any existing one.
	SaveKey(key *rsa.PrivateKey) error
}

// FileKeyStore stores the private key as a PEM file on local disk.
type FileKeyStore struct {
	// FilePath is the PEM file's location. An empty path disables persistence:
	// LoadKey and SaveKey both become no-ops, and the caller gets an in-memory
	// key that does not survive a restart.
	FilePath string
}

// LoadKey reads and parses the PEM-encoded private key.
//
// Returns (nil, nil) when no key is stored — an empty path or a missing file.
// That is not an error: it is the signal that a key must be generated, and
// callers distinguish it from failure by the nil error.
//
// Returns an error when the file exists but cannot be read, contains no PEM
// block, or holds something that is not an RSA private key. Those are startup
// failures; overwriting an unreadable key file would silently invalidate every
// token signed under the key it was meant to hold.
func (f *FileKeyStore) LoadKey() (*rsa.PrivateKey, error) {
	if f.FilePath == "" {
		return nil, nil
	}

	data, err := os.ReadFile(f.FilePath)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed reading RSA key file %s: %w", f.FilePath, err)
	}

	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("failed decoding PEM block from %s", f.FilePath)
	}

	// Both encodings are accepted because the two are not distinguishable from
	// the PEM type alone in the wild: keys generated by older OpenSSL versions
	// are PKCS#1, newer ones and most KMS exports are PKCS#8.
	if key, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
		return key, nil
	}

	if keyInterface, err := x509.ParsePKCS8PrivateKey(block.Bytes); err == nil {
		if rsaKey, ok := keyInterface.(*rsa.PrivateKey); ok {
			return rsaKey, nil
		}
	}

	return nil, fmt.Errorf("unrecognized or invalid RSA private key format in %s", f.FilePath)
}

// SaveKey writes the private key as a PKCS#1 PEM file, creating the containing
// directory if needed.
//
// Does nothing when the path is empty or the key is nil. Returns an error when
// the directory or file cannot be written.
func (f *FileKeyStore) SaveKey(key *rsa.PrivateKey) error {
	if f.FilePath == "" || key == nil {
		return nil
	}

	dir := filepath.Dir(f.FilePath)
	if err := os.MkdirAll(dir, keyDirMode); err != nil {
		return fmt.Errorf("failed creating directory %s for RSA key: %w", dir, err)
	}

	pemBlock := &pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(key),
	}

	pemBytes := pem.EncodeToMemory(pemBlock)
	if err := os.WriteFile(f.FilePath, pemBytes, keyFileMode); err != nil {
		return fmt.Errorf("failed writing RSA private key to %s: %w", f.FilePath, err)
	}

	return nil
}

// GetOrGenerateRSAPrivateKey returns the process's ID token signing key,
// loading it from disk on first call and generating and persisting one if no
// key is stored yet.
//
// The path is taken from the optional keyPath argument, then the
// AUTHN_RSA_KEY_PATH environment variable, then defaultRSAKeyPath. Callers
// inside the engine pass the configured path explicitly; the other two are
// fallbacks for tooling that runs without the configuration layer loaded.
//
// Returns an error when a stored key cannot be read or parsed, when key
// generation fails, or when a newly generated key cannot be persisted. Each is
// a startup failure: continuing would sign tokens with a key that no restart
// can reproduce and no relying party will have seen.
func GetOrGenerateRSAPrivateKey(keyPath ...string) (*rsa.PrivateKey, error) {
	path := defaultRSAKeyPath
	if len(keyPath) > 0 && keyPath[0] != "" {
		path = keyPath[0]
	} else if envPath := os.Getenv(rsaKeyPathEnvVar); envPath != "" {
		path = envPath
	}

	globalRSALock.RLock()
	if globalRSAKey != nil {
		defer globalRSALock.RUnlock()
		return globalRSAKey, nil
	}
	globalRSALock.RUnlock()

	globalRSALock.Lock()
	defer globalRSALock.Unlock()

	// Re-check under the write lock. The read lock was released before it was
	// taken, so a concurrent caller may have populated the cache in between;
	// without this, two goroutines racing at startup would each generate a key
	// and one would overwrite the other's file.
	if globalRSAKey != nil {
		return globalRSAKey, nil
	}

	store := &FileKeyStore{FilePath: path}

	existingKey, err := store.LoadKey()
	if err != nil {
		return nil, fmt.Errorf("failed loading persisted RSA key: %w", err)
	}
	if existingKey != nil {
		globalRSAKey = existingKey
		return globalRSAKey, nil
	}

	newKey, err := rsa.GenerateKey(rand.Reader, rsaKeyBits)
	if err != nil {
		return nil, fmt.Errorf("failed generating RSA 2048 keypair: %w", err)
	}

	// Persist before caching. Serving tokens signed by a key that failed to
	// reach disk would strand every one of them at the next restart.
	if err := store.SaveKey(newKey); err != nil {
		return nil, fmt.Errorf("failed persisting RSA key to disk: %w", err)
	}

	globalRSAKey = newKey
	return globalRSAKey, nil
}

// SignIDTokenRS256 signs claims with an RSA private key and returns a compact
// JWT.
//
// keyID becomes the header's `kid`, which is how a relying party picks the
// right entry out of the published key set. Omitting it would force verifiers
// to try every key and would break rotation, since a key set in a grace period
// holds more than one.
//
// Returns an error if the header or claims cannot be marshalled, or if signing
// fails.
func SignIDTokenRS256(privKey *rsa.PrivateKey, claims interface{}, keyID string) (string, error) {
	headerJSON, err := json.Marshal(map[string]string{
		"alg": "RS256",
		"typ": "JWT",
		"kid": keyID,
	})
	if err != nil {
		return "", fmt.Errorf("failed marshaling RS256 jwt header: %w", err)
	}

	payloadJSON, err := json.Marshal(claims)
	if err != nil {
		return "", fmt.Errorf("failed marshaling RS256 jwt claims: %w", err)
	}

	signingInput := base64.RawURLEncoding.EncodeToString(headerJSON) + "." + base64.RawURLEncoding.EncodeToString(payloadJSON)
	hashed := sha256.Sum256([]byte(signingInput))

	signatureBytes, err := rsa.SignPKCS1v15(rand.Reader, privKey, crypto.SHA256, hashed[:])
	if err != nil {
		return "", fmt.Errorf("failed signing token with RSA private key: %w", err)
	}

	signature := base64.RawURLEncoding.EncodeToString(signatureBytes)
	return signingInput + "." + signature, nil
}

// ExportRSAPublicJWKS renders one RSA public key as a JWKS document.
//
// The modulus and exponent are base64url-encoded big-endian integers with no
// leading zero padding, which is the representation RFC 7518 requires; the
// usual exponent 65537 encodes to "AQAB". Only public values appear, so the
// result is safe to serve unauthenticated.
func ExportRSAPublicJWKS(pubKey *rsa.PublicKey, keyID string) JWKSResponse {
	nBytes := pubKey.N.Bytes()
	eBytes := big.NewInt(int64(pubKey.E)).Bytes()

	return JWKSResponse{
		Keys: []JSONWebKey{
			{
				Kty: "RSA",
				Use: "sig",
				Alg: "RS256",
				Kid: keyID,
				N:   base64.RawURLEncoding.EncodeToString(nBytes),
				E:   base64.RawURLEncoding.EncodeToString(eBytes),
			},
		},
	}
}
