#!/usr/bin/env sh
#
# Authn Platform — Enterprise Identity Engine
# Derives Docker Compose settings from DATABASE_URL.
#
# DATABASE_URL is the single source of truth for the database: its scheme picks
# the engine, and its userinfo, host, port and path carry the credentials. This
# script takes those apart so the bundled postgres container can be configured
# from the same string the engine connects with. Nothing about the database is
# written down twice, so nothing can drift.
#
# It writes .env.compose, which docker-compose.yml reads alongside .env. That
# file is generated on every `make dev` and must not be edited by hand.
#
# Usage: scripts/compose-env.sh [output-file]
#
# License: GNU AGPLv3 — Copyright (C) Authn Platform Authors

set -eu

OUT="${1:-.env.compose}"
ENV_FILE="${ENV_FILE:-.env}"

if [ ! -f "$ENV_FILE" ]; then
    echo "compose-env: $ENV_FILE not found — copy .env.example first" >&2
    exit 1
fi

# Read DATABASE_URL from .env without sourcing the file: sourcing would execute
# whatever is in it, and a stray backtick in a password would run as a command.
raw_url=$(sed -n 's/^[[:space:]]*DATABASE_URL[[:space:]]*=[[:space:]]*//p' "$ENV_FILE" | tail -n 1)
url=$(printf '%s' "$raw_url" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")

if [ -z "$url" ]; then
    echo "compose-env: DATABASE_URL is not set in $ENV_FILE" >&2
    exit 1
fi

scheme=$(printf '%s' "$url" | sed -n 's|^\([a-zA-Z0-9+]*\)://.*|\1|p')
rest=$(printf '%s' "$url" | sed -n 's|^[a-zA-Z0-9+]*://\(.*\)|\1|p')

# Only server-backed engines need a container. sqlite is a file, so a compose
# profile for it would start a database nobody connects to.
case "$scheme" in
    postgres|postgresql) profile="postgres" ;;
    mysql)               profile="mysql" ;;
    sqlite|file|"")      profile="" ;;
    *)
        echo "compose-env: unsupported DATABASE_URL scheme '$scheme'" >&2
        exit 1
        ;;
esac

db_user=""; db_pass=""; db_host=""; db_port=""; db_name=""

if [ -n "$profile" ]; then
    # Split on the last '@', so a password containing '@' does not truncate the
    # host. Everything before it is userinfo; everything after is the address.
    userinfo=$(printf '%s' "$rest" | sed -n 's|^\(.*\)@[^@]*$|\1|p')
    hostpart=$(printf '%s' "$rest" | sed -n 's|^.*@\([^@]*\)$|\1|p')
    if [ -z "$hostpart" ]; then
        hostpart="$rest"
    fi

    db_user=$(printf '%s' "$userinfo" | sed -n 's|^\([^:]*\).*|\1|p')
    db_pass=$(printf '%s' "$userinfo" | sed -n 's|^[^:]*:\(.*\)$|\1|p')

    hostport=$(printf '%s' "$hostpart" | sed -n 's|^\([^/?]*\).*|\1|p')
    db_host=$(printf '%s' "$hostport" | sed -n 's|^\([^:]*\).*|\1|p')
    db_port=$(printf '%s' "$hostport" | sed -n 's|^[^:]*:\([0-9]*\)$|\1|p')
    db_name=$(printf '%s' "$hostpart" | sed -n 's|^[^/]*/\([^?]*\).*|\1|p')

    [ -n "$db_port" ] || db_port=$([ "$profile" = "mysql" ] && echo 3306 || echo 5432)

    # The engine reaches the database by service name inside the compose
    # network, where the host in DATABASE_URL — usually localhost — would mean
    # the engine's own container. Only the host is substituted; credentials,
    # database name and query parameters are carried through unchanged.
    container_url=$(printf '%s' "$url" | sed "s|@${db_host}:|@${profile}:|")
else
    container_url="$url"
fi

redis_url=$(sed -n 's/^[[:space:]]*REDIS_URL[[:space:]]*=[[:space:]]*//p' "$ENV_FILE" | tail -n 1 |
    sed -e 's/^"//' -e 's/"$//')
redis_host=$(printf '%s' "$redis_url" | sed -n 's|^redis://\([^:/]*\).*|\1|p')
redis_container_url="$redis_url"
if [ -n "$redis_host" ]; then
    redis_container_url=$(printf '%s' "$redis_url" | sed "s|//${redis_host}|//redis|")
fi

# The mail catcher follows the same rule as the database: a container is started
# only when the configuration calls for one. EMAIL_DRIVER=smtp against a host on
# this machine means the bundled catcher; a managed relay is left alone.
read_env() {
    sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$ENV_FILE" | tail -n 1 |
        sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
}

email_driver=$(read_env EMAIL_DRIVER)
smtp_host=$(read_env SMTP_HOST)
mailpit_ui_port=$(read_env MAILPIT_UI_PORT)
[ -n "$mailpit_ui_port" ] || mailpit_ui_port=8025

mail_profile=""
smtp_host_container="$smtp_host"
if [ "$email_driver" = "smtp" ]; then
    case "$smtp_host" in
    localhost | 127.0.0.1 | ::1 | mailpit | "")
        mail_profile="mail"
        # Inside the compose network the catcher answers to its service name.
        # SMTP_HOST's usual localhost would mean the engine's own container,
        # where nothing is listening on the SMTP port.
        smtp_host_container="mailpit"
        ;;
    esac
fi

# Profiles are a comma-separated list, so the database and the mail catcher can
# be selected independently.
profiles="$profile"
if [ -n "$mail_profile" ]; then
    profiles="${profiles:+$profiles,}$mail_profile"
fi

cat > "$OUT" <<EOF
# GENERATED by scripts/compose-env.sh — do not edit.
#
# Every value here is derived from DATABASE_URL, REDIS_URL and the mail settings
# in .env. Change those and re-run \`make dev\`; editing this file directly will
# be overwritten and would reintroduce the drift it exists to prevent.

COMPOSE_PROFILES=${profiles}

POSTGRES_USER=${db_user}
POSTGRES_PASSWORD=${db_pass}
POSTGRES_DB=${db_name}
POSTGRES_PORT=${db_port}

MYSQL_USER=${db_user}
MYSQL_PASSWORD=${db_pass}
MYSQL_DATABASE=${db_name}
MYSQL_PORT=${db_port}

MAILPIT_UI_PORT=${mailpit_ui_port}

DATABASE_URL_CONTAINER=${container_url}
REDIS_URL_CONTAINER=${redis_container_url}
SMTP_HOST_CONTAINER=${smtp_host_container}
EOF

if [ -z "$profile" ]; then
    echo "compose-env: DATABASE_URL uses '${scheme}' — no database container will be started."
else
    echo "compose-env: derived ${profile} container settings from DATABASE_URL (db=${db_name} port=${db_port})."
fi

if [ -n "$mail_profile" ]; then
    echo "compose-env: EMAIL_DRIVER=smtp against '${smtp_host:-localhost}' — the Mailpit catcher will be started."
fi
